<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.js')?>"></script> 
<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.min.js')?>"></script> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.css')?>"> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.min.css')?>"> 


<?php 
  $btcatProModel = Mage::getModel('btslider/btproductslider')->getCollection();
  $currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();


  foreach ($btcatProModel as $productslider) {
     $catId = $productslider['categoryid'];

$categoryModel = Mage::getModel('catalog/category')->load($catId);
$catName = $categoryModel->getName();
$productsku = $productslider->getProductSku();
$pro_sku = explode(',',$productsku);

?>
     <div>
          <h3><?php echo __($catName); ?></h3>
    </div>
     <ul class="bxslider">
             <?php 

                    foreach ($pro_sku as $sku) {
  
                        $products = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku); 
                        $productname  = $products['name'];
                        $productprice = $products['price'];
                        $product_image_url = $products->getImageUrl();
                       /* echo "<pre>++";
                        print_r($products->getData());*/
                    ?>
                    <li>
                        <div>
                            <img src="<?php echo $product_image_url ?>" style="height: 260px; width: 350px;" class="img-responsive" alt="a" />
                       </div>
                       <div>
                            <h5><a href="<?php echo $products->getProductUrl(); ?>"><?php echo __($productname); ?></a></h5>
                       <div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $products['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                             </div>
                                             <br>
                                            <h5 class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($productprice,2)); ?></h5>
                                        </div>
                    </li>
           <?php } ?>
     </ul>
<?php } ?>
<script>
var con = jQuery.noConflict();
 con('.bxslider').bxSlider({
  auto: true,
  autoControls: true,
  minSlides: 3,
  maxSlides: 3,
  slideWidth: 360,
  slideMargin: 10
});
</script>