<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.js')?>"></script> 
<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.min.js')?>"></script> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.css')?>"> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.min.css')?>"> 

<div class="topsellingCount">
<div>
    <h3><?php echo __('Top Selling Products'); ?></h3>
</div>

 <ul class="bxslider">
<?php 
 $currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
        $storeId = (int) Mage::app()->getStore()->getId();
 
        // Date
        $date = new Zend_Date();
        $toDate = $date->setDay(1)->getDate()->get('Y-MM-dd');
        $fromDate = $date->subMonth(1)->getDate()->get('Y-MM-dd');
 
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addStoreFilter()
            ->addPriceData()
            ->addTaxPercents()
            ->addUrlRewrite()
            ->setPageSize(6);
 
        $collection->getSelect()
            ->joinLeft(
                array('aggregation' => $collection->getResource()->getTable('sales/bestsellers_aggregated_monthly')),
                "e.entity_id = aggregation.product_id AND aggregation.store_id={$storeId} AND aggregation.period BETWEEN '{$fromDate}' AND '{$toDate}'",
                array('SUM(aggregation.qty_ordered) AS sold_quantity')
            )
            ->group('e.entity_id')
            ->order(array('sold_quantity DESC', 'e.created_at'));
 
        Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);

        foreach ($collection as $collectiondata) {
            $bestProductId = $collectiondata['entity_id'];
            $bestProductData = Mage::getModel('catalog/product')->load($bestProductId);
             $best_product_image_url = $bestProductData->getImageUrl();
/*
            echo "<pre>++";
            print_r($bestProductData->getData());*/
            
                    ?>
                     <a href="<?php echo $bestProductData->getProductUrl(); ?>">
                    <li class="shadow">
                   
                     
                        <div>
                            <img src="<?php echo $best_product_image_url ?>"  class="img-responsive"  />
                       </div>
                       <div class="productNameing">
                           <div class="productsnameInner"><?php echo __($bestProductData->getName()); ?></div>
                       <div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $bestProductData['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                             </div>
                                             <br>
                                            <h5 class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($bestProductData->getPrice(),2)); ?></h5>
                                        </div>
                                         
                    
                    </li>
                    </a>

           <?php 
        }
?>
</ul>
</div>

<!-- Homepage Banner Ad 1 start-->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Homepage-mish-ad-1')->toHtml(); 
?>

<!-- Homepage Banner Ad 1 end -->

<!-- category section starts here -->

<?php 
  $btcatProModel = Mage::getModel('btslider/btproductslider')->getCollection();
 


  foreach ($btcatProModel as $productslider) {
     $catId = $productslider['categoryid'];

$categoryModel = Mage::getModel('catalog/category')->load($catId);
$catName = $categoryModel->getName();
$productsku = $productslider->getProductSku();

if($productsku != ""){
  $pro_sku = explode(',',$productsku);
?>
     <div>
          <h3><?php echo __($catName); ?></h3>
    </div>
     <ul class="bxslider">
             <?php 

                    foreach ($pro_sku as $sku) {
  
                        $products = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku); 
                        $productname  = $products['name'];
                        $productprice = $products['price'];
                        $product_image_url = $products->getImageUrl();
                       /* echo "<pre>++";
                        print_r($products->getData());*/
                    ?>
                     <a href="<?php echo $products->getProductUrl(); ?>">
                    <li class="shadow">
                   
                  
                        <div>
                            <img src="<?php echo $product_image_url ?>"  class="img-responsive" alt="a" />
                       </div>
                       <div>
                            <h5 style="text-align: center;"><?php echo __($productname); ?></h5>
                       </div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $products['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                            
                                             <br>
                                            <h5 style="text-align: center;" class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($productprice,2)); ?></h5>
                                        
                            </li>
                         </a>
                 
           <?php } ?>
     </ul>
<?php } }?>

<!-- Homepage Banner Ad 2 start-->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Homepage-mish-ad-2')->toHtml(); 
?>

<!-- Homepage Banner Ad 2 end -->
<!-- Top moving product section start here -->
<div>
  
<?php
   $movingproductsku = Mage::getStoreConfig('fastmovingprpoducts/movingproducts/fastmoving');
   if($movingproductsku != ""){ ?>
   <div>
      <h3><?php echo __('Fast Moving Products'); ?></h3>
  </div>
<ul class="bxsliderfast">
<?php 
   $movingproductExplode = explode(',' ,$movingproductsku);

   foreach ($movingproductExplode as $ProductSku) {
    $productModel = Mage::getModel('catalog/product')->loadByAttribute('sku',$ProductSku);
    $productUrl = $productModel->getProductUrl();
    $product_image = $productModel->getImageUrl();  
 ?>
 <a href="<?php echo $productUrl;?>"><li class="shadow"><img src="<?php echo $product_image; ?>"></li></a>
<?php } ?>
</ul>
<?php }?>

</div>
<!-- Top moving product section end here -->


<!-- Category and brand section start here -->
<?php 
$catbrandModel = Mage::getModel('btslider/btcatbrand')->getCollection();
$i=0;
foreach ($catbrandModel as $catbrandData) {
   $catid = $catbrandData['catid'];
   $brands = $catbrandData['brand_name'];
   $featuredimage = $catbrandData['featured_image'];
   $imageone = $catbrandData['imageone'];
   $imagetwo = $catbrandData['imagetwo'];
   $brandexplode = explode(',',$brands);
   $catModel = Mage::getModel('catalog/category')->load($catid);
   $catname = $catModel->getName();
   $caturl = $catModel->getUrl();
   if($catid != ""){

   	$color = array('#444653','#4f6184','#e9e9e9');
   	$fontcolor = array('#fff','#fff','#000');
 ?>
<div class="womensCategory">
  <?php// for ($i=0; $i <count($color) ; $i++) { ?>
    <div  class="womensCategoryleft" style="background:<?php echo $color[$i]; ?>">
          <ul>
          <span><a href="<?php echo $caturl; ?>" style="color: <?php echo $fontcolor[$i]; ?>"><?php echo $catname;?></a></span>
          <?php foreach($brandexplode as $brand){?>
          <li><a href ="#" style="color: <?php echo $fontcolor[$i]; ?>"><?php echo $brand;?></a></li>
          <?php } ?>
</ul>
    </div>
    <?php// } ?>
    <div class="womensCategoryMid">
         <a href="<?php echo $caturl; ?>"> <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$featuredimage; ?>"> </a>
    </div>

    <div  class="womensCategoryRight">
        <div class="imageF"> <a href="<?php echo $caturl; ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$imageone; ?>"></a></div>
        <div> <a href="<?php echo $caturl; ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$imagetwo; ?>"></a></div>
    </div>
    <div class="clr"></div>
</div>

<?php } $i++;} ?>
<!-- Category and brand section end herejfgjgyjgjgy -->

<script>
var con = jQuery.noConflict();
 con('.bxslider').bxSlider({
  /*auto: true,
  autoControls: true,*/
  minSlides: 4,
  maxSlides: 4,
  slideWidth: 360,
  slideMargin: 10
});
</script>

<script>
var con = jQuery.noConflict();
 con('.bxsliderfast').bxSlider({
  auto: true,
  autoControls: true,
  minSlides: 4,
  maxSlides: 4,
  slideWidth: 360,
  slideMargin: 10
});
</script>

<style>
.bx-pager{display: none}
 .topsellingCount {
    margin-left: 153px !important;
}
.shadow:hover{
box-shadow: 0 5px 5px rgba(182, 182, 182, 0.75);}
.productsnameInner {
    height: auto;
}

</style>