<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.js')?>"></script> 
<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.bxslider.min.js')?>"></script> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.css')?>"> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('custom/css/jquery.bxslider.min.css')?>"> 

<div class="topsellingCount">
<div>
    <h3><?php echo __('Top Selling Product'); ?></h3>
</div>

 <ul class="bxslider">
<?php 
 $currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
        $storeId = (int) Mage::app()->getStore()->getId();
 
        // Date
        $date = new Zend_Date();
        $toDate = $date->setDay(1)->getDate()->get('Y-MM-dd');
        $fromDate = $date->subMonth(1)->getDate()->get('Y-MM-dd');
 
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addStoreFilter()
            ->addPriceData()
            ->addTaxPercents()
            ->addUrlRewrite()
            ->setPageSize(6);
 
        $collection->getSelect()
            ->joinLeft(
                array('aggregation' => $collection->getResource()->getTable('sales/bestsellers_aggregated_monthly')),
                "e.entity_id = aggregation.product_id AND aggregation.store_id={$storeId} AND aggregation.period BETWEEN '{$fromDate}' AND '{$toDate}'",
                array('SUM(aggregation.qty_ordered) AS sold_quantity')
            )
            ->group('e.entity_id')
            ->order(array('sold_quantity DESC', 'e.created_at'));
 
        Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);

        foreach ($collection as $collectiondata) {
            $bestProductId = $collectiondata['entity_id'];
            $bestProductData = Mage::getModel('catalog/product')->load($bestProductId);
             $best_product_image_url = $bestProductData->getImageUrl();
/*
            echo "<pre>++";
            print_r($bestProductData->getData());*/
            
                    ?>
                    <li>
                        <div>
                            <img src="<?php echo $best_product_image_url ?>"  class="img-responsive"  />
                       </div>
                       <div class="productNameing">
                           <div class="productsnameInner"><a href="<?php echo $bestProductData->getProductUrl(); ?>"><?php echo __($bestProductData->getName()); ?></a></div>
                       <div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $bestProductData['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                             </div>
                                             <br>
                                            <h5 class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($bestProductData->getPrice(),2)); ?></h5>
                                        </div>
                    </li>
           <?php 
        }
?>
</ul>
</div>

<!-- Homepage Banner Ad 1 start-->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Homepage-mish-ad-1')->toHtml(); 
?>

<!-- Homepage Banner Ad 1 end -->

<!-- category section starts here -->

<?php 
  $btcatProModel = Mage::getModel('btslider/btproductslider')->getCollection();
 


  foreach ($btcatProModel as $productslider) {
     $catId = $productslider['categoryid'];

$categoryModel = Mage::getModel('catalog/category')->load($catId);
$catName = $categoryModel->getName();
$productsku = $productslider->getProductSku();
$pro_sku = explode(',',$productsku);

?>
     <div>
          <h3><?php echo __($catName); ?></h3>
    </div>
     <ul class="bxslider">
             <?php 

                    foreach ($pro_sku as $sku) {
  
                        $products = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku); 
                        $productname  = $products['name'];
                        $productprice = $products['price'];
                        $product_image_url = $products->getImageUrl();
                       /* echo "<pre>++";
                        print_r($products->getData());*/
                    ?>
                    <li>
                        <div>
                            <img src="<?php echo $product_image_url ?>"  class="img-responsive" alt="a" />
                       </div>
                       <div>
                            <h5><a href="<?php echo $products->getProductUrl(); ?>"><?php echo __($productname); ?></a></h5>
                       <div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $products['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                             </div>
                                             <br>
                                            <h5 class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($productprice,2)); ?></h5>
                                        </div>
                    </li>
           <?php } ?>
     </ul>
<?php } ?>

<!-- Homepage Banner Ad 2 start-->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('Homepage-mish-ad-2')->toHtml(); 
?>

<!-- Homepage Banner Ad 2 end -->

<script>
var con = jQuery.noConflict();
 con('.bxslider').bxSlider({
  auto: true,
  autoControls: true,
  minSlides: 4,
  maxSlides: 4,
  slideWidth: 360,
  slideMargin: 10
});
</script>