<?php
$order = $this->getTrackyourorder();
$shipTrack = array();
        if ($order) {
            $shipments = $order->getShipmentsCollection();
            foreach ($shipments as $shipment){
                $increment_id = $shipment->getIncrementId();
                $tracks = $shipment->getTracksCollection();

                $trackingInfos=array();
                foreach ($tracks as $track){
                    $trackingInfos[] = $track->getNumberDetail();
                }
                $shipTrack[$increment_id] = $trackingInfos;
            }
        }
?> 
<?php  $_results = $shipTrack; ?>

 <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Your Order Information') ?></h2>
<p><?php echo $this->__("Your Order Status is :")?> <strong><?php echo $order->getStatusLabel() ?></strong></p>

<?php if(sizeof($_results)>0): ?>
<?php foreach($_results as $shipid => $_result): ?>
    <?php if($shipid): ?>
    <h4><?php echo $this->__('Shipment #').$shipid; ?></h4>
    <?php endif; ?>
    <?php if(sizeof($_result)>0): ?>
        <?php $rowCount = sizeof($_result); $counter = 1; ?>
        <?php foreach($_result as $track): ?>
        <table class="data-table track-data-table">
            <col width="15%" />
            <col />
            <tbody>
                <?php if(is_object($track)): ?>
                <tr>
                    <th><?php echo $this->__('Tracking Number:'); ?></th>
                    <td><?php echo $track->getTracking(); ?></td>
                </tr>
                <?php if ($track->getCarrierTitle()): ?>
                <tr>
                    <th><?php echo $this->__('Carrier:'); ?></th>
                    <td><?php echo $track->getCarrierTitle(); ?></td>
                </tr>
            <?php

switch ($track->getCarrierTitle()) {
    case "DHL":
        $url = "http://www.dhl.com/";
        break;
    case "DHL (Deprecated)":
        $url = "http://www.dhl.com/";
        break;
    case "Federal Express":
        $url = "http://www.fedex.com/";
        break;
     case "United States Postal Service":
        $url = "https://tools.usps.com";
        break;
     case "United Parcel Service":
        $url = "http://www.ups.com/";
        break;           
    default:
   $i =1 ;
         break;
}
?>
<?php if($i!=1) { ?>
                <tr>
                    <th><?php echo $this->__('More Details:'); ?></th>
                    <td class="error"><a href="<?php echo $url; ?>" onclick="this.target='_blank'"><?php echo $this->__('Click here') ?></a><?php echo $this->__('  to get details  ');?></a>
                    
                    </td>
                </tr>
                <?php } else { ?>
                <th><?php echo $this->__('Notice:'); ?></th>
                    <td class="error"><?php if ((bool) Mage::getStoreConfig('contacts/contacts/enabled')) : ?><a href="<?php echo $this->getUrl('contacts') ?>" onclick="this.target='_blank'"><?php echo $this->__('Click here') ?></a><?php echo $this->__('  to get details or '); endif; echo $this->__('email us at '); ?><a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_support/email'); ?>"><?php echo Mage::getStoreConfig('trans_email/ident_support/email') ?></a>
                    
                    </td>
                </tr>
                <?php } ?>
                <?php endif; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            <?php $counter++; ?>
        
        <?php endforeach; ?>
   
    <?php else: ?>
        <p><?php echo $this->__('There is no tracking Number available for this shipment.'); ?></p>
    <?php endif; ?>

<?php endforeach; ?>
<?php else: ?>
    <div><?php echo $this->__('There is no tracking Number available.'); ?></div>
<?php endif; ?>

</div>