<?php
/**
 * 
 */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
<div class="my-wishlist">
    <div class="page-title">
        <h1><?php echo $this->__('My Wishlist') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->hasWishlistItems()): ?>
    <div class="wishlist-wrap">
        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey')?>
            <ul id="wishlist" data-role="listview" data-theme="c" data-split-theme="c" data-split-icon="delete">
                <?php foreach ($this->getWishlistItems() as $item): ?>
                    <?php
                        $product = $item->getProduct();
                        $isVisibleProduct = $product->isVisibleInSiteVisibility();
                    ?>
                    <li><a href="<?php echo $this->getProductUrl($item) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(80); ?>" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                            <h2>
                                <?php echo $this->escapeHtml($product->getName()) ?>
                                
                            </h2>
                            <?php echo $this->getPriceHtml($product) ?>                        
                            <textarea style="display:none;" name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo $this->__('Comment') ?>"><?php echo $this->getCommentValue($item); ?></textarea>
                        
                        </a>
                        <a href="<?php echo $this->getItemRemoveUrl($item) ?>" title="<?php echo $this->__('Remove') ?>" onclick="return confirmRemoveWishlistItem();" class="btn-remove"><img src="<?php echo $this->getSkinUrl('images/btn_trash.png') ?>" width="10" height="10" alt="<?php echo $this->__('Remove item')?>" /></a>
                    </li>
                <?php endforeach ?>
            </ul>
                <?php if($this->isSaleable()):?>
                <div class="row">
                    <a data-role="button" href="javascript:void(0)" title="<?php echo $this->__('Add All to Cart') ?>" onclick="addAllWItemsToCart()" class="button"><?php echo $this->__('Add All to Cart') ?></a>
                </div>
                <?php endif;?>
        </form>
    </div>
    <?php else: ?>
        <p><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>
    <script type="text/javascript">
    //<![CDATA[
    function confirmRemoveWishlistItem() {
        return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
    }

    function focusComment(obj) {
        if( obj.value == '<?php echo $this->helper('wishlist')->defaultCommentString() ?>' ) {
            obj.value = '';
        } else if( obj.value == '' ) {
            obj.value = '<?php echo $this->helper('wishlist')->defaultCommentString() ?>';
        }
    }

    function addWItemToCart(itemId) {
        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
        url = url.gsub('%item%', itemId);
        var form = $('wishlist-view-form');
        if (form) {
            var input = form['qty[' + itemId + ']'];
            if (input) {
                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
                url += separator + input.name + '=' + encodeURIComponent(input.value);
            }
        }
        setLocation(url);
    }

    function addAllWItemsToCart() {
        var url = '<?php echo $this->getUrl('*/*/allcart') ?>';
        var separator = (url.indexOf('?') >= 0) ? '&' : '?';
        $$('#wishlist-view-form .qty').each(
            function (input, index) {
                url += separator + input.name + '=' + encodeURIComponent(input.value);
                separator = '&';
            }
        );
        setLocation(url);
    }
    //]]>
    </script>
</div>
<?php endif ?>
