<?php
/******************************************************
 * @package Ves Megamenu module for Magento 1.4.x.x and Magento 1.7.x.x
 * @version 1.0.0.1
 * @author http://landofcoder.com
 * @copyright	Copyright (C) December 2010 LandOfCoder.com <@emai:landofcoder@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
$title = $this->getConfig("title");
$enable_offcanvas = Mage::getStoreConfig("ves_verticalmenu/ves_verticalmenu/enable_offcanvas");
?>
<div id="ves-verticalmenu" class="block ves-verticalmenu <?php if(!$enable_offcanvas): ?>hidden-xs hidden-sm<?php else: ?> offcanvas-actived<?php endif; ?>">
	<?php if($title) { ?>
	<div class="block-title <?php if($enable_offcanvas): ?>hidden-xs hidden-sm<?php endif; ?>">
		<strong><span><?php echo $title; ?></span></strong>
		<em class="shapes right"></em>	
		<em class="line"></em>
	</div>
	<?php } ?>
	<div class="block-content">
		<div class="navbar navbar-inverse">
			<div id="verticalmenu" class="verticalmenu offset-canvas-menu-play" role="navigation" data-offcanvas="<?php echo $enable_offcanvas?'true':'false'; ?>">
				<div class="navbar">
					<div class="topclassNav">
						<ul>
							<span>TOP CATEGORIES</span>
							<li><a href="#">All Offers</a></li>
							<li><a href="#">Mobile & Tablet</a></li>
							<li><a href="#">Electronics</a></li>
							<li><a href="#">Computers & Gaming</a></li>
							<li><a href="#">Home & Kitchen</a></li>
							<li><a href="#">Men’s & Clothing</a></li>
							<li><a href="#">Women’s & Clothing</a></li>
						</ul>
					</div>
					<a href="javascript:;" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				     </a>
					<div class="collapse navbar-collapse navbar-ex1-collapse">
						<?php if($menu_top = $this->getChildHtml("verticalmenu.menu.top")): ?>
						<div class="close-mobile-nav close-block hidden-lg hidden-md">
							<?php echo $menu_top;//Top menu content ?>
						</div>
						<?php endif; ?>

						<?php echo $menuHtml;//Main menu content ?>

						<?php if($menu_footer = $this->getChildHtml("verticalmenu.menu.footer")): ?>
						<div class="menu-footer hidden-lg hidden-md">
							<?php echo $menu_footer;//Footer menu content ?>
						</div>
						<?php endif ;?>
					 </div>
					<!-- Off canvas tab icon just show on offcanvasmenu -->
					<div class="navbar-offcanvas-tab hidden">
						<i class="fa fa-bars"></i> <?php echo $this->__("Categories");?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery(window).ready( function(){

	/*  Fix First Click Menu */
	jQuery(document.body).on('click', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
	jQuery(document.body).on('dblclick', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
});
</script>