<?php if ($this->isShowChart()): ?>
<div id="trendchart" style="width: 100%; height: 400px;"></div>
<script type="text/javascript">
    var chart;
    var recipeintTrendData = [];
    <?php foreach ($this->getCollection() as $row): ?>
        recipeintTrendData.push({
            average_rate: '<?php echo $row->getData('average_rate') ?>',
            response_rate: '<?php echo $row->getData('response_rate') ?>',
            date: '<?php echo $row->getData('created_at') ?>'
        });
    <?php endforeach ?>

    AmCharts.ready(function () {
        chart                    = new AmCharts.AmSerialChart();
        chart.pathToImages       = "/js/mirasvit/code/helpdesk/lib/amcharts-3.4.5/images/";
        chart.dataProvider       = recipeintTrendData;
        chart.categoryField      = "date";

        var categoryAxis = chart.categoryAxis;
        categoryAxis.parseDates       = true;
        categoryAxis.minPeriod        = "DD";
        categoryAxis.dashLength       = 1;
        categoryAxis.minorGridEnabled = true;
        categoryAxis.position         = "top";
        categoryAxis.axisColor        = "#DADADA";

        var averageRateAxis = new AmCharts.ValueAxis();
        averageRateAxis.axisAlpha  = 1;
        //averageRateAxis.gridAlpha  = 1;
        averageRateAxis.dashLength = 1;
        averageRateAxis.title      = "Satisfaction Score, %";
        averageRateAxis.inside     = true;
        averageRateAxis.position   = "left";
        chart.addValueAxis(averageRateAxis);

        var graph = new AmCharts.AmGraph();
        graph.valueField        = "average_rate";
        graph.title             = "Satisfaction Score, %";
        graph.valueAxis         = averageRateAxis;
        graph.balloonText       = "Satisfaction Score: [[value]]%";
        graph.type              = "smoothedLine";
        graph.lineColor         = "#5fb503";
        graph.lineAlpha         = 1;
        graph.lineThickness     = 2;
        graph.bulletSize        = 2;
        graph.fillAlphas        = 0.1;
        chart.addGraph(graph);

        var responseRateAxis = new AmCharts.ValueAxis();
        responseRateAxis.axisAlpha  = 1;
        //responseRateAxis.gridAlpha  = 1;
        responseRateAxis.dashLength = 1;
        responseRateAxis.title      = "Response Rate, %";
        responseRateAxis.inside     = true;
        responseRateAxis.position   = "right";
        chart.addValueAxis(responseRateAxis);

        var graph = new AmCharts.AmGraph();
        graph.valueField        = "response_rate";
        graph.title             = "Response Rate, %";
        graph.valueAxis         = responseRateAxis;
        graph.balloonText       = "Response Rate: [[value]]%";
        graph.type              = "smoothedLine";
        graph.lineColor         = "#ff0000";
        graph.lineAlpha         = 1;
        graph.lineThickness     = 2;
        graph.bulletSize        = 2;
        graph.fillAlphas        = 0.1;
        chart.addGraph(graph);


        var legend = new AmCharts.AmLegend();
        legend.equalWidths = false;
        chart.addLegend(legend);

        var chartCursor            = new AmCharts.ChartCursor();
        chartCursor.cursorPosition = "mouse";
        chartCursor.pan            = true;
        chart.addChartCursor(chartCursor);

        var chartScrollbar = new AmCharts.ChartScrollbar();
        chart.addChartScrollbar(chartScrollbar);

        chart.write("trendchart");
    });
</script>
<?php endif;?>