<style>
.block-check-delivery .block-title strong {background-image:none; font-size: 11px;}
.block-check-delivery .block-content {padding:0 10px;  }
</style>
<div class="block block-list block-check-delivery">
 
    <div class="deliveryCount" >	
    <?php $blockLabel = Mage::getStoreConfig('checkdelivery/general/block_title'); ?>
        <span><?php echo $this->__($blockLabel) ?></span>	
		
			<input name="zipcode" size="17" type="text" id="zipcode" maxlength="10" class="input-text" placeholder="<?php echo $this->__('Enter Pincode'); ?>"/>
			
			<input type="button" value="Check" class="inputbutton" name="zip-check" id="zip-check">
			<?php $defaultHtml = Mage::getStoreConfig('checkdelivery/general/default_html'); ?>
			<span id='loading-image' style='display:none'>
			  <img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>'/>
			</span>
			<span id="delivery-html"><?php echo $defaultHtml ?></span>
			<span id="delivery-message"></span>
			
		<br>		
    </div>
</div>


<script>
	Event.observe('zip-check', 'click', function(event){
		
		$('loading-image').show();
		new Ajax.Request("<?php echo $this->getUrl('checkdelivery/index/index') ?>", {
			method: "get",
			parameters: {zipcode : $('zipcode').value },
			onSuccess: function(transport) {
				$('loading-image').hide();
				var json = transport.responseText.evalJSON();
				 $('delivery-message').update(json.message);				 
				 $('delivery-message').setStyle({ color: json.color});
				 $('delivery-html').update(json.html);	
			}
		});
	});
</script>