<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:100%;"><h3 class="icon-head head-blog"><?php echo Mage::helper('ves_blog')->__('Comment Manager') ?></h3></td>
        <td>
            <?php echo $this->getImportButtonHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php  echo $this->getStoreSwitcherHtml() ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>