
<?php 

      $session = Mage::getSingleton('vendors/session');
      $vendorID = $session->getId();
?>
<div>
    <div style="text-align: center;"">
          <h3 ><?php echo __('Manage Commission');?><?php echo __(" (Vendor Id- ".$vendorID).")";?></h3>
    </div>


    <div>

             <?php
                     $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                     $vendorCommissionModel = Mage::getModel('commision/vendorcommision')->getCollection()
                     ->addFieldToFilter('vendor_id',array('eq' => $vendorID));
              ?>


    </div>
    <div class="selectedCategories">
        <table id="example" class="display" cellspacing="0" width="100%">
            <thead>
                  <tr>
                      
                      <th style="padding: 5px;"><?php echo __('Invoice Increment Id');?></th>
                      <th style="padding: 5px;"><?php echo __('Order Id');?></th>
                      <th style="padding: 5px;"><?php echo __('Price');?></th>
                      <th style="padding: 5px;"><?php echo __('Product Name');?></th>
                      <th style="padding: 5px;"><?php echo __('CategoryName');?></th>
                      <th style="padding: 5px;"><?php echo __('Product Quantity');?></th>
                      <th style="padding: 5px;"><?php echo __('Amount (Price X Item Ordered Quantity)');?></th>
                      <th style="padding: 5px;"><?php echo __('Commission Amount (%)');?></th>
                      <th style="padding: 5px;"><?php echo __('Calculated Paid Amount');?></th>
                      <th style="padding: 5px;"><?php echo __('Status');?></th>
                      <th style="padding: 5px;"><?php echo __('Comment');?></th>
                      <th style="padding: 5px;border-right: none;" ><?php echo __('Payment Date and Time');?></th>

                  </tr>
            </thead>
            <tfoot>
                 <tr>
                    <th><?php echo __('Invoice Increment Id');?></th>
                      <th><?php echo __('Order Id');?></th>
                      <th><?php echo __('Price');?></th>
                      <th><?php echo __('Product Name');?></th>
                      <th><?php echo __('CategoryName');?></th>
                      <th><?php echo __('Product Quantity');?></th>
                      <th><?php echo __('Amount (Price X Item Ordered Quantity)');?></th>
                      <th><?php echo __('Commission Amount (%)');?></th>
                      <th><?php echo __('Calculated Paid Amount');?></th>
                      <th><?php echo __('Status');?></th>
                      <th><?php echo __('Comment');?></th>
                      <th><?php echo __('Payment Date and Time');?></th>
                 </tr>
            </tfoot>
             <tbody>
                  <?php 
                        foreach ($vendorCommissionModel as $commissionData) {
                           $id                        = $commissionData['id'];
                           $orderid                   = $commissionData['orderid'];
                           $invoiceincrementId        = $commissionData['invoice_increment_id'];
                           $invoiceincrementId        = $commissionData['invoice_increment_id'];
                           $orderincrementId          = $commissionData['order_increment_id'];
                           $productPrice              = $commissionData['product_amount'];
                           $productCategoryCommission = $commissionData['pro_categorycommision'];
                           $calculatedCommissionAmount= $commissionData['calculated_commission'];
                           $status                    = $commissionData['status'];
                           $paymentDateTime           = $commissionData['payment_datetime'];
                           $actualPrice               = $commissionData['product_actual_price'];
                           $QtyOrdered                = $commissionData['product_qty'];
                           $comment                   = $commissionData['comment'];
                           $productName               = $commissionData['product_name'];
                           $categoryName              = $commissionData['category_name'];
                       
                       
                  ?>
           
                  <tr>

                      <td style="padding: 5px;"><?php echo $invoiceincrementId; ?></td>
                      <td style="padding: 5px;"><a href="<?php echo $this->getBaseUrl().'vendors/sales_order/view/order_id/'.$orderid.''; ?>" target='_blank'><?php echo $orderincrementId; ?></a></td>
                      <td style="padding: 5px;"><?php echo $actualPrice."". $currencySymbol; ?></td>
                      <td style="padding: 5px;"><?php echo $productName ?></td>
                      <td style="padding: 5px;"><?php echo $categoryName; ?></td>
                      <td style="padding: 5px;"><?php echo $QtyOrdered; ?></td>
                      <td style="padding: 5px;"><?php echo $productPrice." ". $currencySymbol;; ?></td>
                      <td style="padding: 5px;"><?php echo $productCategoryCommission; ?></td>
                      <td style="padding: 5px;"><?php echo $calculatedCommissionAmount." ". $currencySymbol;; ?></td>
                      <td style="padding: 5px;">
                          <?php  
                              if($status==0){
                                echo "Unpaid";
                              }else{
                                echo "Paid";
                              }
                         
                           ?>
                         
                       </td>
                       <td style="padding: 5px;"><?php echo $comment; ?></td>
                      <td style="padding: 5px; border-right: none;"><?php echo $paymentDateTime; ?></td>
                      
                      
                    
                  </tr>
           



            <?php } ?>
             </tbody>
          
        </table>
    </div>
</div>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
<!--   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
<style>
 .selectedCategories tr td {border: solid 1px #000; border-bottom: none; border-left: none;  }
 .selectedCategories tr th {border: solid 1px #000; border-bottom: none; border-left: none;  border-top:none;  }
</style>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script> 

<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ves_vendors/js/paging.js')?>"></script> 
<script type="text/javascript">
            var j = jQuery.noConflict();
           /* j(document).ready(function() {
                j('#tableDat').paging({limit:10});
            });*/

            j(document).ready(function() {
    // Setup - add a text input to each footer cell
    j('#example tfoot th').each( function () {
        var title = j(this).text();
       j(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );
 
    // DataTable
    var table = j('#example').DataTable();
 
    // Apply the search
    table.columns().every( function () {
        var that = this;
 
        j( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
} );
</script>

<script type="text/javascript">
    j('.confirmation').on('click', function () {
        return confirm('Are you sure?');
    });
</script>

<style>
  tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }
</style>

