<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_message = $this->getMessage(); ?>
<div class="page-title">
    <h1><?php echo $_message->getTitle() ?></h1>
</div>
<div class="ves_message_container">
	<h3 style="float: left;"><?php echo $_message->getFrom()?></h3>
	<div style="float: right;font-style: italic;"><?php echo $this->formatDate($_message->getCreatedAt()) ?></div>
	<div style="clear: both;border-top: 1px dashed #D3D3D3;margin-bottom: 10px;"></div>
	<?php echo $_message->getContent();?>
</div>
<?php echo $this->getChildHtml('message-form-reply') ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getBackUrl();?>"><small>&laquo; </small><?php echo $this->__('Back')?></a></p>
</div>