<div style="margin-bottom: 30px;">
    <form id="search_form" onsubmit="if(Validation.validate('selectandsell_search')){<?php echo $this->getGridJsObjectName()?>.doFilter();return false;}else return false;">
    <label for="product_id"><?php echo $this->__('Search product in store')?></label>
    <div class=search-box>
        <div style="float:left;margin-right:20px;width:90% !important"><input style="width: 100%;" type="text" class="input-text required-entry" placeholder="<?php echo $this->__('Enter product name')?>" name="name" value="<?php echo $this->getSessionNameParam()?>" id="selectandsell_search"></div>
        <button type="submit" title="<?php echo $this->__('Search')?>'" class="button"><span><span><?php echo $this->__('Search')?></span></span></button>
    </div>
    <div style="clear:both;"></div>
    </form>
</div>
<script type="text/javascript">
    searchForm = new varienForm('search_form', '');
</script>
