<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('pikachoose/css/bottom.css')?>" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pikachoose/js/jquery-1.8.0.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pikachoose/js/jquery.jcarousel.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pikachoose/js/jquery.pikachoose.js') ?>"></script>


<?php $banner = $this->getBanner(); ?>
<?php if(!$banner) echo $this->__('Banner Not Found!'); ?>

<script type="text/javascript">
	$pika = jQuery.noConflict();
	$pika(document).ready(function(){
		$pika("#pikame").PikaChoose({
		
		showTooltips:true,
		transition:[<?php echo $banner->getEasing();?>],
		
		});
		
		$pika(".pika-stage").css({
			'width':'<?php echo $banner->getWidth(); ?>',
			'height':'<?php echo $banner->getHeight(); ?>',
		
		});
		
		$pika(".pika-textnav").css({
			'width':'<?php echo $banner->getWidth(); ?>',
		});
		
		// make thumb pikachoose = width pikastage
		$pika(".pikachoose").css({
			'width':'<?php echo $banner->getWidth() + 20; ?>',
			
		});
		// 5 thumbs image inline
		$pika(".pika-thumbs li").css({
			'width':'<?php echo $banner->getWidth()/5 -18 ?>',
		});
			
	});
	
</script>	

	
<div class="pikachoose">
	<ul id="pikame">
		<?php foreach($this->getItems() as $items): ?>
		<li><img src="<?php echo Mage::helper('bannermanager/image')->init($items->getFilename())->resize($banner->getWidth(),$banner->getHeight()) ?>" title="<?php echo $items->getTitle()?>" alt="" /><span><?php echo $items->getDescription()?></span></li>
		<?php endforeach; ?>
	</ul>
</div>
