<div class="page-title">
    <h1><?php echo $this->__('My Support Tickets') ?></h1>
</div>
<?php 
$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
$customerName = Mage::getSingleton('customer/session')->getCustomer()->getName();
$tickets = $this->getCollection()->addFieldToFilter('customer_id', $customerId);
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$writeConnection = $resource->getConnection('core_write');
$tableName = $resource->getTableName('helpdesk/comment');
?>
<?php echo $this->getPagerHtml(); ?>
<?php if($tickets->getSize()): ?>
<table class="data-table" id="tickets-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />    
    <thead>
        <tr>
            <th><?php echo $this->__('Id') ?></th>
            <th style="width:70%"><?php echo $this->__('Subject') ?></th>
            <th><?php echo $this->__('Replies') ?></th>
            <th><?php echo $this->__('Status') ?></th>			
        </tr>
    </thead>
    <tbody>
      <?php foreach ($tickets as $ticket): ?>		
        <tr onclick="window.location.href='<?php echo Mage::getUrl('helpdesk/index/view',array('id' =>$ticket->getTicketId())) ?>'">
		<?php 
			$ticketId = $ticket->getTicketId();
			$sql = "SELECT count(`comment`) as comment FROM $tableName WHERE  `ticket_id`= $ticketId ";
			$comments = $readConnection->fetchRow($sql);
			$comment = $comments['comment'];
		?>
            <td><?php echo $ticket->getTicketId() ?></td>
            <td><span class="nobr"><?php echo $ticket->getSubject(); ?></span></td>
            <td><span class="nobr"><?php echo $comment; ?></span></td> 
            <td><span class="nobr"><?php echo $ticket->getStatus(); ?></span></td>	
        </tr>
		<?php endforeach; ?>	
    </tbody>
</table>
<script type="text/javascript">decorateTable('tickets-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You do not have any Tickets.'); ?></p>
<?php endif ?>
<form action="<?php echo Mage::getUrl('helpdesk/index/save') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Create new ticket') ?></h2>
		<input type="hidden" name="customer_id" value="<?php echo $customerId; ?>">
        <ul class="form-list">
            <li class="wide">
                <label for="subject" class="required"><em>*</em><?php echo $this->__('Subject') ?></label>
                <div class="input-box">
                    <input name="subject" id="subject" title="<?php echo $this->__('Subject') ?>" value="" class="input-text required-entry" type="text">
                </div>
            </li>
			<li>
				<label for="priority"><?php echo $this->__('Priority')?></label>
				<div class="input-box">
				<?php $priorities = $this->helper('helpdesk')->getAllPriority();?>
                    <select name="priority" id="priority" title="<?php echo $this->__('Priority') ?>">
						<?php foreach($priorities as $priority):?>
							<option value="<?php echo $priority;?>"><?php echo $priority;?></option>
						<?php endforeach;?>
                    </select>
                </div>
			</li>
			<li>
                <label for="order"><?php echo $this->__('Assign to order')?></label>
                <div class="input-box">
				<?php  
				$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
				$orders = Mage::getModel('sales/order')->getCollection()->addAttributeToFilter('customer_id', $customerId);
				?>				
                    <select name="order" id="order" title="<?php echo $this->__('Assign to order')?>">
						<option value="<?php echo $this->__('Unassigned')?>"><?php echo $this->__('Unassigned')?></option>
						<?php foreach($orders as $order):?>
							<option value="<?php echo $order->getData('increment_id'); ?>"><?php echo $order->getData('increment_id'); ?></option>
						<?php endforeach;?>
					</select>
                </div>
            </li>
			<li class="wide">
                <label for="message" class="required"><em>*</em><?php echo $this->__('Message')?></label>
                <div class="input-box">
                    <textarea class="required-entry" name="message" id="message"></textarea>
                </div>
            </li>
        </ul>
    </div>
	 <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button data-action="save-ticket" type="submit" title="<?php echo $this->__('Submit Ticket') ?>" class="button"><span><span><?php echo $this->__('Submit Ticket') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
