<?php /*
<script src="<?php echo $this->getJsUrl('helpdesk/nicEdit-latest.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	bkLib.onDomLoaded(function() {
		new nicEditor({fullPanel : true}).panelInstance(
			document.getElementById('comment')
		);
	});
</script>
*/ ?>
<?php 
	$ticket = Mage::registry('current_ticket');
	$ticketId = $ticket->getTicketId();
	$comments = Mage::getModel('helpdesk/comment')->getCollection()->addFieldToFilter('ticket_id', $ticketId);
	$comments->setOrder('created_date','DESC');
	$loggedInCustomerName = Mage::getSingleton('customer/session')->getCustomer()->getName();	
	$ticketStatus = $ticket->getData('status');
?>
	<div class="page-title">
		<h1>[ <?php echo $ticket->getTicketId(); ?> ] <?php echo $ticket->getSubject(); ?> </h1>
	</div>
	<div class="col-1">
		<div class="fieldset">
		<h2 class="legend"><?php echo $this->__('Ticket Information')?></h2>
		<table class="ticket-view-info-table info-table">
			<tbody>
				<tr>
					<th><span class="nobr"><?php echo $this->__('Status')?></span></th>
					<td><?php echo $ticket->getStatus(); ?></td>
				</tr>
				<tr>
					<th><span class="nobr"><?php echo $this->__('Priority')?></span></th>
					<td><?php echo $ticket->getPriority(); ?></td>
				</tr>
			</tbody>
		</table>
		</div>   
	</div>
	<?php if($ticketStatus!="Closed"):?>
	<form id="ticket-reply-form" action="<?php echo Mage::getUrl('helpdesk/index/comment') ?>" method="post" enctype="multipart/form-data" >
		<input type="hidden" name="ticket_id" value="<?php echo $ticket->getTicketId(); ?>">
		<ul class="form-list">
			<li class="wide">
				<label for="comment" class="required"><em>*</em><?php echo $this->__('Post a Reply')?></label>
				<div class="input-box" style="width:100%">
					<textarea class="required-entry" name="comment" id="comment" ></textarea>
				</div>
			</li>
		</ul>
		<div class="ticket-view-action-bottomgroup-right">
			<nobr>
			<button id="ticket-view-close-btn" title="<?php echo $this->__('Close Ticket')?>" class="button"><span><span><?php echo $this->__('Close Ticket')?></span></span></button>
			<button  id="ticket-view-reply-btn"  title="<?php echo $this->__('Post Reply')?>" class="button"><span><span><?php echo $this->__('Post  Reply')?></span></span></button>
			</nobr>
		</div>
	</form>
	<script type="text/javascript">
		var dataForm = new VarienForm('ticket-reply-form', false);
	</script>
	<script type="text/javascript">
		(function(){
			var closeBtn = $('ticket-view-close-btn');
			if (!closeBtn) {
				return;
			}
			closeBtn.observe('click', function(e){
				e.stop();
				if (confirm("You are near to close the ticket. Are you sure?")) {
					setLocation("<?php echo Mage::getUrl('helpdesk/index/closeticket',array('id' =>$ticket->getTicketId())) ?>");
				}
			});
		})();
	</script>
	<br />
<?php endif;?>	
	<div class="back">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">«<?php echo $this->__('Back to my support tickets')?></a>
    </div>
	<br />	
	<div class="ticket-view-thread">
		<?php foreach($comments as $comment):?>
			<div  class="ticket-view-thread-message-box <?php if($comment->getData('is_customer_comment') == 1):?>  customer-comment <?php endif;?>"  >
				<div class="ticket-view-thread-message-box-header">
					<span class="ticket-view-thread-message-box-header-author"><?php echo $comment->getData('comment_by'); ?></span>
					<span class="separator">|</span>
					<span class="ticket-view-thread-message-box-header-date"><?php echo $comment->getData('created_date');?></span>
				</div>
				<div class="ticket-view-thread-message-box-body">
					<p><?php echo $comment->getData('comment'); ?></p>
				</div>				
			</div>
		<?php endforeach; ?>
			<div class="ticket-view-thread-message-box customer-comment" >
				<div class="ticket-view-thread-message-box-header">
					<span class="ticket-view-thread-message-box-header-author"><?php echo $loggedInCustomerName;?></span>
					<span class="separator">|</span>
					<span class="ticket-view-thread-message-box-header-date"><?php echo $ticket->getCreatedDate();?></span>
				</div>
				<div class="ticket-view-thread-message-box-body">
					<p><?php echo $ticket->getMessage(); ?></p>
				</div>
			</div>
	</div>