<?php
$config = $this->getConfig();
$customer = $this->getCustomer();
?>
<form action="<?php echo $this->getPostUrl()?>" method="POST" id="helpdesk-contact-form" class="helpdesk-contact-form"  enctype="multipart/form-data">
<div class="close" onclick="window.parent.helpdeskFormHide();">&times;</div>
<div class="dropbox">
    <h2 class="legend"><?php echo $config->getFormTitle() ?></h2>
    <div class="inside-form">
        <ul class="form-list">
            <li class="email">
                <label for="email" class="required"><?php echo $this->__("Email") ?><em>*</em></label>
                <div class="input-box">
                    <input  type="text" name='email' id='email' class="input-text">
                </div>
            </li>
            <li>
                <label for="name" class="required"><?php echo $config->getSubjectTitle() ?><em>*</em></label>
                <div class="input-box">
                    <input  type="text" name='name' id='name' class="input-text required-entry" placeholder="<?php echo $config->getSubjectPlaceholder() ?>" value='<?php echo $this->getSearchQuery()?>'>
                </div>
            </li>
            <li>
                <label for="message" class="required"><?php echo $config->getDescriptionTitle() ?><em>*</em></label>
                <div class="input-box">
                    <textarea name='message' id='message'  class="input-text required-entry" placeholder="<?php echo $config->getDescriptionPlaceholder() ?>"></textarea>
                </div>
            </li>
            <?php if (!$customer): ?>
            <div class="customer-details">
                <li class="customer-name">
                    <label for="customer_name" class="required"><?php echo $this->__("Name") ?><em>*</em></label>
                    <div class="input-box">
                        <input  type="text" name='customer_name' id='customer_name' class="input-text required-entry">
                    </div>
                </li>
                <li class="customer-email">
                    <label for="customer_email" class="required"><?php echo $this->__("Email") ?><em>*</em></label>
                    <div class="input-box">
                        <input  type="text" name='customer_email' id='customer_email' class="input-text required-entry validate-email">
                    </div>
                </li>
            </div>
        	<?php endif; ?>
            <div class="fields">
                <?php if ($this->getIsAllowPriority()): ?>
                    <li class="field1">
                        <label for="priority_id"><?php echo $this->__("Priority") ?></label>
                        <div class="input-box">
                            <select name="priority_id" id='priority_id'>
                                <?php foreach ($this->getPriorityCollection() as $priority): ?>
                                    <option value="<?php echo $priority->getId()?>"><?php echo $priority->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </li>
                <?php endif;?>
                <?php if ($this->getIsAllowDepartment()): ?>
                    <li class="field2">
                        <label for="department_id"><?php echo $this->__("Department") ?></label>
                        <div class="input-box">
                            <select name="department_id" id='department_id'>
                                <?php foreach ($this->getDepartmentCollection() as $department): ?>
                                    <option value="<?php echo $department->getId()?>"><?php echo $department->getName()?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </li>
                <?php endif;?>
            </div>
            <?php foreach ($this->getCustomFields() as $field): ?>
            <li class="<?php echo $field->getType()?>">
                <label for="<?php echo $field->getCode()?>" <?php echo $field->getIsRequiredCustomer()?'class="required"><em>*</em>':'>'?><?php echo $this->__($field->getName()) ?></label>
                <div class="input-box <?php echo $field->getType()?>">
                    <?php echo $this->getInputHtml($field)?>
                </div>
                <p><?php echo $field->getDescription() ?></p>
            </li>
            <?php endforeach; ?>
            <?php if ($this->isAttachmentEnabled()) : ?>
            <li class="wide">
                <label for="attachment"><?php echo $this->__("Attach files") ?></label>
                <div class="input-box">
                    <input type='file' class='multi' name='attachment[]' id='attachment'></textarea>
                </div>
            </li>
            <?php endif; ?>

        </ul>
    </div>

    <button type="submit" title="<?php echo $this->__("Submit") ?>" class="post-button" onclick="dataFormSubmit(this)" ><?php echo $this->__("Submit") ?></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('helpdesk-contact-form', true);
    function dataFormSubmit(button){
        if(dataForm.validator &&  dataForm.validator.validate()){
            Form.Element.disable(button);
            dataForm.submit();
        }
    }
//]]>
</script>