<?php
/*
* Ves Base Widget - Single image
*
* @package   vesbase
* @version   5.0
* @author    http://www.venustheme.com
* @copyright Copyright (C) October 2013 venustheme.com <@emai:venustheme@gmail.com>
*               <info@venustheme.com>.All rights reserved.
* @license   GNU General Public License version 2
*/

$html = base64_decode($this->getConfig('html'));

if(isset($thumbnailurl) ):
	$image_alt = (isset($widget_heading)&&!empty($widget_heading))?$widget_heading: Mage::helper("ves_base")->__("Image");
$holder_image = isset($holder_image)?$holder_image:"";
?>
<div class="widget-images block <?php echo $addition_cls; ?> <?php echo isset($animation)&&$animation?$animation:''; ?> <?php echo isset($stylecls)&&$stylecls?'block-'.$stylecls:'';?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<?php echo $widget_heading; ?>
		</div>
	<?php endif; ?>
	<div class="widget-inner block-content clearfix">
		<div class="image-item">
			<?php if ($ispopup): ?>
				<a href="<?php echo $imageurl; ?>" class="ves-popup fancybox" title="<?php echo Mage::helper("ves_base")->__('Large Image');?>"><span class="icon icon-search-plus"></span></a>
			<?php endif; ?>
			<?php if ($link_url): ?>
				<a href="<?php echo $link_url;?>" class="ves-btnlink img-animation" title="<?php echo $image_alt;?>">
					<img <?php echo $holder_image?'data-src="'.$holder_image.'"':''; ?> src="<?php echo $thumbnailurl;?>" class="img-responsive" alt="<?php echo $image_alt; ?>"/></a>
				<?php else: ?>
					<span class="img-animation"><img <?php echo $holder_image?'data-src="'.$holder_image.'"':''; ?> src="<?php echo $thumbnailurl; ?>" class="img-responsive" alt="<?php echo $image_alt; ?>"/></span>
				<?php endif; ?>
			<?php if($html != ''){ ?>
			<div class="image-description">
				<?php echo $html ?>
			</div>
			<?php } ?>
			</div>
		</div>
	</div>
<?php endif; ?>