<div class="ves_sellers_page">
    <?php echo $this->getBeforeSellersListHeaderHtml()?>
    <?php echo $this->getSellersListHeaderHtml()?>
    <?php echo $this->getAfterSellersListHeaderHtml()?>

    <?php echo $this->getContentHtml()?>

    <?php echo $this->getBeforeSellersListFooterHtml()?>
    <?php echo $this->getSellersListFooterHtml()?>
    <?php echo $this->getAfterSellersListFooterHtml()?>
</div>