<?php if(Mage::getSingleton('core/session')->getNewDataFaq()){ 
			$data = Mage::getSingleton('core/session')->getNewDataFaq();
	}
?>
<div class="kbase-block-title">
<div class="box-head">
<h2 class="title"><?php echo Mage::helper('advancedfaq')->__('Add more Questions please :') ?></h2>
</div>
<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
<div class="box-content">
	<form action="<?php echo $this->getUrlNew() ?>" method="post" id="new-faq-form" enctype="multipart/form-data">
	   <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="category_id" class="required"><em>*</em><?php echo Mage::helper('advancedfaq')->__('Select a topic') ?></label>
                    <div class="input-box">
                       <select name="category_id" id="category_id" class="required-entry">
                       		<option value=""><?php echo Mage::helper('advancedfaq')->__('--Select one--') ?></option>
							<?php foreach($this->getCategory() as $category):?>
							<option value="<?php echo $category->getId()?>" <?php if($category->getId()==$data['category_id']) echo "selected"?>><?php echo $category->getTitle() ?></option>
							<?php endforeach;?>
						</select>
                    </div>
                 </div>
            </li>
            <li>
                <label for="question" class="required"><em>*</em><?php echo Mage::helper('advancedfaq')->__('Question') ?></label>
                <div class="input-box otto_field">
                    <textarea name="question" id="question" title="<?php echo Mage::helper('advancedfaq')->__('Question') ?>" class="required-entry input-text" cols="80" rows="10"><?php if($data['question']) echo $data['question'] ?></textarea>
                </div>
            </li>
			<li class="wide" id="recapcha-field">
				<?php //echo $this->getRecapcharHtml() ?>
				<div style="clear:both" ></div>
            </li>
        </ul>
		
		<div class="buttons-set">
				<button class='button btn-cart' title="Submit ticket" type="submit" ><span><span><?php echo Mage::helper('advancedfaq')->__('Reset') ?></span></span></button>
				<button class='button btn-cart' title="Submit ticket" type="submit" ><span><span><?php echo Mage::helper('advancedfaq')->__('Send') ?></span></span></button>
		</div>
	</form>
</div>
</div>
<?php Mage::getSingleton('core/session')->unsNewDataFaq()?>
<script type='text/javascript'>
var newForm = new VarienForm('new-faq-form', true); 
<?php if(Mage::helper('advancedfaq/recapcha')->getEnableRecapchar()) :?>
							Recaptcha.create("<?php echo Mage::helper('advancedfaq/recapcha')->getPublickeyConfig() ?>", 'recapcha-field', {
							theme: "<?php echo Mage::helper('advancedfaq/recapcha')->getThemeOption() ?>",
							lang : "<?php echo Mage::helper('advancedfaq/recapcha')->getLangugageOption() ?>",
							callback: Recaptcha.focus_response_field});
							$('recapcha-field').show();
<?php endif; ?>
</script>