<?php
/**
 * View Widget Template
 */
?>

<?php $widgetData = $this->getWidgetData() ?>
<?php $account = $this->getAccount() ?>

<div id="affiliatepluswidget_outer_body" style="display:block;width:<?php echo $widgetData['width'] ?>px;height:<?php echo $widgetData['height'] ?>px;">
	<div id="affiliatepluswidget_body" style="width:<?php echo $widgetData['width'] ?>px;background-color:#<?php echo $widgetData['border'] ?>;color:#<?php echo $widgetData['textbody'] ?>;">
                        <div id="affiliatepluswidget_footer">
				<a href="<?php echo $this->getUrl(null,array('_query' => array('acc' => $account->getIdentifyCode()))) ?>" style="color:#<?php echo $widgetData['textlink'] ?>;">
					<?php echo Mage::app()->getStore()->getFrontendName() ?>
				</a>
			</div>
		<div id="affiliatepluswidget_content" style="float: left;background-color:#<?php echo $widgetData['background'] ?>;">
                    <div id="affiliatepluswidget_search_form">
                        <form class = "form-search" onsubmit="return false;">
                            <div class="div-affiliate-search"><input id="affiliatepluswidget_search" name="search" value="<?php echo $widgetData['search'] ?>" style="max-width:<?php echo $widgetData['width']-48 ?>px;" /></div>
                            <div style="width: 10%;float: left;">
                                <button class = "button-go" type="button" id="affiliatepluswidget_submit" style="border:none" onclick="affiliatepluswidgetInstanceSearch();">
                                    <span><?php echo $this->__('Go') ?></span>
				</button>
                            </div>
			</form>
                    </div>
			<?php $requestParam = $this->getRequest()->getParams() ?>
			<?php unset($requestParam['search']) ?>
			<input type="hidden" id="affiliatepluswidget_search_url" value="<?php echo $this->getUrl("affiliatepluswidget/index/products",array("_query" => $requestParam)) ?>" />
			<div class="affiliatepluswidget_product_list_container" style="background-color:#<?php echo $widgetData['background'] ?>;height:<?php echo $widgetData['height']-64 ?>px;">
				<div id="affiliatepluswidget_product_list">
					<?php echo $this->getChildHtml('affiliatepluswidget_products') ?>
				</div>
				<div id="widget-products-ajax-load" style="display:none;padding-top:10px;">
					<center>
						<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>" title="<?php echo $this->__('Loading...') ?>" />
						<span style="color:#E76200"><?php echo $this->__('Loading...') ?></span>
					</center>
				</div>
			</div>
		</div>
	</div>
</div>  
<?php exit(); ?>