<div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script>jQuery.noConflict();</script>
	<div>
	   <h2><?php echo __("Home Page Slider"); ?></h2>
	</div>


	<div>
		 <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/saveBanerimages') ?>" method="POST" enctype="multipart/form-data">
		     <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		     <b>Select images:</b>
		      <input type="file" value="" name="fileToUpload" id="fileToUpload"><br>
		      Image Tab Label:<input type="text" name="imagelabel" id="vl" ><br>

			  Title:<input type="text" name="title"  ><br>
			  Know More url:<input type="text" name="url" ><br>
			 <!--  Serial:<input type="text" name="serials" > -->
			  <br><br><br>
			  <button submit >update</button>
		  </form>
	</div>
</div>

<?php 
$btSLiderModel = Mage::getModel('btslider/btslider')->getCollection();
?>

<div>
<form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/deletesliderimage') ?>" method="POST" enctype="multipart/form-data">
 <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <table border="1" width="100%">
    	<thead>
    		<tr>
    		    <td><?php echo __('Id'); ?></td>
    			<td><?php echo __('Image'); ?></td>
    			<td><?php echo __('Tab Label'); ?></td>
    			<td><?php echo __('Image Title'); ?></td>
    			<td><?php echo __('Url'); ?></td>
    			<td><?php echo __('Action'); ?></td>
    		</tr>
    	</thead>
    	<tbody>
    	<?php 
foreach ($btSLiderModel as $imagedata) { 
  $id = $imagedata['btslider_id'];
  $image = $imagedata['images'];
  $url = $imagedata['url'];
  $imagelabel = $imagedata['imagelabel'];
  $title = $imagedata['title'];
  $imagethumbnail = $imagepath.$image;
?>
<input type="hidden" name="id" value="<?php echo $id; ?>">
    	  <tr>
    	        <td><?php echo $id;?></td>
    	  		<td style="width: 50%"> <img height="100px" width="100%" src="http://localhost/mish/media/slider/<?php echo $image; ?>"></td>
    	  		<td><?php echo $imagelabel;?></td>
    	  		<td><?php echo $title; ?></td>
    	  		<td><?php echo $url; ?></td>
    	  		<td><button type="submit">Delete</button></td>
    	  </tr>
  <?php } ?>
    	</tbody>
    </table>
    </form>
</div>

