<?php
    $rfq = $this->getRfqData();
    $rfq_obj = $this->getCurrentRfq();
    $estimate_interface = $rfq_obj->getReminderInterface();
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Replies for "%s"', $rfq['project_title']) ?></h1>
</div>
<div class="rfq-box">
    <h2 class="legend"><?php echo $this->__('RFQ Infomation')?></h2>
    <ul class="rfq-field-list">
        <li><p class="field"><?php echo $this->__('Company: %s',$rfq['company'])?></p></li>
        <li><p class="field"><?php echo $this->__('Phone: %s',$rfq['phone'])?></p></li>
        <li><p class="field"><?php echo $this->__('Contact name: %s',$rfq['contact_name'])?></p></li>
        <li><p class="field"><?php echo $this->__('Email: %s',$rfq['email'])?></p></li>
        <li><p class="field"><?php echo $this->__('Project title: %s',$rfq['project_title'])?></p></li>
        <li><p class="field"><?php echo $this->__('Overview: %s',$rfq['overview'])?></p></li>
        <li><p class="field"><?php echo $this->__('Created At: %s',$this->formatDate($rfq['created_at']))?></p></li>
        <li><p class="field"><?php echo $this->__('Close Date: %s',$this->formatDate($rfq['close_date']))?></p></li>
        <li>
<!--            <form id="resend_form" action="<?php /*echo $this->getResendUrl() */?>" method="post">
                <input type="hidden" name="company" value="<?php /*echo $rfq['company']*/?>" />
                <input type="hidden" name="phone" value="<?php /*echo $rfq['phone']*/?>" />
                <input type="hidden" name="contact_name" value="<?php /*echo $rfq['contact_name']*/?>" />
                <input type="hidden" name="email" value="<?php /*echo $rfq['email']*/?>" />
                <input type="hidden" name="project_title" value="<?php /*echo $rfq['project_title']*/?>" />
                <input type="hidden" name="overview" value="<?php /*echo $rfq['overview']*/?>" />
                <input type="hidden" name="created_at" value="<?php /*echo strtotime(now())*/?>" />
                <input type="hidden" name="close_date" value="<?php /*echo $this->getCloseDateNumber()*/?>" />
                <input type="hidden" name="attachment" value="<?php echo $rfq['attachment']?>" />
-->
                <button class="button" title="<?php echo $this->__('Resend RFQ')?>" onclick="resendRfq()" type="button"><span><span><?php echo $this->__('Resend RFQ')?></span></span></button>
            <!--</form>-->
        </li>
   </ul>
</div>

<div class="page-title title-buttons">
    <h1><?php echo $this->__('Vendor Replies') ?></h1>
</div>
<?php if($rfq_obj->isReplied()):?>
<div class="rfq-replies">
    <?php foreach($this->getRfqReplies() as $_reply):?>
        <?php echo $this->getReplyHtml($_reply)?>
    <?php endforeach;?>
</div>

<script type="text/javascript">
    var resendForm = new VarienForm('resend_form', true);
    $$('.reply-item').each(function(item) {
        var h2 = item.down('h2');
        var background = h2.down('i');
        var content = item.down('.reply-content');

        Event.observe(h2,'click',function(){
            if(background.hasClassName('arrow')) {
                background.removeClassName('arrow');
                background.addClassName('arrow-up');
            } else {
                background.removeClassName('arrow-up');
                background.addClassName('arrow');
            }
            content.toggle();
        });
     });
	
</script>

<?php else:?>
    <p><?php echo $this->__('No reply to your RFQ.')?></p>
<?php endif;?>

<!--if close rfq-->
<?php if(!$this->isClose()):?>
    <div class="close-rfq">
        <a href="javascript:void(0);" onclick="closeRfq()"><?php echo $this->__('Close this RFQ')?></a>
    </div>
<?php endif;?>

<script type="text/javascript">
    function resendRfq() {
        var result = confirm("<?php echo $this->__('Are you sure?')?>");
        if(result == true) {
            window.location.href = "<?php echo $this->getResendUrl()?>";
        }
    }

    function closeRfq() {
        var result = confirm("<?php echo $this->__('Are you sure?')?>");
        if(result == true) {
            window.location.href = "<?php echo $this->getCloseRfqUrl()?>";
        }
    }
</script>