<?php 
	$storeId = '';
	if($this->getData('storeId')){
		$storeId = $this->getData('storeId');
	}
?>
<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('items')->__('Attribute Mapping') ?></h3></td>
      <td class="a-right"><?php  echo $this->getButtonsHtml() ?></td>
    </tr>
  </table>
  </div>
 <div>
<table width="100%" border="0" cellspacing="5" cellpadding="0" class="switcher">
  <tr>
    <td width="20%"><label for="store_switcher">Choose MercadoLibre Root Category:</label></td>
    <td ><select onchange="return meliRootCategoryStore(this);" id="meli_root_category_switcher" name="meli_root_category_switcher">
      <?php
		$data['root_id'] = '';
		$data = $this->getData();
		foreach($data['meliCategoriesRoot'] as $key => $value ){
			echo '<option value="'.$key.'"';
			if($key == $data['root_id']){  $selected = 'selected'; } else { $selected = '';};
			echo $selected .'>&nbsp;&nbsp;'.$value.'&nbsp;&nbsp;</option>';
		}
	?>
    </select>
	<?php 
		if(count($data['meliCategoriesRoot']) == 1 || count($data['meliCategoriesRoot']) == 0){
			echo "&nbsp;&nbsp;<a href='".$this->getUrl('adminhtml/system_config/edit/section/mlitems')."'>Click here</a>&nbsp;&nbsp;To Choose MercadoLibre Root Category For Selected Store.";
		}
	?>
	</td>
  </tr>
  <tr>
    <td><label for="store_switcher">Choose MercadoLibre Category:</label></td>
    <td>
		<?php 
			$attribute_id ='';
			if($this->getData('attribute_id')){
				$attribute_id = $this->getData('attribute_id');
			}
		?>
	<select onchange="return meliCategoryStore('<?php echo $data['root_id']; ?>',this.value,'<?php echo $attribute_id; ?>');" id="meli_category_switcher" name="meli_category_switcher">
	<?php
		$data['root_id'] = '';
		$data = $this->getData();
		foreach($data['meliCategories'] as $key => $value ){
			echo '<option value="'.$key.'"';
			if($key == $data['category_id']){  $selected = 'selected'; } else { $selected = '';};
			echo $selected .'>&nbsp;&nbsp;'.$value.'&nbsp;&nbsp;</option>';
		}
	?>
    </select>
	<?php 
		if((count($data['meliCategories']) == 1 || count($data['meliCategories']) == 0) && (isset($data['root_id']) && trim($data['root_id'])!='') ){
			echo "&nbsp;&nbsp;<a href='".$this->getUrl('items/adminhtml_categorymapping')."'>Click here</a>&nbsp;&nbsp;To Category Mapping Before Attribute Mapping.";
		}
	?>
	</td>
  </tr>
  <tr>
    <td> <label for="store_switcher">Choose Magento Attribute :</label></td>
    <td> <select onchange="return onChangeMageAttributes('<?php echo $data['root_id']; ?>','<?php echo $data['category_id'];?>',this.value);" id="mage_attribute_switcher" name="mage_attribute_switcher">
      <?php
		$data['attribute'] = '';
		$data = $this->getData();
		foreach($data['mageAttributeCollection'] as $key => $value ){
			echo '<option value="'.$key.'"';
			if($key == $data['attribute_id']){  $selected = 'selected'; } else { $selected = '';};
			echo $selected .'>&nbsp;&nbsp;'.$value.'&nbsp;&nbsp;</option>';
		}
	?>
    </select></td>
  </tr>
</table>
</div>
<form  id="edit_form" action="<?php echo $this->getUrl('*/*/post');?>" method="post"  >
<div style="text-align:right;">
	<input name="button" type="submit" value="Save Attribute Mapping" onClick="this.form.submit()"  class="form-button scalable save" />
</div>
  <div> <?php echo $this->getGridHtml() ?> </div>
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
  	<input type='hidden' name='root_id_hidden' value='<?php echo $this->getRequest()->getParam('root_id'); ?>'>
	<input type='hidden' name='category_id_hidden' value='<?php echo $this->getRequest()->getParam('category_id');?>'>
	<input type='hidden' name='attribute_id_hidden' value='<?php echo$this->getRequest()->getParam('attribute_id'); ?>'>
</form>
<script type="text/javascript">
    function meliRootCategoryStore(obj) {
		var storeId = '<?php echo $storeId; ?>';
		var storePram = '';
		if(storeId){
			var storePram = storeId ? 'store/' + storeId + '/' : '';
		}
        var categoryRootParam = obj.value ? 'root_id/' + obj.value + '/' : '';
        setLocation('<?php echo $this->getUrl('*/*/*');?>' + storePram + categoryRootParam);
        }
</script>
<script type="text/javascript">
    function meliCategoryStore(root_id,category_id,attribute_id) {
		var storeId = '<?php echo $storeId; ?>';
		var storePram = '';
		if(storeId){
			var storePram = storeId ? 'store/' + storeId + '/' : '';
		}
		
		if(root_id=='' && category_id == ''){
			alert('Please Choose MercadoLibre Root Category');
			return false;
		}
       	 var categoryParam = 'root_id/'+root_id+'/category_id/' + category_id + '/';
		if(attribute_id!=''){
			var categoryParam = 'root_id/'+root_id+'/category_id/'+ category_id +'/attribute_id/'+ attribute_id + '/';
		}
        if (categoryParam) {
            categoryParam = categoryParam;
        }
           setLocation('<?php echo $this->getUrl('*/*/*');?>' + storePram + categoryParam);
      }
</script>
<script type="text/javascript">
    function onChangeMageAttributes(root_id,cat_id,attribute_id) {
		var storeId = '<?php echo $storeId; ?>';
		var storePram = '';
		if(storeId){
			var storePram = storeId ? 'store/' + storeId + '/' : '';
		}
		
		if(root_id=='' && cat_id==''){
			alert('Please Choose MercadoLibre Root Category');
			return false;
		}
		if(cat_id==''){
			alert('Please Choose MercadoLibre Category');
			return false;
		}
        var attributeParam = 'root_id/'+root_id+'/category_id/'+ cat_id +'/attribute_id/'+ attribute_id + '/';
         setLocation('<?php echo $this->getUrl('*/*/*');?>'+ storePram + attributeParam);
        }
</script>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '');
</script>
<script type="text/javascript">
    function onChangeMlColorAttribute(MageId){
		var Color_Primario = 'meli_value_id_1_'+MageId;
		var selObj = document.getElementById(Color_Primario);	
		var selIndex = selObj.selectedIndex;
		var textValue1 = selObj.options[selIndex].text;
		
		var Color_Secundario = 'meli_value_id_2_'+MageId;
		var select = document.getElementById(Color_Secundario);
		for (var i = 0; i < select.options.length; i++) {
			if (select.options[i].text == textValue1) {
				select.options[i].selected = "true";
				break;
			}
		}
	}
</script>


