<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__('Tier Prices') ?></h4>
    </div>
    <fieldset>
        <legend><?php echo Mage::helper('catalog')->__('Tier Prices') ?></legend>
        <table cellspacing="0" class="form-list" id="table_tierprices">
            <?php $_htmlId      = 'tier_price'; ?>
            <?php $_htmlClass   = 'input-text'; ?>
            <?php $_htmlName    = 'tier_price'; ?>
            <?php $_readonly    = 0; ?>
            <?php $_showWebsite = true; ?>
            <?php $_editWebsite = true; ?>
            <?php $_priceValueValidation = 'validate-greater-than-zero'; ?>
            
            <tr>
                <td colspan="10" class="grid tier">
                <table cellspacing="0" class="data border" id="tiers_table">
                    <?php if ($_showWebsite): ?>
                    <col width="135" />
                    <?php endif; ?>
                    <col width="120" />
                    <col width="95" />
                    <col />
                    <col width="210" />
                    <col width="1" />
                    <thead>
                        <tr class="headings">
                            <th <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('sales')->__('Website') ?></th>
                            <th><?php echo Mage::helper('catalog')->__('Customer Group') ?></th>
                            <th><?php echo Mage::helper('catalog')->__('Qty') ?></th>
                            <th><?php echo Mage::helper('catalog')->__('Price / Percent') ?></th>
                            <th><?php echo Mage::helper('catalog')->__('Type') ?></th>
                            <th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th>
                        </tr>
                    </thead>
                    <tbody id="<?php echo $_htmlId ?>_container"></tbody>
                    <tfoot>
                        <tr>
                            <td <?php if (!$_showWebsite): ?>style="display:none"<?php endif; ?>></td>
                            <td colspan="5" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
                        </tr>
                    </tfoot>
                </table>
            
            <script type="text/javascript">
            //<![CDATA[
            var tierPriceRowTemplate = '<tr>'
                + '<td<?php if (!$_showWebsite): ?> style="display:none"<?php endif; ?>>'
                + '<select class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[{{index}}][website_id]" id="tier_price_row_{{index}}_website">'
                <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                + '<option value="<?php echo $_websiteId ?>"><?php echo $this->jsQuoteEscape($this->htmlEscape($_info['name'])) ?><?php if (!empty($_info['currency'])): ?> [<?php echo $this->htmlEscape($_info['currency']) ?>]<?php endif; ?></option>'
                <?php endforeach ?>
                + '</select></td>'
                + '<td><select class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[{{index}}][cust_group]" id="tier_price_row_{{index}}_cust_group">'
                <?php foreach ($this->getCustomerGroups() as $_groupId=>$_groupName): ?>
                + '<option value="<?php echo $_groupId ?>"><?php echo $this->jsQuoteEscape($this->htmlEscape($_groupName)) ?></option>'
                <?php endforeach ?>
                + '</select></td>'
                + '<td class="nobr"><input class="<?php echo $_htmlClass ?> qty required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[{{index}}][price_qty]" value="{{qty}}" id="tier_price_row_{{index}}_qty" />'
                + ' <small class="nobr"><?php echo Mage::helper('catalog')->__("and above")?></small></td>'
                + '<td><input class="<?php echo $_htmlClass ?> required-entry <?php echo $_priceValueValidation ?>" type="text" name="<?php echo $_htmlName ?>[{{index}}][price]" value="{{price}}" id="tier_price_row_{{index}}_price" /></td>'
                + '<td><select class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[{{index}}][value_type]" id="tier_price_row_{{index}}_value_type">'
                + '<option value="fixed"><?php echo $this->__('Fixed Price') ?></option>'
                + '<option value="discount_percent"><?php echo $this->__('Discount Percent') ?></option>'
                + '</select></td>'
                + '<td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[{{index}}][delete]" class="delete" value="" id="tier_price_row_{{index}}_delete" />'
                + '<button title="<?php echo Mage::helper('catalog')->__("Delete Tier") ?>" type="button" class="scalable delete icon-btn delete-product-option" id="tier_price_row_{{index}}_delete_button" onclick="return tierPriceControl.deleteItem(event);">'
                + '<span><span><span><?php echo Mage::helper('catalog')->__("Delete") ?></span></span></span></button></td>'
                + '</tr>';
            
            var tierPriceControl = {
                template: new Template(tierPriceRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
                itemsCount: 0,
                addItem : function () {
                    <?php if ($_readonly): ?>
                    if (arguments.length < 5) {
                        return;
                    }
                    <?php endif; ?>
                    var data = {
                        website_id: '<?php echo $this->getDefaultWebsite() ?>',
                        group: '<?php echo $this->getDefaultCustomerGroup() ?>',
                        qty: '',
                        price: '',
                        value_type: 'fixed',
                        readOnly: false,
                        index: this.itemsCount++
                    };
            
                    if(arguments.length >= 5) {
                        data.website_id = arguments[0];
                        data.group      = arguments[1];
                        data.qty        = arguments[2];
                        data.price      = arguments[3];
                        data.value_type = arguments[4];
                    }
                    if (arguments.length == 6) {
                        data.readOnly = arguments[5];
                    }
            
                    Element.insert($('<?php echo $_htmlId ?>_container'), {
                        bottom : this.template.evaluate(data)
                    });
            
                    $('tier_price_row_' + data.index + '_cust_group').value = data.group;
                    $('tier_price_row_' + data.index + '_website').value    = data.website_id;
                    $('tier_price_row_' + data.index + '_value_type').value  = data.value_type;
            
                    if (data.readOnly == '1') {
                        ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                            $('tier_price_row_'+data.index+'_'+idx).disabled = true;
                        });
                        $('tier_price_row_'+data.index+'_delete_button').hide();
                    }
            
                    <?php if ($_readonly): ?>
                    $('<?php echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                    $('<?php echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                    <?php else: ?>
                    $('<?php echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                    <?php endif; ?>
                },
                disableElement: function(el) {
                    el.disabled = true;
                    el.addClassName('disabled');
                },
                deleteItem: function(event) {
                    var tr = Event.findElement(event, 'tr');
                    if (tr) {
                        Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                        Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                        Element.hide(tr);
                        Element.addClassName(tr, 'no-display template');
                    }
                    return false;
                }
            };
            <?php if ($_readonly): ?>
            $('<?php echo $_htmlId ?>_container').up('table').select('button')
                .each(tierPriceControl.disableElement);
            <?php endif; ?>
            //]]>
            </script>
            </td></tr>
        </table>
    </fieldset>
</div>
