<?php
$collection = $this->getCollection();
$_helper = Mage::helper('vendorssellerlist');
?>

<?php if(!$collection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no vendor in website.') ?></p>
<?php else: ?>
    <div class="ves_sellers_grid">
        <?php // Grid Mode ?>

        <?php $_collectionSize = $collection->count() ?>
        <?php $_columnCount = $this->getColumnCount();?>
        <?php $i=0; foreach ($collection as $_seller): ?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul class="ves_sellers_child_list">
        <?php endif ?>
                <li class="ves_sellers_child_item_g item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <a href="<?php echo $this->getSellerUrl($_seller)?>" onclick="setLocation('<?php echo $this->getSellerUrl($_seller)?>')" class="seller-image">
                        <img src="<?php echo $this->getSellerImageUrl($_seller) ?>" width="161" height="112" title="<?php echo $this->stripTags($_seller->getTitle())?>" alt="<?php echo $this->stripTags($_seller->getTitle())?>" />
                        <div class="mp_landing_hover">
                            <span><?php echo $_seller->getTitle() ?></span>
                        </div>
                    </a>
                </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.ves_sellers_child_list'), ['odd','even','first','last'])</script>

        <?php if($this->isViewAll()):?>
        <div class="toolbar-bottom">
            <?php echo $this->getPagerHtml() ?>
        </div>
        <?php endif;?>
    </div>
<?php endif; ?>
