<?php
/**
 * 
 * Overrides template/page/template/links.phtml - puts both sets of links into one menu ("account.links" and "top.links")
 */
?>

<?php
  // Check if Wishlist link enabled
  $configData = Mage::getStoreConfig('hybrid_mobile');
  $wishlist = $configData['header_settings']['wishlist'];
  $wishlisttitle = $this->__('Wishlist');
?>

<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
    <?php foreach($_links as $_link): ?>
      <?php $title = explode(" ", $_link->getTitle()); $title = $title[0]; ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract && $title != $wishlisttitle):?>
            <?php echo $_link->toHtml(); ?>
        <?php elseif($_link instanceof Mage_Core_Block_Abstract && $title == $wishlisttitle && $wishlist == 1): ?>
        	<?php echo $_link->toHtml(); ?>
        <?php elseif($title != $wishlisttitle): ?>
            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif;?>
    <?php endforeach; ?>
<?php endif; ?>