<?php 
$_product = $this->getProduct();
$quoteHelper = Mage::helper('vendorsquote');
$customerSession = Mage::getSingleton('customer/session');
$isAllowedToAddToQuote    = $quoteHelper->isAllowedToQuote($_product);
$isAllowedToAddToCart     = $quoteHelper->isAllowedToOrder($_product);
?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable() || $isAllowedToAddToQuote): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped() && ($isAllowedToAddToQuote || $isAllowedToAddToCart)): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <?php if($isAllowedToAddToCart):?>
            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php endif;?>
        <?php if($isAllowedToAddToQuote):?>
            <a href="javascript:void(0);"<?php if($quoteHelper->requireCustomerLogin() && !$customerSession->isLoggedIn()):?> onmousemove="$(this).update('<?php echo $quoteHelper->__('Login Required')?>')" onmouseout="$(this).update('<?php echo $quoteHelper->__('Add To Quote')?>')"<?php endif;?> onclick="<?php if($quoteHelper->requireCustomerLogin() && !$customerSession->isLoggedIn()):?>setLocation('<?php echo $this->getUrl('customer/account/login')?>')<?php else:?>addToQuote('<?php echo Mage::helper('vendorsquote')->getAddToQuoteUrl($_product)?>')<?php endif;?>" style="margin-left:10px;" type="button" title="<?php echo Mage::helper('vendorsquote')->__('Add To Quote') ?>" class="button btn-quote"><span><span><?php echo Mage::helper('vendorsquote')->__('Add To Quote') ?></span></span></a>
        <?php endif;?>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>