<div class="ves_sellers_child">
    <div class="label"><?php echo $this->__('Latest Products')?></div>
    <?php if($this->getLatestProducts()->count()):?>
    <ul class="ves_sellers_child_list">
        <?php foreach($this->getLatestProducts() as $_product):?>
            <li class="ves_sellers_child_item">
                <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(94); ?>" width="94" height="94" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="mp_landing_hover">
                    <span><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'); ?></span>
                </div>
            </li>
        <?php endforeach;?>
    </ul>
    <?php endif;?>
</div>