<?php
/**
 * Create account form template
 *
 * @var $this VES_Vendors_Block_Form_Register
 */
?>
<?php
$_countries = Mage::getResourceModel('directory/country_collection')
        ->loadData()
        ->toOptionArray(false);
$countryHtml = '';
if (count($_countries) > 0):
    $countryHtml .= '<select name="additional[country_id]" id="more_country" class="validate-select" title="Country">';
    $countryHtml .= '<option value=""></option>';
    foreach ($_countries as $_country):
        $countryHtml .= '<option value="' . $_country['value'] . '">' . $_country['label'] . '</option>';
    endforeach;
    $countryHtml .= '</select>';
endif;
?>
<script src='https://www.google.com/recaptcha/api.js'></script>
<div id="registerbox">
    <h1><?php echo $this->__('Create An Account') ?></h1>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <form class="form-horizontal" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?php echo $this->__('Vendor Information') ?></h5>
            </div>
            <div class="widget-content">
                <div class="control-group">
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('First Name') ?><?php if ($this->getIsRequired('firstname')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" id="firstname" name="firstname" value="<?php echo $this->escapeHtml($this->getFormData()->getFirstName()) ?>" title="<?php echo $this->__('First Name') ?>" placeholder="<?php echo $this->__('First Name') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('firstname')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Last Name') ?><?php if ($this->getIsRequired('lastname')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" id="lastname" name="lastname" value="<?php echo $this->escapeHtml($this->getFormData()->getLastName()) ?>" title="<?php echo $this->__('Last Name') ?>" placeholder="<?php echo $this->__('Last Name') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('lastname')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('Display Name') ?><?php if ($this->getIsRequired('title')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" id="title" name="title" value="<?php echo $this->escapeHtml($this->getFormData()->getTitle()) ?>" title="<?php echo $this->__('Display name') ?>" placeholder="<?php echo $this->__('Display name') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('title')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Logo') ?><?php if ($this->getIsRequired('logo')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="file" id="logo" name="logo" value="<?php echo $this->escapeHtml($this->getFormData()->getTitle()) ?>" title="<?php echo $this->__('Logo') ?>" placeholder="<?php echo $this->__('Logo') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('logo')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                </div>


                 <div class="control-group" >
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('Date of Birth') ?><?php if ($this->getIsRequired('Date of Birth')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls v-reg">
                        <input type="date" name="birthday" />
                            
                        </div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Sex') ?><?php if ($this->getIsRequired('Sex')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls v-reg"> <input type="radio" name="sex" <?php if (isset($sex) && $sex=="female") echo "checked";?> value="female">Female
                          <input type="radio" name="sex" <?php if (isset($sex) && $sex=="male") echo "checked";?> value="male">Male
 
                    </div>

                </div>
                </div>
                <div class="control-group">
                   <div class="col col-left">
                      <label class="control-label"><?php echo $this->__('Passport No.:') ?><?php if ($this->getIsRequired('Passport')): ?> <em>*</em><?php endif; ?></label>
                      <div class="controls"><input type="text" id="Passport" name="passport" class="input-text required-entry validate-length maximum-length-12 minimum-length-5 validate-digits"  value="<?php echo $this->escapeHtml($this->getFormData()->getPassport()) ?>" title="<?php echo $this->__('Passport') ?>" placeholder="<?php echo $this->__('Passport number') ?>" maxlength="255"   /></div>
                      </div>

                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Facebook of the brand') ?><?php if ($this->getIsRequired('facebook_brand')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" id="facebook_brand" name="facebook_brand" value="<?php echo $this->escapeHtml($this->getFormData()->getFacebookBrand()) ?>" title="<?php echo $this->__('Facebook of the brand') ?>" placeholder="<?php echo $this->__('Facebook of the brand') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('facebook_brand')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                </div>

                <div class="control-group">
                    <div class="col col-left">
                        <input type="radio" class="radio <?php if ($this->getIsRequired('seller_with_invoice')): ?> validate-one-required-by-name<?php endif; ?>" id="seller_with_invoice" name="seller_with_invoice" style="width:auto;" placeholder="<?php echo $this->__('Seller With an Invoice') ?>" onclick="addInvoiceForm(1)" value="1" />
                        <label class="control-label"><?php echo $this->__('Seller With Invoice') ?></label>
                    </div>
                </div> 

                <div class="control-group">
                    <div class="col col-left">
                        <input type="radio" class="radio <?php if ($this->getIsRequired('seller_with_invoice')): ?> validate-one-required-by-name<?php endif; ?>" id="personal_seller" name="seller_with_invoice" style="width:auto;" placeholder="<?php echo $this->__('Personal Seller') ?>" onclick="addInvoiceForm(2)" value="0" />
                        <label class="control-label"><?php echo $this->__('Personal Seller') ?></label>
                    </div>
                </div>
                <div class="control-group" id="seller_with_invoice_form"></div>
                <div class="control-group" id="personal_seller_form"></div>

                <div class="control-group">                    
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('Telephone') ?><?php if ($this->getIsRequired('telephone')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" placeholder="<?php echo $this->__('Telephone') ?>" class="input-text<?php if ($this->getIsRequired('telephone')): ?> required-entry<?php endif; ?>" /></div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Facebook/Instagram') ?><?php if ($this->getIsRequired('Facebook/Instagram')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" id="Facebook/Instagram" name="Facebook" value="<?php echo $this->escapeHtml($this->getFormData()->getFacebook()) ?>" title="<?php echo $this->__('Facebook/Instagram') ?>" placeholder="<?php echo $this->__('Enter Facebook/Instagram id') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('Facebook/Instagram')): ?> required-entry<?php endif; ?>"  /></div>
                    </div>
                </div>

                <div class="control-group">
               
                    <label class="control-label"><?php echo $this->__('Room Address') ?><?php if ($this->getIsRequired('Room Address')): ?> <em>*</em><?php endif; ?></label>
                    <div class="controls"><input type="text" name="roomaddress" value="<?php echo $this->escapeHtml($this->getFormData()->getAddress()); ?>" title="<?php echo $this->__('roomaddress') ?>" placeholder="<?php echo $this->__('Room address') ?>" id="roomaddress" />

                    </div>
                
                    </div>
                    <input type="checkbox" name="billingtoo" onclick="FillBilling(this.form)">
                    <em>Check if Address is same</em>
                   <div class="control-group">
                    <label class="control-label"><?php echo $this->__('Address') ?><?php if ($this->getIsRequired('address')): ?> <em>*</em><?php endif; ?></label>
                    <div class="controls">
                    <input type="text" name="address" value="<?php echo $this->escapeHtml($this->getFormData()->getAddress()); ?>" title="<?php echo $this->__('Address') ?>" placeholder="<?php echo $this->__('Address') ?>" id="address"  /></div>
                    </div>
                
                <div class="control-group">
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('City') ?><?php if ($this->getIsRequired('city')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" placeholder="<?php echo $this->__('City') ?>" class="input-text<?php if ($this->getIsRequired('city')): ?> required-entry<?php endif; ?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" /></div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('State/Province') ?><?php if ($this->getIsRequired('region_id')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select <?php if ($this->getIsRequired('region_id')): ?> required-entry<?php endif; ?>" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text<?php if ($this->getIsRequired('region')): ?> required-entry<?php endif; ?>" style="display:none;" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('Zip/Postal Code') ?><?php if ($this->getIsRequired('postcode')): ?> <em>*</em><?php endif; ?></label>
                        <div class="controls"><input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" id="postcode" class="input-text validate-zip-international<?php if ($this->getIsRequired('postcode')): ?> required-entry<?php endif; ?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" /></div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Country') ?> :</label>
                        <div class="controls"><?php echo $this->getCountryHtmlSelect() ?></div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="col col-left">
                        <input type="checkbox" class="checkbox" id="more_than_one" name="more_than_one" style="width:auto;" placeholder="<?php echo $this->__('Tick if you have more than 1 Warehouse') ?>" onclick="addForm()" value="1" />
                        <label class="control-label"><?php echo $this->__('Tick if you have more than 1 Warehouse') ?></label>
                    </div>
                </div>
                <div class="control-group" id="more_warehouse"></div>
                <div class="control-group">
                    <label class="control-label"><?php echo $this->__('Account Activation Email') ?> <em>*</em></label>
                    <div class="controls"><input type="text" name="activation_email" id="activation_email" value="<?php echo $this->escapeHtml($this->getFormData()->getActivationEmail()) ?>" title="<?php echo $this->__('Account Activation Email') ?>" placeholder="<?php echo $this->__('Account Activation Email') ?>" class="input-text validate-email required-entry" /></div>
                </div>
                <div class="control-group">
                    <label class="control-label"><?php echo $this->__('Attach Rut of the company on both sides and Rut of the Legal representative (must attach in JPG, GIF files) ') ?><?php if ($this->getIsRequired('attach_rut_file')): ?> <em>*</em><?php endif; ?></label>
                    <div class="controls"><input type="file" id="attach_rut_file" name="attach_rut_file" value="<?php echo $this->escapeHtml($this->getFormData()->getAttachRutFile()) ?>" title="<?php echo $this->__('Attach Rut of the company on both sides and Rut of the Legal representative (must attach in JPG, GIF files) ') ?>" placeholder="<?php echo $this->__('Attach Rut of the company on both sides and Rut of the Legal representative (must attach in JPG, GIF files) ') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('attach_rut_file')): ?> required-entry<?php endif; ?>"  /></div>
                </div>

                <div class="control-group">
                    <label class="control-label"><?php echo $this->__('Google re-Captcha') ?></label>
                    <div class="controls">
                        <div class="g-recaptcha" data-sitekey="6LdN9hIUAAAAAHs_XoxLvWzkoZXFdb_OVvcvbw0_"></div>
                    </div>                        
                </div>


                <div class="clear"></div>
            </div>
        </div>
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-align-justify"></i>									
                </span>
                <h5><?php echo $this->__('Login Information') ?></h5>
            </div>
            <div class="widget-content nopadding">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->__('Email') ?> <em>*</em></label>
                    <div class="controls"><input type="text" name="email" readonly="true" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email') ?>" placeholder="<?php echo $this->__('Email') ?>" class="input-text validate-email required-entry" /></div>
                </div>
                <div class="control-group">
                    <label class="control-label"><?php echo $this->__('SELLER NAME') ?> <em>*</em></label>
                    <div class="controls"><input type="text" readonly="true" name="vendor_id" id="vendor_id" value="<?php echo $this->escapeHtml($this->getFormData()->getVendorId()) ?>" title="<?php echo $this->__('SELLER NAME') ?>" placeholder="<?php echo $this->__('SELLER NAME') ?>" class="input-text required-entry" /></div>
                </div>

                <div class="control-group">
                    <div class="col col-left">
                        <label class="control-label"><?php echo $this->__('Password') ?> <em>*</em></label>
                        <div class="controls">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="col col-right">
                        <label class="control-label"><?php echo $this->__('Confirm Password') ?> <em>*</em></label>
                        <div class="controls">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" placeholder="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </div>
                <div class="clear"></div>			
            </div>
        </div>
        <?php $additionalAttributes = $this->getAdditionalAttributes(); ?>
        <?php if (sizeof($additionalAttributes)): ?>
            <!-- <div class="widget-box">
                   <div class="widget-title">
                           <span class="icon">
                                   <i class="icon-align-justify"></i>									
                           </span>
                           <h5><?php echo $this->__('Additional Information') ?></h5>
                   </div>
                   <div class="widget-content nopadding">
            <?php foreach ($additionalAttributes as $attribute): ?>
                <?php $isRequired = $attribute->getIsRequired(); ?>
                                                       <div class="control-group">
                                                               <div class="controls">
                <?php $field = $this->getAttributeInputHtml($attribute); ?>
                <?php echo $field->getHtml(); ?>
                                                               </div>
                                                       </div>
            <?php endforeach; ?>
                           <div class="clear"></div>			
                   </div>
           </div>-->
            <a href="<?php echo $this->getLoginUrl() ?>" class="btn btn-inverse"><?php echo $this->__('Back') ?></a>
            <button class="btn btn-success" type="submit"><?php echo $this->__('Save') ?></button>
        <?php endif; ?>
    </form>

    <script type="text/javascript">
        //<![CDATA[
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

        var dataForm = new VarienForm('form-validate', true);

        function addForm() {
            var morehtml = '<div class="control-group">';
            morehtml += '<label class="control-label"><?php echo $this->__('Address') ?><?php if ($this->getIsRequired('address')): ?> <em>*</em><?php endif; ?></label>';
            morehtml += '<div class="controls">';
            morehtml += '<input type="text" name="additional[address]" value="<?php echo $this->escapeHtml($this->getFormData()->getAddress()); ?>" title="<?php echo $this->__('Address') ?>" placeholder="<?php echo $this->__('Address') ?>" id="address" class="input-text<?php if ($this->getIsRequired('address')): ?> required-entry<?php endif; ?>" /></div>';
            morehtml += '</div>';
            morehtml += '<div class="control-group">';
            morehtml += '<div class="col col-left">';
            morehtml += '<label class="control-label"><?php echo $this->__('City') ?><?php if ($this->getIsRequired('city')): ?> <em>*</em><?php endif; ?></label>';
            morehtml += '<div class="controls">';
            morehtml += '<input type="text" name="additional[city]" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" placeholder="<?php echo $this->__('City') ?>" class="input-text<?php if ($this->getIsRequired('city')): ?> required-entry<?php endif; ?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" /></div></div>';
            morehtml += '<div class="col col-right">';
            morehtml += '<label class="control-label"><?php echo $this->__('State/Province') ?><?php if ($this->getIsRequired('region_id')): ?> <em>*</em><?php endif; ?></label>';
            morehtml += '<div class="controls">';
            morehtml += '<select id="more_region_id" name="additional[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php if ($this->getIsRequired('region_id')): ?> required-entry<?php endif; ?>" style="display:none;">';
            morehtml += '<option value=""><?php echo $this->__('Please select region, state or province') ?></option>';
            morehtml += '</select>';
            // $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
            morehtml += '<input type="text" id="more_region" name="additional[region]" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text<?php if ($this->getIsRequired('region')): ?> required-entry<?php endif; ?>" style="display:none;" />';
            morehtml += '</div></div></div>';
            morehtml += '<div class="control-group">';
            morehtml += '<div class="col col-left">';
            morehtml += '<label class="control-label"><?php echo $this->__('Zip/Postal Code') ?><?php if ($this->getIsRequired('postcode')): ?> <em>*</em><?php endif; ?></label>';
            morehtml += '<div class="controls"><input type="text" name="additional[postcode]" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" id="postcode" class="input-text validate-zip-international<?php if ($this->getIsRequired('postcode')): ?> required-entry<?php endif; ?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" /></div>';
            morehtml += '</div><div class="col col-right">';
            morehtml += '<label class="control-label"><?php echo $this->__('Country') ?> :</label>';
            //morehtml +='<div class="controls"><?php echo $this->getCountryHtmlSelect() ?></div></div></div>';
            morehtml += '<div class="controls"><?php echo $countryHtml; ?></div></div></div>';

            //<![CDATA[
            //$('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
            //]]>


            if (jQuery('#more_than_one').is(':checked')) {
                //console.log(morehtml);
                jQuery('#more_warehouse').html(morehtml);
                new RegionUpdater('more_country', 'more_region', 'more_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
            } else {
                jQuery('#more_warehouse').html('');
            }
        }


        function addInvoiceForm(type) {
            var sellerhtml = '<div class="control-group">';
            sellerhtml += '<div class="control-group">' +
                    '<div class="col col-left">' +
                    '<label class="control-label"><?php echo $this->__('Name of the Legal Company') ?><?php if ($this->getIsRequired('name_legal_company')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" id="name_legal_company" name="name_legal_company" value="<?php echo $this->escapeHtml($this->getFormData()->getNameLegalCompany()) ?>" title="<?php echo $this->__('Name of the legal company') ?>" placeholder="<?php echo $this->__('Name of the legal company') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('name_legal_company')): ?> required-entry<?php endif; ?>"  /></div>' +
                    '</div>' +
                    '<div class="col col-right">' +
                    '<label class="control-label"><?php echo $this->__('RUT of the Legal Company') ?><?php if ($this->getIsRequired('rut_legal_company')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" id="rut_legal_company" name="rut_legal_company" value="<?php echo $this->escapeHtml($this->getFormData()->getRutLegalCompany()) ?>" title="<?php echo $this->__('RUT of the company') ?>" placeholder="<?php echo $this->__('RUT of the company') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('rut_legal_company')): ?> required-entry<?php endif; ?>"  /></div>' +
                    '</div>' +
                    '</div>' +
                    '<div class="control-group">' +
                    '<div class="col col-left">' +
                    '<label class="control-label"><?php echo $this->__('Name of Legal Representative') ?><?php if ($this->getIsRequired('name_legal_representative')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" id="name_legal_representative" name="name_legal_representative" value="<?php echo $this->escapeHtml($this->getFormData()->getFirstName()) ?>" title="<?php echo $this->__('Name of Legal Representative') ?>" placeholder="<?php echo $this->__('Name of Legal Representative') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('name_legal_representative')): ?> required-entry<?php endif; ?>"  /></div>' +
                    '</div>' +
                    '<div class="col col-right">' +
                    '<label class="control-label"><?php echo $this->__('Rut of the Legal Representative') ?><?php if ($this->getIsRequired('rut_legal_representative')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" id="rut_legal_representative" name="rut_legal_representative" value="<?php echo $this->escapeHtml($this->getFormData()->getFirstName()) ?>" title="<?php echo $this->__('Rut of the Legal Representative') ?>" placeholder="<?php echo $this->__('Rut of the Legal Representative') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('rut_legal_representative')): ?> required-entry<?php endif; ?>"  /></div>' +
                    '</div>' +
                    '</div>' +
                    '<div class="control-group">' +
                    '<div class="col col-left">' +
                    '<label class="control-label"><?php echo $this->__('Company') ?><?php if ($this->getIsRequired('company')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" placeholder="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?><?php if ($this->getIsRequired('company')): ?> required-entry<?php endif; ?>" /></div>' +
                    '</div>' +
                    '</div>' +
                    '</div>';
            var seller2 = '<div class="control-group">';
            seller2 += '<div class="control-group">' +
                    '<div class="col col-left">' +
                    '<label class="control-label"><?php echo $this->__('Rut of Seller or Person') ?><?php if ($this->getIsRequired('rut_of_seller')): ?> <em>*</em><?php endif; ?></label>' +
                    '<div class="controls"><input type="text" id="rut_of_seller" name="rut_of_seller" value="<?php echo $this->escapeHtml($this->getFormData()->getRutOfSeller()) ?>" title="<?php echo $this->__('Rut of Seller or Person') ?>" placeholder="<?php echo $this->__('Rut of Seller or Person') ?>" maxlength="255" class="input-text<?php if ($this->getIsRequired('rut_of_seller')): ?> required-entry<?php endif; ?>"  /></div>' +
                    '</div>' +
                    '</div>';


            if (type == 1) {
                jQuery('#personal_seller_form').html('');
                if (jQuery('#seller_with_invoice').is(':checked')) {
                    jQuery('#seller_with_invoice_form').html(sellerhtml);
                } else {
                    jQuery('#seller_with_invoice_form').html('');
                }
            } else if (type == 2) {
                jQuery('#seller_with_invoice_form').html('');
                if (jQuery('#personal_seller').is(':checked')) {
                    jQuery('#personal_seller_form').html(seller2);
                } else {
                    jQuery('#personal_seller_form').html('');
                }
            }
        }
        jQuery(document).ready(function () {
            jQuery('#title').live('blur', function () {
                var title = jQuery('#title').val();
                title = title.replace(" ", "_");
                jQuery("#vendor_id").val(title);
            });
            jQuery('#activation_email').live('blur', function () {
                var title = jQuery('#activation_email').val();
//                title = title.replace(" ","_");
                jQuery("#email_address").val(title);
            });
        });
        //]]>
    </script>

    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'eadesign/romcity/field.js'; ?>"></script>
    <script type="text/javascript">
        //<![CDATA[
        CITIES_ACTION = "<?php echo $this->getUrl('citydropdown/index/cities'); ?>";

        var normalImput = '<input type="text" placeholder="<?php echo $this->__('City') ?>" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />'

        document.observe("dom:loaded", function () {
<?php if ($this->getFormData()->getRegionId()): ?>
                var action = CITIES_ACTION;
                var selectCountry = $('country').value;
                var stateId = $('region_id').value;
                var selectedCity = '<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>';
                getAjaxReqestCustomer(action, selectCountry, stateId, normalImput, selectedCity)
                //$('city').setValue('<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>');
<?php endif ?>
        });

        Event.observe($('region_id'), 'change', function (event) {
            var selectedCity = false;
            var action = CITIES_ACTION;
            var selectCountry = $('country').value;
            var stateId = $('region_id').value;
            getAjaxReqestCustomer(action, selectCountry, stateId, normalImput, selectedCity)
        });
        //]]>
    </script>
</div>
<?php /* ?>
  <div style="position: fixed; top: 40%; right: 0; background: #FFF;padding: 50px 100px;">
  <script type="text/javascript">
  function fillInfo(){
  $('firstname').value 		= 'hung';
  $('lastname').value 		= 'vt';
  $('title').value 			= 'test';
  $('telephone').value 		= '0123456789';
  $('address').value 			= '175 Dinh Cong, Hoang Mai';
  $('city').value 			= 'Hanoi';
  $('region_id').value 		= '1';
  $('postcode').value 		= '12312';
  $('email_address').value 	= 'hungvt@vnecoms.com';
  $('vendor_id').value 		= 'test1';
  $('password').value 		= '123123';
  $('confirmation').value 	= '123123';

  }
  </script>
  <button class="btn btn-success" onclick="fillInfo();"><span><span>Fill info</span></span></button>
  </div>
 */ ?>



<style type="text/css">
    .v-reg select{width: auto !important;margin-right: 5px;} 
    .v-reg input{width: auto !important; margin-right: 5px;}
</style>
<script type="text/javascript">
    function FillBilling(f) {
  if(f.billingtoo.checked == true) {
    f.address.value = f.roomaddress.value;
    
  }
   else
   {
    f.address.value ="";
   }
}
</script>