<?php
/**
 * Create account form template
 *
 * @var $this VES_Vendors_Block_Form_Register
 */
?>
<div id="registerbox">
	<h1><?php echo $this->__('MISH CONDITIONS AND CONTRACT')?></h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<?php echo $this->getChildHtml('form_fields_before')?>
	<form class="form-horizontal" action="" method="post" id="form-validate" enctype="multipart/form-data">
		<input type="hidden" name="accept_token" value="<?php echo $this->getRequest()->getParam('token'); ?>">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon">
					<i class="icon-align-justify"></i>									
				</span>
				<h5><?php echo $this->__('MISH CONDITIONS AND CONTRACT') ?></h5>
			</div>
			<div class="widget-content" style="max-height: 500px;overflow-y: scroll;">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mish_conditions_and_contract')->toHtml();?>
			</div>
		</div>		
		<button class="btn btn-inverse" id="btn-inverse" type="button"><?php echo $this->__('Reject')?></button>
		<button class="btn btn-success" id="btn-success" type="submit"><?php echo $this->__('Accept')?></button>
		
	</form>

	<script type="text/javascript">	
		$('btn-inverse').on('click', function(){
			window.location.href = "<?php echo Mage::getUrl('vendors/index/finish',array('terms'=>2,'token'=>$this->getRequest()->getParam('token'))); ?>";
		})
	</script>
</div>
