<?php
 $imagepath = Mage::getBaseDir('media').DS."slider".DS;
 $btmodel = Mage::getModel('btslider/btslider')->getCollection();
foreach ($btmodel as $imagedata) { 
  $image = $imagedata['images'];
  $url = $imagedata['url'];
  $imagelabel = $imagedata['imagelabel'];
  $title = $imagedata['title'];
  $imagethumbnail = $imagepath.$image;
}
?>
<div class="homebannerTopcount">
 <div id="myCarousel" class="carousel slide bannerCount" data-ride="carousel">
    
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
      <?php $i=0;
        foreach ($btmodel as $imagedata) { 
            $id= $imagedata['btbanner_id'];
            $image = $imagedata['images'];
            $url = $imagedata['url'];
            $imagelabel = $imagedata['imagelabel'];
            $title = $imagedata['title'];
            $imagethumbnail = $imagepath.$image;
?>
        <div class="item <?php if ($i==0) { echo "active";} ?>">

           <a href="<?php echo $url; ?>" title="<?php echo $title; ?>" alt="<?php echo $title; ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/".$image; ?>"></a>
           <div class="carousel-caption">
         <!--    <h3>Headline</h3>
            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p> -->
          </div>
        </div><!-- End Item -->
<?php $i++; } ?>      
      </div><!-- End Carousel Inner -->


      <ul class="nav nav-pills nav-justified" >
      <?php $m=0;
        foreach ($btmodel as $imagedata) { 
            $id= $imagedata['btbanner_id'];
            $imagelabel = $imagedata['imagelabel']; ?>
          <li data-target="#myCarousel" data-slide-to="<?php echo $m; ?>" class="col <?php //if ($m==0) { echo "active";} ?>"><a href="#"><?php echo $imagelabel; ?></a></li>
      <?php $m++; } ?>
        </ul>


    </div><!-- End Carousel -->

  <!-- Right side AD image -->
  <div class="bannerrightAdd">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-rightside-add')->toHtml();?>
  </div>

    <!-- Right side AD image mobile view -->
  <div class="bannerrightAddMobile">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-rightside-add-mobileview')->toHtml();?>
  </div>
 <!-- top selling product -->
  <div class="topsellingCount">
<div>
    <h3><?php echo __('Top Selling Products'); ?></h3>
</div>

 <ul class="bxslider">
<?php 
 $currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
        $storeId = (int) Mage::app()->getStore()->getId();
 
        // Date
        $date = new Zend_Date();
        $toDate = $date->setDay(1)->getDate()->get('Y-MM-dd');
        $fromDate = $date->subMonth(1)->getDate()->get('Y-MM-dd');
 
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addStoreFilter()
            ->addPriceData()
            ->addTaxPercents()
            ->addUrlRewrite()
            ->setPageSize(6);
 
        $collection->getSelect()
            ->joinLeft(
                array('aggregation' => $collection->getResource()->getTable('sales/bestsellers_aggregated_monthly')),
                "e.entity_id = aggregation.product_id AND aggregation.store_id={$storeId} AND aggregation.period BETWEEN '{$fromDate}' AND '{$toDate}'",
                array('SUM(aggregation.qty_ordered) AS sold_quantity')
            )
            ->group('e.entity_id')
            ->order(array('sold_quantity DESC', 'e.created_at'));
 
        Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);

        foreach ($collection as $collectiondata) {
            $bestProductId = $collectiondata['entity_id'];
            $bestProductData = Mage::getModel('catalog/product')->load($bestProductId);
             $best_product_image_url = $bestProductData->getImageUrl();
/*
            echo "<pre>++";
            print_r($bestProductData->getData());*/
            
                    ?>
                     <a href="<?php echo $bestProductData->getProductUrl(); ?>">
                    <li class="shadow">
                   
                     
                        <div>
                            <img src="<?php echo $best_product_image_url ?>"  class="img-responsive"  />
                       </div>
                       <div class="productNameing">
                           <div class="productsnameInner"><?php echo __($bestProductData->getName()); ?></div>
                       <div>

                            <?php echo $this->getChildHtml('related_products') ?>
               <?php $vendorid= $bestProductData['vendor_id'] ;
                $ratingsummary=array();
                $vendorReviewModel = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);

                foreach ($vendorReviewModel as $vendorReview) {
                   $ratingsummary[]=$vendorReview['summary_percent'];
                   $count = count($ratingsummary);
                   $sum = array_sum($ratingsummary);  
          }
                   $average = ($sum/$count);
      ?>

                                            <div class="ratings">
                                                <?php if ($average):?>
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                                        </div>
                                                    </div>
                                                <?php endif;?>
                                              </div>
                                               <!--  <i class="price-text-color fa fa-star"></i> -->
                                             </div>
                                             <br>
                                            <h5 class="price-text-color">
                                                <?php echo __($currency_symbol." ".round($bestProductData->getPrice(),2)); ?></h5>
                                        </div>
                                         
                    
                    </li>
                    </a>

           <?php 
        }
?>
</ul>
</div>

<div>



<style>
#myCarousel .nav a small {
    display:block;
}
#myCarousel .nav {
  background:#eee;
}
.nav > li > a:focus {background-color: #fe585c !important;}
.nav-justified > li > a:hover, .nav-tabs.nav-justified > li > a {background-color: #fe585c !important; color:#fff;}

</style>
<script>
  
  $(document).ready( function() {
    $('#myCarousel').carousel({
    interval:   4000
  });
  
  var clickEvent = false;
  $('#myCarousel').on('click', '.nav a', function() {
      clickEvent = true;
      $('.nav li').removeClass('active');
      $(this).parent().addClass('active');    
  }).on('slid.bs.carousel', function(e) {
    if(!clickEvent) {
      var count = $('.nav').children().length -1;
      var current = $('.nav li.active');
      current.removeClass('active').next().addClass('active');
      var id = parseInt(current.data('slide-to'));
      if(count == id) {
        $('.nav li').first().addClass('active');  
      }
    }
    clickEvent = false;
  });
});

</script>

