<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * Under the terms and conditions of this Agreement, the Author grants you a nonexclusive license to use the Module 
 * on a computer server and under your designated domain name and only for purposes of operating an electronic-commerce store 
 * on the Internet. The Module is licensed, not sold.
 *
 * DISCLAIMER
 *
 * The author forbids, under any circumstances, the unauthorized reproduction of the Module or use of illegally obtained Module. 
 * Making illegal copies of the Module is prohibited. Individuals who violate copyright law and this Module license agreement may be 
 * subject to criminal or civil prosecution by the owner of the copyright.
 *
 * @category    Nanowebgroup
 * @package     Rockslide
 * @copyright   Copyright (c) 2013 Nanowebgroup. (http://www.nanowebgroup.com)
 * @license     http://nanowebgroup.com/rockslide-license/  
 * @version     1.1.0
 */

/**
 * Category controller
 *
 * @category   Nanowebgroup
 * @package    Rockslide
 * @author     Nanowebgroup <support@nanowebgroup.com>
 */
 ?>
<div id="search_module">
	<div class="search_section">
		<div class="shape section full">
			<div style='text-align:center;' class="slider_wrapper">
				<h1>This Mobile Theme is provided by Nanowebgroup</h1>
				<p>The HybridMobile Theme is currently inactive and needs to be activated. </p>
				<p>Please visit <a href='http://www.rockslide.co'>www.rockslide.co</a> to activate your diamond search module.</p> <br> 
				<?php 
	            //$link = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/nanowebgroup/diamondsearch/images/RS.png'; 
	            ?>
	            <!-- <a href='http://www.rockslide.co'><img title="RockSlide" alt="RockSlide" width='200' height='200' src='<?php echo $link;?>'></a> -->
			</div>
		</div>
	</div>
</div>