<!-- Details page left section -->
<div class="detailspageLeft">
    <div class="imagelistingLeft">
        <ul>
            <li><img src="http://localhost/miss/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
            <li><img src="http://localhost/miss/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
            <li><img src="http://localhost/miss/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
        </ul>
    </div>
    <div class="imageRight">
        <img src="http://localhost/miss/mishproject/media/wysiwyg/detailpage_printerimage.png">
    </div>
    <div class="clr"></div>
</div>
<!-- Details page left section -->
<!-- Details page Right section -->
<div class="detailspageRight">
    <div class="topHead">
        <h1>HP DeskJet 1112 Printer</h1>
        <ul>
            <li><a href="#"><img src="http://localhost/miss/mishproject/media/wysiwyg/star_icon.jpg"> <span>(3.6)</span> 706 Ratings</a></li>
            <li><a href="#">104 Reviews</a></li>
            <li><a href="#">3Selfies</a></li>
            <li><a href="#">Have a question</a></li>
            <div class="clr"></div>
        </ul>
    </div>

    <div class="priceofferCount">
    <!-- Details Price section -->
        <div class="priceCount">
            <div class="linethroughPrice">Rs, 2,923</div>
            <div class="currentPrice">Rs. 2,049 <span>30% OFF</span></div>
        </div>
    <!-- Details Price section -->  
    <!-- Details Offer Applicable section -->
        <div class="offerApplicable">
            <div>(2) Offers  Applicable on cart</div>
            <div class="innerCount">
                <div class="textbox">
                    <div class="left"><img src="http://localhost/miss/mishproject/media/wysiwyg/offer_icon.jpg"></div>
                    <div class="right">Get 5% instant discount + 10X rewards using Mish HDFC Bank Credit Card <a href="#">T&C</a></div>
                    <div class="clr"></div>
                </div>
                <div class="textbox borderbtmNone">
                    <div class="left"><img src="http://localhost/miss/mishproject/media/wysiwyg/offer_icon.jpg"></div>
                    <div class="right">Get 5X Reward Points Using HDFC Bank Credit Cards <a href="#">T&C</a></div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
    <!-- Details Offer Applicable section -->
        <div class="clr"></div>
     </div>  

        <div class="addtoCartCount">
            <div class="buttonCount">
                <input type="button" value="add to cart">
                <input type="button" value="buy now" class="color">
            </div>

        </div>

        <div class="deliveryCount">
            <span>Delivery</span>
            <input type="text" placeholder="Enter Pincode">
            <input type="button" value="Check" class="inputbutton">
            <span>Generally delivered by 5 days</span>
        </div>

        <div class="p-keyfeatures kf-below-name productType">
                <ul class="clr">
                    <li class="col-xs-8 reset-padding" title="Product Type: Inkjet Printers"><span class="list-circle"></span>
                            <span class="h-content">Product Type: Inkjet Printers</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Colour Type: Color"><span class="list-circle"></span>
                            <span class="h-content">Colour Type: Color</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Yield (No. of Pages): 1000"><span class="list-circle"></span>
                            <span class="h-content">Yield (No. of Pages): 1000</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Warranty: 1 Year Manufacturer Warranty"><span class="list-circle"></span>
                            <span class="h-content">Warranty: 1 Year Manufacturer Warranty</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Utility: Home"><span class="list-circle"></span>
                            <span class="h-content">Utility: Home</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="View all item details"><span class="list-circle" style="visibility:hidden"></span>
                            <span class="h-content viewAllDetails"><a href="javascript: void(0)">View all item details</a></span>
                        </li>
                    </ul>
            </div>
            <div class="mispolicyDiv">
                <div class="pdp-grante-cont marT15">
                            <span class="pe-head">Mish Guarantee</span>
                            <div id="policyEngineGoldText">
                                <span class="pe-innerText" title="TrustPay : 7 Days Easy Replacements">
                                        TrustPay : 7 Days Easy Replacements</span>
                                <a class="know-more" href="https://www.snapdeal.com/page/TrustPay" target="_blank">Know More <i class="sd-icon sd-icon-next"></i></a>
                                <p class="sdGoldCont ">
                                    <i id="policyGoldIcon" class="sdGoldDeliveryIcon footerIconsImg "></i>
                                    Longer 14-days return period<span class="sdgHoverToolTip" omnisrc="sdBenefitsWidget">
                                <i class="sd-icon sd-icon-ic-more"></i>
                                </span></p>
                            </div>
                        </div>
                    </div>
</div>
<!-- Details page Right section -->
<div class="clr"></div>
