<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); 
/*echo "<pre>+++";
print_r($_product->getData());
echo "</pre>";*/
$vendorid = $_product->getVendorId();
$price = $_product->getPrice();
$specialprice = $_product->getSpecialPrice();
$currenct_symbol= Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<!-- Details page left section -->
<!-- <div class="detailspageLeft">
    <div class="product-img-box">
            <?php //echo $this->getChildHtml('media') ?>
        </div>
    <div class="clr"></div>
</div> -->
<div class="detailspageLeft">
    <div class="imagelistingLeft">
        <ul>
            <li><img src="http://localhost/mish/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
            <li><img src="http://localhost/mish/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
            <li><img src="http://localhost/mish/mishproject/media/wysiwyg/detail_printer_smallimage.jpg"></li>
        </ul>
    </div>
    <div class="imageRight">
        <img src="http://localhost/mish/mishproject/media/wysiwyg/detailpage_printerimage.png">
    </div>
    <div class="clr"></div>
</div>
<!-- Details page left section -->
<!-- Details page Right section -->
<div class="detailspageRight">
    <div class="topHead">
        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        
        <ul>
            <li>    
            <span>
                            <?php 
                             $vendorreview = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);
                               foreach ($vendorreview as $vendor123) {
                                   $ratingsummary=array($vendor123['summary_percent']);
                                   $count = count($ratingsummary);
                                   $sum = array_sum($ratingsummary); 
                                 }
                                   $average = ($sum/$count);
                                   //echo "average- ".$average;
                             ?>

                            <div class="ratings pull-left">
                                <?php if ($average):?>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                    
                                        </div>
                                    </div>
                                <?php endif;?>
                              </div>
                    </span>
                    </li>
            <li><a href="#">104 Reviews</a></li>
            <li><a href="#">3Selfies</a></li>
            <li><a href="#">Have a question</a></li>
            <div class="clr"></div>
        </ul>
    </div>

    <div class="priceofferCount">
    <!-- Details Price section -->
        <div class="priceCount">

         
       
            <div class="<?php if($_product->getSpecialPrice()){
                echo 'linethroughPrice';
                }else{
                    echo 'currentPrice';
                    } 
                ?>"><?php echo $currenct_symbol." ".number_format($_product->getPrice(),2);; ?></div>
            
             <?php if($_product->getSpecialPrice()){ ?>
                <div class="currentPrice"><?php echo $currenct_symbol." ".number_format($_product->getSpecialPrice(),2); ?>
                <span>
                   <?php 
                        $originalPrice = $_product->getPrice();
                        $finalPrice = $_product->getSpecialPrice();
                        $percentage = 0;
                        if ($originalPrice > $finalPrice) {
                            $percentage = ($originalPrice - $finalPrice) * 100 / $originalPrice;
                        }

                        if ($percentage) {
                            echo $this->__($percentage . '%');
                        }
                        ?>
                </span></div>
            <?php } ?>
            <div><?php echo $this->getChildHtml('product_type_data');?></div>
        </div>
    <!-- Details Price section -->  
    <!-- Details Offer Applicable section -->
        <div class="offerApplicable">
            <div>(2) Offers  Applicable on cart</div>
            <div class="innerCount">
                <div class="textbox">
                    <div class="left"><img src="http://localhost/mish/mishproject/media/wysiwyg/offer_icon.jpg"></div>
                    <div class="right">Get 5% instant discount + 10X rewards using Mish HDFC Bank Credit Card <a href="#">T&C</a></div>
                    <div class="clr"></div>
                </div>
                <div class="textbox borderbtmNone">
                    <div class="left"><img src="http://localhost/mish/mishproject/media/wysiwyg/offer_icon.jpg"></div>
                    <div class="right">Get 5X Reward Points Using HDFC Bank Credit Cards <a href="#">T&C</a></div>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
    <!-- Details Offer Applicable section -->
        <div class="clr"></div>
     </div>  

        <div class="addtoCartCount">
         <?php if (!$this->hasOptions()):?>
            <?php //if($_product->isSaleable()): ?>
            <div class="buttonCount">
                <input type="button" value="add to cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                <input type="button" value="buy now" class="color" onclick="setcheckoutLocation('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo Mage::getUrl('checkout/onepage') ?>')">
              <!--    <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?> -->
                 <?php //endif; ?>

                 <script>
                 function setcheckoutLocation(location,chkout)
                 {
                  jQuery.ajax({
                                type:"GET",
                                url:location,
                                success:function(data){
                                     window.location.href = chkout;
                                }
                             });
                }
                </script>
 <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
            </div>

        </div>

            <?php //echo $this->getTierPriceHtml() ?>
            <?php //echo $this->getChildHtml('extrahint') ?>
             <?php //echo $this->getChildHtml('other');?>

        <div class="deliveryCount">
           <?php echo $this->getChildHtml('deliverycheck');?>
        </div>

        <div class="p-keyfeatures kf-below-name productType">
                <ul class="clr">
                    <li class="col-xs-8 reset-padding" title="Product Type: Inkjet Printers"><span class="list-circle"></span>
                            <span class="h-content">Product Type: Inkjet Printers</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Colour Type: Color"><span class="list-circle"></span>
                            <span class="h-content">Colour Type: Color</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Yield (No. of Pages): 1000"><span class="list-circle"></span>
                            <span class="h-content">Yield (No. of Pages): 1000</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Warranty: 1 Year Manufacturer Warranty"><span class="list-circle"></span>
                            <span class="h-content">Warranty: 1 Year Manufacturer Warranty</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="Utility: Home"><span class="list-circle"></span>
                            <span class="h-content">Utility: Home</span>
                       </li>
                    <li class="col-xs-8 reset-padding" title="View all item details"><span class="list-circle" style="visibility:hidden"></span>
                            <span class="h-content viewAllDetails"><a href="javascript: void(0)">View all item details</a></span>
                        </li>
                    </ul>
            </div>
            <div class="mispolicyDiv">
                <div class="pdp-grante-cont marT15">
                            <span class="pe-head">Mish Guarantee</span>
                            <div id="policyEngineGoldText">
                                <span class="pe-innerText" title="TrustPay : 7 Days Easy Replacements">
                                        TrustPay : 7 Days Easy Replacements</span>
                                <a class="know-more" href="https://www.snapdeal.com/page/TrustPay" target="_blank">Know More <i class="sd-icon sd-icon-next"></i></a>
                                <p class="sdGoldCont ">
                                    <i id="policyGoldIcon" class="sdGoldDeliveryIcon footerIconsImg "></i>
                                    Longer 14-days return period<span class="sdgHoverToolTip" omnisrc="sdBenefitsWidget">
                                <i class="sd-icon sd-icon-ic-more"></i>
                                </span></p>
                            </div>
                        </div>
                    </div>
</div>
<!-- Details page Right section -->
<div class="clr"></div>



<!-- Seller Details section -->
<?php 
$vendorid = $_product->getVendorId();
if($vendorid){
    $vendor_info = Mage::getModel('vendors/vendor')->load($vendorid,'vendor_id');
    $vendorName = $vendor_info->getFirstname().' '.$vendor_info->getLastname();
    $companyName = $vendor_info->getCompany();
    $cityName = $vendor_info->getCity();
    $logo = $vendor_info->getLogo();
    $vendorurlid = $vendor_info->getVendorId();

    $mediaurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);

?>
<div class="detailsmidSection">
    <div class="sellerDetails">
        <h1><?php echo __('Seller Details');  ?></h1>
        <div class="sellerInner">
            <div class="left">
                <div class="sellerImage">
                   <img src="<?php echo $mediaurl.$logo; ?>" class="img-circle" alt="Cinque Terre" width="70" height="70">
                </div>
                <div class="sellerinfo">
                    <div>
                        <span><?php echo __($vendorName); ?></span>
                <span>
                    <?php if($cityName || $companyName){
                        echo "(".$cityName;
                        if($companyName){
                            echo ",".$companyName;
                        }
                        echo ")";
                        } ?>
                </span>
                    </div>
                    <div>
                        <?php 
                             $vendorreview = Mage::getModel('vendorsreview/review')->getCollection()->addFieldToFilter('vendor_id',$vendorid);
                               foreach ($vendorreview as $vendor123) {
                                   $ratingsummary=array($vendor123['summary_percent']);
                                   $count = count($ratingsummary);
                                   $sum = array_sum($ratingsummary); 
                                 }
                                   $average = ($sum/$count);
                                   //echo "average- ".$average;
                             ?>

                            <div class="ratings pull-left">
                                <?php if ($average):?>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo ceil($average) ; ?>%;">
                                    
                                        </div>
                                    </div>
                                <?php endif;?>
                              </div>
                    </div>
                  <br>  <div><a href="#">5 more sellers starting from Rs. 2,049 </a></div>
                </div>

            </div>
            <div class="right">
                    <div class="abouttheSeller">
                        <span>About the Seller</span>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                    </div>
                  </div>  
                <div class="clr"></div>
        </div>
        <div class="visitStore">
                   <?php echo __('Expand your business to millions of customers '); ?> <a href="<?php echo $this->getUrl().'vendors/'; ?>">Sell this item on MISH</a><span><a href="<?php echo $this->getUrl().$vendorurlid; ?>">VIEW STORE</a></span>
                </div>
    </div>

    <!-- Seller Details section -->
    <?php } ?>
    <!-- Review and rating section -->
    <div class="ratingReview customer_review">
        <h1>Ratings & Reviews</h1>

            <div class="product_review">

    <ul itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating">
        <li class="first  col-xs-8  leftAlignment">
                <div class="chart text">
                    <div class="rating-middle-section clearfix"> 
                        <div class="rating-text"><span class="rating">3.8</span>/5</div> 
                        <div class="rating-stars product-rating clearfix"><img src="http://localhost/mish/mishproject/media/wysiwyg/star_icon.jpg"></div>
                        <p class="total-review-txt">751 Ratings &amp; 105 Reviews</p> 
                        <a class="view-all-reviews" >View All Reviews</a>
                        </div>
                </div>
            </li>
        <li id="user-reviewRec-content-div" class="second col-xs-8" style="border-right: solid 1px #e8e8e8;">
            <div class="text aligncenter">
                <div id="rcmnd-text" class="LTgray fs14">
                    <div class="recom-text"><span class="recom">75<span class="percentText">%</span></span></div> 
                            <div class="recom-subtext">Based on 173 Recommendations.</div>
                        </div>
                <div class="recomBtn marT30">
                    <span class="LTblack col-xs-13"> Would you like to recommend this item?</span>
                    <a id="recBtn" class="btn white-btn rippleWhite col-xs-4 reset-margin");">Yes</a>
                    <a id="notRecBtn" class="btn white-btn rippleWhite col-xs-4 reset-margin");">No</a>
                </div>
             </div>
        </li>
        
        <li id="user-reviewRate-content-div" class="third col-xs-8">
            <div class="aligncenter">
                <p id="rev-text"><span>Have you used this product?</span></p>
                <a class="btn btn-orange rippleWhite js-userReviewed reviewBtn")">Review</a>
            </div>
        </li>
    </ul>
    <div class="clear"></div>
</div>

    </div>
    <!-- Review and rating section -->
<div class="clr"></div>
</div>
