	<?php
			
			$plsessionId =  Mage::getSingleton('core/session')->getPlsessionId(); 
			$plUserModel = Mage::getModel('personallogistic/personallogistic')->load($plsessionId);
			$pluserlastName     = $plUserModel->getLastname();
			$plfullName         = $plUserModel->getFirstname()." ".$plUserModel->getLastname();
			$pluserFirstName    = $plUserModel->getFirstname();
			$pluserLastName     = $plUserModel->getLastname();
			$pluserDob          = $plUserModel->getDob();
			$pluserName         = $plUserModel->getFirstname();
			$pluserMail         = $plUserModel->getMail();
			$pluserTransport    = $plUserModel->getTransport();
		
			$pluserPrice        = $plUserModel->getPrice();
			$pluserProfilepic   = $plUserModel->getProfilepic();
			$pluserRut          = $plUserModel->getRut();
      $pluserRegion       = $plUserModel->getRegion();

      $explodeRegion = explode(',',$pluserRegion);	
      
		?>


<div>
		<h3 class="customheader"><?php echo __('Personal Logistic'); ?></h3>
</div>

 

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4><?php echo __('Dashboard'); ?></h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="<?php echo $this->getBaseUrl().'personallogistic/index/dashboard'; ?>"><?php echo __('Profile'); ?></a></li>
        <li><a href="<?php echo $this->getBaseUrl().'personallogistic/index/orderdashboard'; ?>"><?php echo __('Orders'); ?></a></li>
        <li><a href="<?php echo $this->getBaseUrl().'personallogistic/index/logout'; ?>"><?php echo __('Logout'); ?></a></li>
      </ul><br>

    </div>
<h3><?php echo __("Welcome ".$plfullName); ?></h3>
    <div class="col-sm-9">
      <h4><small><?php echo __('Profile Details'); ?></small></h4>

  	<hr>
	<div class="row">
    <form class="form-horizontal" role="form" action="<?php echo $this->getUrl('personallogistic/index/personalLogisticDetails') ?>"  method="POST" enctype="multipart/form-data">
      <!-- left column -->
      <div class="col-md-3">
        <div class="text-center">
          <img src="<?php echo $this->getBaseUrl().'media/personallogistic/profilepic/'.$pluserProfilepic.''; ?>" class="avatar img-circle editpicdimensions" alt="avatar">
          <h6><?php echo __('Upload a different photo...'); ?></h6>
          
          <input type="file" class="form-control" name="profilepic">
        </div>
      </div>
      
      <!-- edit form column -->
      <div class="col-md-9 personal-info">
       
        
        
      

        <input type="hidden" name="pluserID" value="<?php echo $plsessionId; ?>">
          <div class="form-group">
            <label class="col-lg-3 control-label"><?php echo __('First Name:'); ?></label>
            <div class="col-lg-8">
              <input class="form-control" type="text" name="firstname" value="<?php echo $pluserFirstName; ?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label"><?php echo __('Last Name:'); ?></label>
            <div class="col-lg-8">
              <input class="form-control" type="text" name="lastname" value="<?php echo $pluserLastName; ?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label"><?php echo __('Date of Birth:'); ?></label>
            <div class="col-lg-8">
              <input class="form-control" type="date" name="dob" value="<?php echo $pluserDob; ?>">
            </div>
          </div>
         
       
          <div class="form-group">
            <label class="col-md-3 control-label"><?php echo __('Mail/Correo:'); ?></label>
            <div class="col-md-8">
              <input class="form-control" type="text" name="mail" value="<?php echo $pluserMail; ?>">
            </div>
          </div>
           <div class="form-group">
            <label class="col-md-3 control-label"><?php echo __('Rut:'); ?></label>
            <div class="col-md-8">
              <input class="form-control" type="text" name="rut" value="<?php echo $pluserRut; ?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label"><?php echo __('Types of Transportation:'); ?></label>
            <div class="col-md-8">
              <ul>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/10kg.png'); ?>" alt="10 kg" /><label for="transport1"><?php echo __('Bicycle') ?> <input type="radio" name="transport" id="transport1" value="Bicycle" <?php 
							if($pluserTransport == 'Bicycle'){
								echo "checked";
								}?> /></label></li>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/20kg.png'); ?>" alt="20 kg" /><label for="transport2"><?php echo __('Small Car') ?> <input type="radio" name="transport" id="transport2" value="Small Car" <?php 
							if($pluserTransport == 'Small Car'){
								echo "checked";
								}?> /></label></li>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/20kg.png'); ?>" alt="20 kg" /><label for="transport3"><?php echo __('Medium Auto') ?> <input type="radio" name="transport" id="transport3" value="Medium Auto" <?php 
							if($pluserTransport == 'Medium Auto'){
								echo "checked";
								}?> /></label></li>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/more than 20kg.png'); ?>" alt="more than 20 kg" /><label for="transport4"><?php echo __('Big Car') ?> <input type="radio" name="transport" id="transport4" value="Big Car" <?php 
							if($pluserTransport == 'Big Car'){
								echo "checked";
								}?>/></label></li>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/more than 20kg.png'); ?>" alt="more than 20 kg" /><label for="transport5"><?php echo __('Heavy Duty Truck') ?> <input type="radio" name="transport" id="transport5" value="Heavy Duty Truck" <?php 
							if($pluserTransport == 'Heavy Duty Truck'){
								echo "checked";
								}?>/></label></li>
							<li><img src="<?php echo $this->getSkinUrl('personallogistic/4kg.png'); ?>" alt="4 kg" /><label for="transport6"><?php echo __('Walking') ?> <input type="radio" name="transport" id="transport6" value="Walking" <?php 
							if($pluserTransport == 'Walking'){
								echo "checked";
								}?> /></label></li>
					   </ul>
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label"><?php echo __('Region:'); ?></label>
            <div class="col-md-8">
              <select name="region[]" multiple="" aria-required="true">
								<option value="" disabled="" selected="">Select Region</option>
								<option value="Aisén del General Carlos Ibáñez del Campo"
                    <?php
                      if(in_array("Aisén del General Carlos Ibáñez del Campo",  $explodeRegion)){
                        echo "selected";
                      } 
                    ?>

                >Aisén del General Carlos Ibáñez del Campo</option>
								<option value="Antofagasta"
                   <?php
                      if(in_array("Antofagasta",  $explodeRegion)){
                        echo "selected";
                      } 
                    ?>
                >Antofagasta</option>
								<option value="Araucanía"profilepic
                 <?php
                      if(in_array("Araucanía",  $explodeRegion)){
                        echo "selected";
                      }
                    ?>
                >Araucanía</option>
								<option value="Arica and Parinacota"
                   <?php
                      if(in_array("Arica and Parinacota",  $explodeRegion)){
                        echo "selected";
                      }
                    ?>
                >Arica and Parinacota</option>
								<option value="Atacama"
                   <?php
                      if(in_array("Atacama",  $explodeRegion)){
                        echo "selected";
                      }
                    ?>
                >Atacama</option>
             </select>
            </div>
          </div>
           
            <div class="form-group">
            <label class="col-md-3 control-label"><?php echo __('Price for KM:'); ?></label>
            <div class="col-md-8">
              <input class="form-control" type="text"  name="price" value="<?php echo $pluserPrice; ?>">
            </div>
          </div>

          <div>
            <label for="personalid"><?php echo __('Personal Id Card/Rut (1):'); ?></label>
            <input type="file" name="personalid" id="personalid" />
        </div>

        <div>
            <label for="personalid"><?php echo __('Driving License card:'); ?></label>
            <input type="file" name="personalid2" id="personalid2" />
        </div>

          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
            <button type="submit" name="sub" class="btn btn-primary"><?php echo __('Save Changes');?></button>
              <span></span>
              <input type="reset" class="btn btn-default" value="Cancel">
            </div>
          </div>
        </form>
      </div>
  </div>

<hr>

    </div>
  </div>
</div>




