
<div class="container">
    <div class="row vertical-offset-100">
    	<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title" style="text-align: center;"><?php echo __('Personal Logistic Login');?></h3>
			 	</div>
			  	<div class="panel-body">
			    	<form  action="<?php echo $this->getUrl('personallogistic/index/pllogin')?>" enctype="multipart/form-data" method="POST">
                    <fieldset>
			    	  	<div class="form-group">
			    		    <input class="form-control" placeholder="<?php echo __('E-mail'); ?>" name="email" type="email">
			    		</div>
			    		<div class="form-group">
			    			<input class="form-control" placeholder="<?php echo __('Password'); ?>" name="password" type="password">
			    		</div>
			    		<input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
			    		
			    	</fieldset>
			      	</form>
			           	<label>
			    	    		<a href="<?php echo $this->getBaseUrl();?>" class="pull-left"><?php echo __('<< Back'); ?></a>
			    	    </label>
			    </div>
			</div>
		</div>
	</div>
</div>
