	<?php
			
			$plsessionId =  Mage::getSingleton('core/session')->getPlsessionId(); 
			$plUserModel = Mage::getModel('personallogistic/personallogistic')->load($plsessionId);
			$pluserlastName     = $plUserModel->getLastname();
			$plfullName         = $plUserModel->getFirstname()." ".$plUserModel->getLastname();
      $pluserprice        = $plUserModel->getPrice();

      $pluserModeldata = Mage::getModel('personallogistic/personallogisticuserorder')->getCollection()
      ->addFieldToFilter('pl_user_id',array('eq'=>$plsessionId));
     
			
		?>
 

<div>
		<h3 class="customheader"><?php echo __('Personal Logistic'); ?></h3>
</div>

 

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav" >
      <h4><?php echo __('Dashboard'); ?></h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="<?php echo $this->getBaseUrl().'personallogistic/index/dashboard'; ?>"><?php echo __('Profile'); ?></a></li>
        <li class="active"><a href="<?php echo $this->getBaseUrl().'personallogistic/index/orderdashboard'; ?>"><?php echo __('Orders'); ?></a></li>
        <li><a href="<?php echo $this->getBaseUrl().'personallogistic/index/logout'; ?>"><?php echo __('Logout'); ?></a></li>
      </ul><br>

    </div>
<h3><?php echo __("Welcome ".$plfullName); ?></h3>
    <div class="col-sm-9">
      <h4><small><?php echo __('Order Details'); ?></small></h4>

  	<hr>
    <div class="selectedCategories">
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search by Order Id" title="Type in a name">
          <table id="myTable" class="display" cellspacing="0">
              <thead>
                  <tr>
                      <th style="padding: 5px;"><?php echo __('Order Increment Id'); ?></th>
                    
                      <th style="padding: 5px;"><?php echo __('Order Delivery Address'); ?></th>
                       <th style="padding: 5px;"><?php echo __('Seller WarehouseAddress'); ?></th>
                    
                      <th style="padding: 5px;"><?php echo __('Order Status'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Status'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Comment'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Amount'); ?></th>
                      <th style="padding: 5px; border-right: none;"><?php echo __('Action'); ?></th>
                  </tr>
              </thead>


              <tbody>

              <?php 
                  foreach($pluserModeldata as $data)
                  {
                    $orderid          = $data->getOrderId();
                    $salesOrder       = Mage::getModel('sales/order')->load($orderid);
                    $vendor_id        = $salesOrder->getVendorId();

                    $vendorcollection=Mage::getModel('inventoryplus/warehouse')->load($vendor_id,'vendor_id');

                       $telephone1=$vendorcollection['telephone']; 
                       $countryid=$vendorcollection['country_id'];
                      $stateid=$vendorcollection['state_id'];

                       $region1 = Mage::getModel('directory/region')->load($stateid);
                      $state_name = $region1->getName();
                     
                        $country = Mage::getModel('directory/country')->loadByCode($countryid);
                         $countryname= $country->getName();

                     

                    $currencysymbol   = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                    $incrementId      = $salesOrder->getIncrementId();
                    $customerFullName = $salesOrder->getCustomerFirstname()." ".$salesOrder->getCustomerLastname();
                    $grandtotal       = $salesOrder->getGrandTotal();
                    $billto           = $salesOrder->getBillingAddress()->format('html'); 
                    $shipto           = $salesOrder->getShippingAddress()->format('html'); 
                    $telephone        = $salesOrder->getShippingAddress()->getTelephone();
                    $weight           = $salesOrder->getWeight();
                    $Order = Mage::getModel('sales/order')->loadByIncrementId($incrementId);
                    $orderItems = $Order->getItemsCollection();
                
              ?>
                    <tr>
                        <td style="padding: 5px;"><?php echo __($incrementId); ?></td>
                      
                        <td style="padding: 5px;"><?php echo __($billto); ?></td>
                        <td style="padding: 5px;"><?php echo __($vendorcollection['street']."<br>".$vendorcollection['city'].","."<br>".$state_name.",".$vendorcollection['postcode']."<br>".$countryname."<br>T: ".$telephone1); ?></td>
                      
                        <td style="padding: 5px;"><?php
                            if($data['order_status'] == 0){
                              echo __('Not Delivered');
                            }else{
                              echo __('Delivered');
                            }
                         ?></td>

                          <td style="padding: 5px;"><?php
                              if($data['payment_status'] == 0){
                              echo __('Unpaid');
                            }else{
                              echo __('Paid');
                            } 
                         ?></td>
                          <td style="padding: 5px;"><?php echo __($data['payment_comment']); ?></td>
                            <td style="padding: 5px;"><?php echo __($data['payment_amount'])." ".$currencysymbol; ?></td>
                        <td style="padding: 5px;border-right: none;">
                        <?php if($data['order_status'] == 0){  ?>
                        <a href="<?php echo $this->getBaseUrl().'personallogistic/index/updateorderstatus/'; ?>?id= <?php echo $data['id']?>" class="confirmationdone"><?php echo __('Done'); ?>
                          
                        </a>
                        <?php }else{
                          echo __('Done');
                          } ?>
                        </td>
                       
                    </tr>
                    <?php } ?>
              </tbody>


          </table>
       </div>
    <hr>

    </div>
  </div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script> 
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('custom/css/custommishfrontend.css')?>" media="all"/>

<script type="text/javascript">
    j('.confirmationdone').on('click', function () {
        return confirm('Are you sure?');
    });
</script>



<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>