<?php
$_item = $this->getItem();
?>
<tr>
    <td<?php if($this->getComment()):?> rowspan="2"<?php endif;?>>
        <img src="<?php echo $this->getProductThumbnail()->resize(80); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
    </td>

    <td>
        <strong><?php echo $this->escapeHtml($this->getProductName()) ?></strong>
        <?php if ($_options = $this->getOptionList()):?>
        <dl>
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd style="margin-left:10px"><?php echo $_formatedOptionValue['value'] ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
    </td>
    <td><?php echo $this->escapeHtml($_item->getSku()); ?></td>
    
    <td>
    <?php foreach($_item->getProposals() as $_proposal):?>
        <div><?php echo $_proposal->getQty()?></div>
    <?php endforeach;?>
    </td>
</tr>
<?php if($this->getComment()):?>
<tr>
    <td colspan="5" style="font-style: italic;"><label style="margin-right: 10px;"><?php echo Mage::helper('vendorsquote')->__('Notes:')?></label><?php echo $this->getComment();?></td>
</tr>
<?php endif;?>


