<?php $_product = $this->getProduct(); ?>
<?php $isAllowedToAddToQuote = Mage::helper('vendorsquote')->isAllowedToQuote($_product);?>
<?php $isAllowedToAddToCart = Mage::helper('vendorsquote')->isAllowedToOrder($_product);?>

<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable() || $isAllowedToAddToQuote): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped() && ($isAllowedToAddToQuote || $isAllowedToAddToCart)): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <?php if($isAllowedToAddToCart):?>
            <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php endif;?>
        <?php if($isAllowedToAddToQuote):?>
            <button onclick="addToQuote('<?php echo Mage::helper('vendorsquote')->getAddToQuoteUrl($_product)?>')" style="margin-left:10px;" type="button" title="<?php echo Mage::helper('vendorsquote')->__('Add To Quote') ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo Mage::helper('vendorsquote')->__('Add To Quote') ?></span></span></button>
        <?php endif;?>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>