<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
        <!--<thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Ship To') ?></th>
                <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th><?php echo $this->__('Status') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>-->
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <div class="order_blk">
					<div class="col3">
                    	<div class="order_info">
                        	<span class="bold">Ordered On</span>
                            <span class="date"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span>
                            <div class="o_links">
                            	<!--<a href="<?php //echo $this->getViewUrl($_order) ?>"><?php //echo $this->__('Order Details') ?></a>
                                <b>|</b>
                                <a href="<?php //echo $this->getViewUrl($_order) ?>"><?php //echo $this->__('Invoice') ?></a>-->
                            </div>
                            <!--<span class="order_no">order #<em><?php //echo $_order->getRealOrderId() ?></em></span>
                            <span class="rec">Recipient <b><?php //echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></b></span>-->
                            <span class="ship"><span class="bold">Ship To:</span> 
                            	<?php echo $_order->getShippingAddress()->format('html') ?> 
                            </span>
                        </div>
                    </div>
				
					<div class="col6">
                    	<div class="item_info">
                        	<!--<span>delivered on <b>Thursday, May 22, 2014</b></span>-->
                            <span class="status">Order <?php echo $_order->getRealOrderId() ?> Status : 
							<?php echo $_order->getStatusLabel() ?></span>
                        </div>
                        <?php $_items = $_order->getItemsCollection(); ?>
						<?php $_count = $_items->count(); ?>
						<?php foreach($_items as $_item){ ?>
						
						<div class="item_detail">
                        	<div class="item_pic">
                            	<?php $_product = Mage::getModel('catalog/product')->load($_item->getProductId());  ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(50,95); ?>" width="50" height="95" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            </div>
                            <div class="item_des">
                            	<h2><?php echo $_item->getName(); ?><span>(<?php echo $_item->getSku(); ?>)</span></h2>
                                <!--<span class="sold">Sold by <b>Life Extension</b></span>
                                <a href="#" class="buy">Buy it again</a>-->
                            </div>
                        </div>
                        
						<?php } ?>
						
                    </div>
					
					<div class="col3 last">
                    	<div class="ob_links">
                        	<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>" class="common_btn"><?php echo $this->__('Reorder This Item') ?></a>
                        <?php endif ?>
							<?php //echo $_order->getRealOrderId() ?>
							<!--<a href="<?php echo Mage::getBaseUrl();?>trackorder/index/popup/" class="common_btn nyroModal">Track Package</a>-->
                            
							<a href="<?php echo Mage::getUrl('trackorder/index/popup/',array('_query'=>array('orderId'=>$_order->getRealOrderId())));?>"  class="common_btn nyroModal">Track Package</a>
							
							<a href="<?php echo Mage::getUrl('helpdesk/contact/form/', array('_query'=>array('order'=>$_order->getRealOrderId()))); ?>" class="common_btn">Contact Us</a>
                            <?php if ($this->helper('urma')->canRMA($_order)) : ?>
							
							<a href="<?php echo $this->helper('urma')->getRMAUrl($_order) ?>" class="common_btn">Return Product</a>
							<?php endif ?>
						</div>
						<span class="total_p"><span class=" bold">TOTAL : </span><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></span>
                    </div>
				</div>
				<!--<tr>
                    <td><?php echo $_order->getRealOrderId() ?></td>
                    <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center">
                        <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>-->
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>

<script type="text/javascript">
jQuery(function() {
  jQuery('.nyroModal').nyroModal();
});
</script>
