<!-- dashboard tabs -->
<?php if ($id = $this->getItemId()): ?>
    <div class="form-dropdown screen" id="edit_add_tab_chart">
        <form method="post" id="edit_chart_form" action="<?php echo $this->getUrl('adminhtml/ind_dashboard/savechart') ?>">
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
            <input type="hidden" name="item_id" value="<?php echo $id ?>" />
            <?php
            $resource = Mage::getSingleton('core/resource');
            $readConnection = $resource->getConnection('read_write');
            $item = Mage::getModel('inventorydashboard/items')->load($id);
            $report_code = $item->getReportCode();
            $reportTypes = Mage::helper('inventorydashboard/constant')->getReportTypes();
            $isFound = false;
            foreach ($reportTypes as $key => $value) {
                foreach ($value['report_code'] as $reportCode => $reportCodeValue) {
                    if (strcmp($report_code, $reportCode) == 0) {
                        $type = $key;
                        $isFound = true;
                        break;
                    }
                }
                if ($isFound == true) {
                    break;
                }
            }
            ?>

            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">
                        <?php echo $this->__('Edit chart %s', $item->getName()) ?>
                    </h4>
                </div>
                <div class="fieldset ">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label">
                                        <label for="chart_name"><?php echo $this->__('Chart Name') ?> <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input type="text" class="required-entry input-text required-entry" value="<?php echo $item->getName() ?>" name="chart_name" maxlength="50" id="chart_name" >            
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label for="group_type"><?php echo $this->__('Report Type') ?> <span class="required">*</span></label></td>
                                    <td class="value">
                                        <select name="group_type" id="group_type" onchange="return dashboard.changeSelectGroupTypeEdit(this);" class="required-entry required-entry select">
                                            <?php $groupTypes = Mage::helper('inventorydashboard')->getGroupType(); ?>
                                            <?php if ($groupTypes): ?>
                                                <?php foreach ($groupTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php if ($key == $type) echo 'selected'; ?>><?php echo $this->__($value['title']) ?></option>
                                                <?php endforeach; ?>
                                            <?php endif ?>
                                        </select>         
                                        <br/><br/>
                                        <select name="sales_report_edit" id="sales_report_edit" onchange="dashboard.changeSalesChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="required-entry required-entry select" <?php
                                        if ($type == 'sales') {
                                            echo 'style="display:inline-block"';
                                        } else {
                                            echo 'style="display:none"';
                                        }
                                        ?>>
                                                    <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('sales'); ?>
                                                    <?php if ($reportTypes): ?>
                                                        <?php $option_selected = 1; ?>
                                                        <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php if ($option_selected == 1 || $key == $report_code) echo 'selected' ?>><?php echo $this->__($value['name']) ?></option>
                                                    <?php $option_selected++ ?>
                                                    <?php
                                                endforeach;
                                                unset($option_selected);
                                                ?>
                                            <?php endif ?>
                                        </select>
                                        <select name="purchaseorder_report_edit" id="purchaseorder_report_edit" onchange="dashboard.changePurchaseorderChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                                        if ($type == 'purchaseorder') {
                                            echo 'style="display:inline-block"';
                                        } else {
                                            echo 'style="display:none"';
                                        }
                                        ?>>
                                                    <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('purchaseorder'); ?>
                                                    <?php if ($reportTypes): ?>
                                                        <?php ?>
                                                        <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                                                    if ($key == $report_code) {
                                                        echo 'selected';
                                                    }
                                                    ?>><?php echo $this->__($value['name']) ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif ?>
                                        </select>
                                        <select name="stockonhand_report_edit" id="stockonhand_report_edit" onchange="dashboard.changeStockonhandChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                                        if ($type == 'stockonhand') {
                                            echo 'style="display:inline-block"';
                                        } else {
                                            echo 'style="display:none"';
                                        }
                                        ?>>
                                                    <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('stockonhand'); ?>
                                                    <?php if ($reportTypes): ?>
                                                        <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                                                    if ($key == $report_code) {
                                                        echo 'selected';
                                                    }
                                                    ?>><?php echo $this->__($value['name']) ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif ?>
                                        </select>
                                        <select name="stockmovement_report_edit" id="stockmovement_report_edit" onchange="dashboard.changeStockmovementChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                                        if ($type == 'stockmovement') {
                                            echo 'style="display:inline-block"';
                                        } else {
                                            echo 'style="display:none"';
                                        }
                                        ?>>
                                                    <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('stockmovement'); ?>
                                                    <?php if ($reportTypes): ?>
                                                        <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                                                    if ($key == $report_code) {
                                                        echo 'selected';
                                                    }
                                                    ?>><?php echo $this->__($value['name']) ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif ?>
                                        </select>
                                        <select name="customer_report_edit" id="customer_report_edit" onchange="dashboard.changeCustomerChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                                        if ($type == 'customer') {
                                            echo 'style="display:inline-block"';
                                        } else {
                                            echo 'style="display:none"';
                                        }
                                        ?>>
                                                    <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('customer'); ?>
                                                    <?php if ($reportTypes): ?>
                                                        <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                                                    if ($key == $report_code) {
                                                        echo 'selected';
                                                    }
                                                    ?>><?php echo $this->__($value['name']) ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif ?>
                                        </select>

                                    </td>
                                </tr>  
                                <tr>
                                    <td class="label">
                                        <label for="chart_name"><?php echo $this->__('Chart Type') ?></label>                                              
                                    </td>
                                    <td class="value">
                                        <div id="select_chart_type"></div>                                             
                                        <div id="default_chart_type">
                                            <?php echo Mage::helper('inventorydashboard')->getDefaultChartType($item->getChartCode(), $item->getReportCode()); ?>
                                        </div>
                                    </td>
                                </tr>                                    
                                <tr>
                                    <td class="label"></td>
                                    <td class="value">
                                        <button type="button" class="scalable save" onclick="dashboard.submitEditChartForm();" style="float:left; margin-right: 14px;" class="" value="Save">
                                            <span><?php echo $this->__('Save') ?></span>
                                        </button>
                                        <button class="scalable" onclick="dashboard.cancelEditChartForm();
                                                    return false;">
                                            <?php echo $this->__('Cancel') ?>
                                        </button>                                            
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>            

                <!--
                <div class="field-table" style="background-color: #efefef;">
                    <div style="padding-left:100px;">
                        <ul class="field-row">
                            <label style="width:210px;font-size: 15px;"></label>
                            <h3><?php echo $this->__('Edit chart %s', $item->getName()) ?></h3>
                        </ul>
                        <br/>
                        <ul class="field-row clear">
                            <li>
                                <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Chart name') ?>&nbsp;<span class="required">*</span></label>
                            </li>
                            <li>
                                <input class="required-entry input-text required-entry" type="text" value="<?php echo $item->getName() ?>" style="width:410px;" name="chart_name" maxlength="50" id="chart_name" />
                            </li>
                        </ul>
                        <br/>
                        <ul class="field-row clear">
                            <li>
                                <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Report Type') ?>&nbsp;<span class="required">*</span></label>
                            </li>
                            <li>
                                <select name="group_type" id="group_type" onchange="return dashboard.changeSelectGroupTypeEdit(this);" class="required-entry required-entry select">
                <?php $groupTypes = Mage::helper('inventorydashboard')->getGroupType(); ?>
                <?php if ($groupTypes): ?>
                    <?php foreach ($groupTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php if ($key == $type) echo 'selected'; ?>><?php echo $this->__($value['title']) ?></option>
                    <?php endforeach; ?>
                <?php endif ?>
                                </select>
                            </li>
                        </ul>
                        <ul class="field-row clear">
                            <li>
                                <select name="sales_report_edit" id="sales_report_edit" onchange="dashboard.changeSalesChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="required-entry required-entry select" <?php
                if ($type == 'sales') {
                    echo 'style="display:inline-block"';
                } else {
                    echo 'style="display:none"';
                }
                ?>>
                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('sales'); ?>
                <?php if ($reportTypes): ?>
                    <?php $option_selected = 1; ?>
                    <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php if ($option_selected == 1 || $key == $report_code) echo 'selected' ?>><?php echo $this->__($value['name']) ?></option>
                        <?php $option_selected++ ?>
                    <?php
                    endforeach;
                    unset($option_selected);
                    ?>
    <?php endif ?>
                                </select>
                                <select name="purchaseorder_report_edit" id="purchaseorder_report_edit" onchange="dashboard.changePurchaseorderChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                if ($type == 'purchaseorder') {
                    echo 'style="display:inline-block"';
                } else {
                    echo 'style="display:none"';
                }
                ?>>
                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('purchaseorder'); ?>
                <?php if ($reportTypes): ?>
                    <?php ?>
                    <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                        if ($key == $report_code) {
                            echo 'selected';
                        }
                        ?>><?php echo $this->__($value['name']) ?></option>
                    <?php endforeach; ?>
    <?php endif ?>
                                </select>
                                <select name="stockonhand_report_edit" id="stockonhand_report_edit" onchange="dashboard.changeStockonhandChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                if ($type == 'stockonhand') {
                    echo 'style="display:inline-block"';
                } else {
                    echo 'style="display:none"';
                }
                ?>>
                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('stockonhand'); ?>
                <?php if ($reportTypes): ?>
                    <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                        if ($key == $report_code) {
                            echo 'selected';
                        }
                        ?>><?php echo $this->__($value['name']) ?></option>
                    <?php endforeach; ?>
    <?php endif ?>
                                </select>
                                <select name="stockmovement_report_edit" id="stockmovement_report_edit" onchange="dashboard.changeStockmovementChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                if ($type == 'stockmovement') {
                    echo 'style="display:inline-block"';
                } else {
                    echo 'style="display:none"';
                }
                ?>>
                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('stockmovement'); ?>
                <?php if ($reportTypes): ?>
                    <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                        if ($key == $report_code) {
                            echo 'selected';
                        }
                        ?>><?php echo $this->__($value['name']) ?></option>
                    <?php endforeach; ?>
    <?php endif ?>
                                </select>
                                <select name="customer_report_edit" id="customer_report_edit" onchange="dashboard.changeCustomerChartTypeEdit('<?php echo $this->getUrl('adminhtml/ind_dashboard/changecharttype', array('_secure' => true)) ?>');" class="" <?php
                if ($type == 'customer') {
                    echo 'style="display:inline-block"';
                } else {
                    echo 'style="display:none"';
                }
                ?>>
                <?php $reportTypes = Mage::helper('inventorydashboard')->getReportType('customer'); ?>
                <?php if ($reportTypes): ?>
                    <?php foreach ($reportTypes as $key => $value): ?>
                                                    <option value="<?php echo $key ?>" <?php
                        if ($key == $report_code) {
                            echo 'selected';
                        }
                        ?>><?php echo $this->__($value['name']) ?></option>
                    <?php endforeach; ?>
    <?php endif ?>
                                </select>

                            </li>
                        </ul>
                        <ul class="field-row clear">
                            <li>
                                <select name="attribute_sales_report_edit" id="attribute_sales_report_edit" onchange="" class="" style="display:none">
                <?php
                $report = Mage::getModel('inventoryreports/reporttype');
                $attributes = $report->getOrderAttributeOptions();
                ?>
                <?php if ($attributes): ?>
                    <?php foreach ($attributes as $key => $attribute): ?>
                                                    <option value="<?php echo $key ?>"><?php echo $this->__($attribute) ?></option>
                    <?php endforeach; ?>
    <?php endif ?>
                                </select>
                            </li>
                        </ul>
                        <br/>
                        <ul class="field-row clear">
                            <li>
                                <label for="chartName" style="font-size: 15px;"><?php echo $this->__('Chart Type') ?>&nbsp;<span class="required">*</span></label>
                            </li>
                            <li>
                                <ul id="select_chart_type_edit">
    <?php echo $this->__('Please select a report type first.') ?>
                                </ul>                    
                            </li>
                            <div id="default_chart_type_edit">
                                <li>
    <?php echo Mage::helper('inventorydashboard')->getDefaultChartType($item->getChartCode(), $item->getReportCode()); ?>
                                </li>
                            </div>
                        </ul>
                        <br/>
                        <ul class="submit-row clear">
                            <label></label>
                            <li>
                                <button type="button" onclick="dashboard.submitEditChartForm();" style="width:80px;height:32px;float:left; margin-right: 14px;" class="" value="Add">
                                    <span><?php echo $this->__('Save') ?></span>
                                </button>
                                <a class="button-grey cancel" onclick="dashboard.cancelEditChartForm();
                                            return false;"><?php echo $this->__('Cancel') ?></a>
                            </li>
                        </ul>

                    </div>
                </div>
                -->
        </form>
    </div>
    <?php
 endif ?>