<div class="box" id="dashboard_diagram_totals">
    <div class="entry-edit">
        <table cellspacing="0" width="100%">
            <tr>
				<td class="a-center bold">
                    <span>Total Listed Items</span><br />
                    <span class="nowrap" style="font-size:18px; color:#EA7601;"><a href='<?php echo Mage::helper('adminhtml')->getUrl('items/adminhtml_itemlisting/'); ?>'><?php echo $this->getData('totallisted'); ?></a></span>
                </td>
             	<td class="a-center bold">
                    <span>Total Published Items</span><br />
                    <span class="nowrap" style="font-size:18px; color:#EA7601;"><a href='<?php echo Mage::helper('adminhtml')->getUrl('items/adminhtml_itempublishing/'); ?>'><?php echo $this->getData('totalPublished'); ?></a></span>
                </td>
				 <!--td class="a-center bold">
                    <span>Total UnPublished Items</span><br />
                    <span class="nowrap" style="font-size:18px; color:#EA7601;"><a href='<?php echo Mage::helper('adminhtml')->getUrl('items/adminhtml_itempublishing/'); ?>'><?php echo $this->getData('totalUnPublished'); ?></a></span>
                </td-->
            </tr>
        </table>
    </div>
</div>

