<?php 
    //todo: move logic to the block
    list($min,$max) = $this->_filter->getMinMaxPriceInt(); 
    list($from,$to) = explode(',', $this->_filter->getActiveState()); 
    
    $from = floor(max($from, $min));
    
    if ($to) {
        $to   = ceil(min($to, $max));		
    } else {
        $to = $max;
    }
    
    if ($to<1 && $from<1) {
        $to = $max;
    }

	//Set the slider width
    $width = 170;
    
    if ($max) {
        if ($max == $min) {
            $firstOffset = 0;
            $secondOffset = $width;
        } else  {
			$firstOffset  = ($from-$min)*$width/($max-$min);
			$secondOffset = ($to-$min)*$width/($max-$min);
        }
    } else  {
			$firstOffset  = 0;
			$secondOffset = 0;
    }
?>

<!-- jquery slider price range -->
<ol>
<li style="padding:10px;">
<div id="slider-range" style="margin-bottom:10px;"></div>
   <input type="hidden" id="searchid" value="<?php echo $_REQUEST['q'] ?>">

<p style="clear:both; width:100%; margin: 10px 0 10px -10px; display:none;">
	<label for="mullnav_rng" style="float:left; width:37%;padding:4px;">Price range:</label>
	<input type="text" id="mullnav_rng" readonly style="border:0; font-weight:bold; background-color:#ffffff; float:left; width:60%;">
</p>
</li>
</ol>
<!-- jquery slider price range -->

<ol>
<?php 
	
	$from_chweb = $from;
	$to_chweb = $to;

    $items = $this->getItems(); 
    list($from, $to) = explode(',', $items[0]->getValueString());
   
    if ($from < 0.01) {
        $from = $this->__('From');
    } else  {
        $from = round($from);    
    }
       
    if ($to < 0.01) {
        $to = $this->__('To');
    } else {
        $to = round($to);    
    }
    
?><?php $currency_code = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();?>
<li class="mullayenav_range_input"><span class="mullayenav_range_dash"><?php echo $currency_code; ?></span>
<input class="input-text mullayenav_range_from" type="text" maxlength="12" size="4" id="price_range_from---<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $from_chweb; ?>"
onclick="if(this.value==this.name) this.value='';"  name="<?php echo $this->__('From')?>" style="background-color:#ffffff !important;"/>
<span class="mullayenav_range_dash">-<?php echo $currency_code; ?></span>
<input class="input-text mullayenav_range_to" type="text" maxlength="12" size="4" id="price_range_to---<?php echo $this->_filter->getRequestVar()?>" value="<?php echo $to_chweb?>"
onclick="if(this.value==this.name) this.value='';" name="<?php echo $this->__('To')?>" style="background-color:#ffffff !important;"/>
<button type="button" class="button mullayenav_range_btn" id="price_button_go---<?php echo $this->_filter->getRequestVar()?>"><span><?php echo $this->__('Go')?></span></button>
</li>
</ol>
<input type="hidden" value="<?php echo $this->_filter->getRequestVar()?>" class="price-input">





<script>
jQuery(document).ready(function() {
  		jQuery( "#slider-range" ).slider({
			range: true,
			min: <?php echo $min; ?>,
			max: <?php echo $max; ?>,
			values: [ <?php echo $from_chweb; ?>, <?php echo $to_chweb; ?> ],
			slide: function( event, ui ) {
			jQuery( "#price_range_from---price" ).val( ui.values[ 0 ] );
				jQuery( "#price_range_to---price" ).val( ui.values[ 1 ] );	
	jQuery( "#mullnav_rng" ).val( "<?php echo $currency_code; ?>" + ui.values[ 0 ] + " - <?php echo $currency_code; ?>" + ui.values[ 1 ] );
				
			},
			 stop: function(a, ui) {				 
				jQuery( "#price_range_from---price" ).val( ui.values[ 0 ] );
				jQuery( "#price_range_to---price" ).val( ui.values[ 1 ] );	
	jQuery( "#mullnav_rng" ).val( "<?php echo $currency_code; ?>" + ui.values[ 0 ] + " - <?php echo $currency_code; ?>" + ui.values[ 1 ] );
				
				 mullnav_rng();
				 
			 }		});
		jQuery( "#mullnav_rng" ).val( "<?php echo $currency_code; ?>" + jQuery( "#slider-range" ).slider( "values", 0 ) +
			" - <?php echo $currency_code; ?>" + jQuery( "#slider-range" ).slider( "values", 1 ) );
	});
	//window.StartSlider();
	function mullnav_rng()
	{
		var mullnav_amount = document.getElementById('mullnav_rng').value;
		mullnav_amount = mullnav_amount.replace("<?php echo $currency_code; ?>", "");
		mullnav_amount = mullnav_amount.replace("<?php echo $currency_code; ?>", "");		
		mullnav_amount = mullnav_amount.split(" - ");
		mullnav_from_amount = mullnav_amount['0'];
		mullnav_to_amount = mullnav_amount['1'];
		if(document.getElementById('searchid').value!='')
		{
		document.getElementById('chweb_layered_params').value ="q="+document.getElementById('searchid').value+ "&price="+mullnav_from_amount+"%2C"+mullnav_to_amount;
		}else{
			
		document.getElementById('chweb_layered_params').value = "price="+mullnav_from_amount+"%2C"+mullnav_to_amount;

		}
		chweb_layered_make_request();
		//alert(mullnav_from_amount);
		//alert(mullnav_to_amount);
	}
	
</script>

