<?php 
$items= $this->getFiltersArray();
$displayStyle = $this->getColumnsNum(); 
?><div class="jspContainer">
 <ul  class="list custom-checkboxes filter_<?php echo $this->__($this->getVar()) ?>">

<?php if ($displayStyle <=1): // one column
$i=0; ?>
    <?php foreach ($items as $_item): ?>
	<li id="filter_<?php echo $this->getVar()?>Option_<?php  echo $i++?>" class="srch_ctgry_item">
        <?php echo $_item?></li>
    <?php endforeach ?>
<?php endif ?>
</ul>
</div>