<?php if ($this->isActive()): ?>
    <script type="text/javascript">
	//console.log(thisinfinitescroll);
        //<![CDATA[
            var thisinfinitescroll = new infinitescroll();
            thisinfinitescroll.shouldload = <?php echo $this->shouldLoad() ? 'true' : 'false'; ?>;
            thisinfinitescroll.nextpage = 2;
            thisinfinitescroll.lastpage = <?php echo $this->getLastPage(); ?>;
            thisinfinitescroll.mode = "<?php echo $this->getMode(); ?>";
        //]]>
    </script>
	<script type="text/javascript" src="<?php  echo Mage::getBaseUrl()?>skin/frontend/base/default/js/chweb/chweb_layered_nav.js"></script>
<?php endif; ?>