<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Rolepermissions
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category Access') ?></h4>
    </div>

    <fieldset id="grop_fields">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label for="amrolepermissions[categories_access_mode]"><?php echo $this->__('Allow access to')?></label></td>
                <td class="value">
                    <?php echo $this->getSelect()->toHtml()?>
                </td>
            </tr>
            </tbody>
        </table>
        <div>
            <input type="hidden" name="category_ids" id="product_categories" value="<?php echo $this->getIdsString() ?>">
            <div id="product-categories" class="tree"></div>
        </div>
    </fieldset>

</div>
<?php if($this->getRootNode() && $this->getRootNode()->hasChildren()): ?>
    <script type="text/javascript">
        Ext.EventManager.onDocumentReady(function() {

            new FormElementDependenceController({"product-categories":{"amrolepermissions[categories_access_mode]":1}}, {levels_up: 0});

            var categoryLoader = new Ext.tree.TreeLoader({
                dataUrl: '<?php echo $this->getLoadTreeUrl()?>'
            });

            categoryLoader.createNode = function(config) {
                config.uiProvider = Ext.tree.CheckboxNodeUI;
                var node;
                if (config.children && !config.children.length) {
                    delete(config.children);
                    node = new Ext.tree.AsyncTreeNode(config);

                } else {
                    node = new Ext.tree.TreeNode(config);
                }
                return node;
            };

            categoryLoader.on("beforeload", function(treeLoader, node) {
                treeLoader.baseParams.category = node.attributes.id;
            });

            categoryLoader.on("load", function(treeLoader, node, config) {
                varienWindowOnload();
            });

            var tree = new Ext.tree.TreePanel('product-categories', {
                animate:true,
                loader: categoryLoader,
                enableDD:false,
                containerScroll: true,
                rootUIProvider: Ext.tree.CheckboxNodeUI,
                selModel: new Ext.tree.CheckNodeMultiSelectionModel(),
                rootVisible: '<?php echo $this->getRootNode()->getIsVisible() ?>'
            });

            tree.on('check', function(node) {
                var status = false;
                if(node.attributes.checked) {
                    categoryAdd(node.id);
                    status = true;
                } else {
                    categoryRemove(node.id);
                }
                check(node, status);
                varienElementMethods.setHasChanges(node.getUI().checkbox);
            }, tree);

            // set the root node
            var root = new Ext.tree.TreeNode({
                text: '<?php echo $this->jsQuoteEscape($this->getRootNode()->getName()) ?>',
                draggable:false,
                checked:'<?php echo $this->getRootNode()->getChecked() ?>',
                id:'<?php echo $this->getRootNode()->getId() ?>',
                disabled: <?php echo ($this->getRootNode()->getDisabled() ? 'true' : 'false') ?>,
                uiProvider: Ext.tree.CheckboxNodeUI
            });

            tree.setRootNode(root);
            bildCategoryTree(root, <?php echo $this->getTreeJson() ?>);
            tree.addListener('click', categoryClick.createDelegate(this));

            // render the tree
            tree.render();
            root.expand();
            tree.expandAll();
        });

        function check(node, status) {
            var cs = node.childNodes;
            checkParent(node, status);
            for(var i = 0; i < cs.length; i++) {
                cs[i].getUI().check(status, true, true);
                check(cs[i], status);
            }
        }

        function checkParent(node, status) {
            if (node.attributes.checked && status == true) {
                categoryAdd(node.id);
            } else {
                categoryRemove(node.id);
            }
            var parentNode = node.parentNode;
            if( parentNode.getUI().check ) {
                parentNode.getUI().check(status, false, true);
                checkParent(parentNode, status);
            }
        }

        function bildCategoryTree(parent, config){
            if (!config) return null;

            if (parent && config && config.length){
                for (var i = 0; i < config.length; i++){
                    config[i].uiProvider = Ext.tree.CheckboxNodeUI;
                    var node;
                    var _node = Object.clone(config[i]);
                    if (_node.children && !_node.children.length) {
                        delete(_node.children);
                        node = new Ext.tree.AsyncTreeNode(_node);

                    } else {
                        node = new Ext.tree.TreeNode(config[i]);
                    }
                    parent.appendChild(node);
                    node.loader = node.getOwnerTree().loader;
                    if(config[i].children){
                        bildCategoryTree(node, config[i].children);
                    }
                }
            }
        }

        function categoryClick(node, e){
            if (node.disabled) {
                return;
            }
            node.getUI().check(!node.getUI().checked());
            varienElementMethods.setHasChanges(Event.element(e), e);
        };
        function categoryAdd(id) {
            var ids = $('product_categories').value.split(',');
            ids.push(id);
            $('product_categories').value = ids.join(',');
        }
        function categoryRemove(id) {
            var ids = $('product_categories').value.split(',');
            // bug #7654 fixed
            while (-1 != ids.indexOf(id)) {
                ids.splice(ids.indexOf(id), 1);
            }
            $('product_categories').value = ids.join(',');
        }
    </script>
<?php endif; ?>
