<?php
$_product = $this->getProduct();
?>
<?php if (($_product->getRatingSummary()->getReviewsCount())
         && ($_product->getRatingSummary()->getRatingSummary() != 0)): ?>
   <div xmlns:v="http://rdf.data-vocabulary.org/#" typeof="v:Review-aggregate" class="review-aggregate-hide">
   <span property="v:itemreviewed"><?php echo $this->escapeHtml($_product->getName())?></span>
   <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')?>" rel="v:photo" />
   <span rel="v:rating">
      <span typeof="v:Rating">
         <span property="v:average"><?php echo round(($_product->getRatingSummary()->getRatingSummary()/100)*5,1);//ceil($_product->getRatingSummary()->getRatingSummary()/100*5)?></span>
         out of
         <span property="v:worst">1</span>
         <span property="v:best">5</span>
      </span>
   </span>
   based on
   <span property="v:reviews"><?php echo  $_product->getRatingSummary()->getReviewsCount()?></span> ratings.
   <span property="v:count"><?php echo  $_product->getRatingSummary()->getReviewsCount()?></span> user reviews.
</div>
<?php endif; ?>

<?php if ($_product->getRatingSummary()->getReviewsCount()): ?>
   <?php $_reviews = $this->getReviews();?>
   <div xmlns:v="http://rdf.data-vocabulary.org/#" typeof="v:Review" class="review-aggregate-hide">
       <dl>
       <?php foreach ($_reviews as $_review):?>
          <dt>
             <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><span property="v:itemreviewed"><?php echo $this->htmlEscape($_review->getTitle()) ?></span></a> <?php echo $this->__('Review by <span property="v:reviewer">%s</span>', $this->htmlEscape($_review->getNickname())) ?>
          </dt>
          <dd>
             <?php $_votes = $_review->getRatingVotes(); ?>
             <?php if (count($_votes)): ?>
             <table class="ratings-table">
                <col width="1" />
                <col />
                <tbody>
                   <?php foreach ($_votes as $_vote): ?>
                   <tr>
                      <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                      <td>
                         <div class="rating-box">
                            <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                         </div>
                      </td>
                   </tr>
                   <?php endforeach; ?>
                </tbody>
             </table>
             <?php endif; ?>
             <span property="v:description">
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
             </span>
             <small class="date"><?php echo $this->__('(Posted on <span property="v:dtreviewed" content="%s">%s</span>)', $_review->getCreatedAt(), $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
          </dd>
       <?php endforeach; ?>
       </dl>
   </div>
<?php endif; ?>