<?php $_product = $this->getProduct();?>
<?php $_vendor	= $this->getVendor();?>
<td>
	<div style="position: relative;">
		<img class="pricecomparison-logo" src="<?php echo $this->getImageUrl($_vendor->getLogo())?>" style="float: left; margin-right: 5px;" width="<?php echo $this->getLogoWidth()?>" height="<?php echo $this->getLogoHeight();?>" />
		<?php if($productUrl = $this->getVendorProductUrl($_product)):?>
		  <a target="_blank" href="<?php echo $productUrl?>"><?php echo $_vendor->getTitle()?></a>
		<?php else:?>
		  <strong><?php echo $_vendor->getTitle()?></strong>
		<?php endif;?>
		<p><?php echo $this->formatDescription($_product->getShortDescription())?></p>
		<?php if($_product->isSaleable()): ?>
            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
        <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>
		<?php if($_vendor->getId() == Mage::getSingleton('vendors/session')->getVendor()->getId()):?>
			<div class="remove-link"><a href="javascript: void(0);" onclick="Comparison.deleteItem(<?php echo $_product->getId() ?>,<?php echo Mage::registry('current_product')->getId()?>)"><?php echo $this->__('Remove your product')?></a></div>
		<?php endif;?>
	</div>
</td>