<?php
/**
 * Link to get Widget Code Product page
 */
?>

<div class="affiliatepluswidget_code">
	<?php echo $this->__('Copy and paste the HTML code onto your webpage.') ?><br />
	<textarea class= "widgets-code" width="283" height="225"onclick="this.select()" readonly cols="65" rows="11"><?php echo $this->getHtmlCode() ?></textarea>
</div>

<div class="buttons-set" style="margin-top:18px;">
	<a href="<?php echo $this->getCustomizeUrl() ?>" title="<?php echo $this->__('Preview Widget') ?>" target="_blank" style="text-decoration:none;">
		<button type="button" class="button button-config">
			<span>
				<span><?php echo $this->__('Preview Widget') ?></span>
			</span>
		</button>
	</a>
</div>
