<?php
/**
 * 
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="mage-iphone'.$this->getBodyClass().'"':'' ?> home="index.php" onload="setTimeout(scrollTo, 0, 0, 1)">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<div data-role="page">
    <div class="header">
        <div class="row">
            <?php echo $this->getChildHtml('header') ?>
        </div>
    </div>

    <div class="middle-container">
        <div class="middle col-1-layout">
            <?php // echo $this->getChildHtml('breadcrumbs') ?>
            <div class="clear"></div>
            <div id="main" class="col-main">
                <div <?php echo $this->getBodyClass()?' class="mage-iphone'.$this->getBodyClass().'"':'' ?>>
                    <?php //if($sliderpowerhome == '1') : ?>
                        <?php echo $this->getChildHtml('hybrid_content_slider') ?>
                    <?php //endif; ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
