<script type="text/javascript">
    function checksubcat(storeId) {
		var selectCats = document.getElementById("mlitems_categoriesupdateinformation_mlrootcategories");
		var selectedCats = [];
		var selectedCatIds = '';
		for (var i = 0; i < selectCats.length; i++) {
			if (selectCats.options[i].selected){ 
					selectedCats.push(selectCats.options[i].value);
				}
		}
		selectedCatIds = selectedCats.join(",");
		new Ajax.Request('<?php echo $this->getAjaxCheckUrl()?>catids/'+ selectedCatIds +'/storeId/'+storeId, {
            method:     'get',
			data:     'test',
            onSuccess: function(transport){
			if (transport.responseText){
                if(transport.responseText == 1){
					document.getElementById('subcatnotimported').style.display = "none";
					document.getElementById('subcatimported').style.display = "block";
				}else if(transport.responseText == 0){
					document.getElementById('subcatimported').style.display = "none";
					document.getElementById('subcatnotimported').style.display = "block";
				}
            }
            }
        });
    }
</script>

<?php echo $this->getButtonHtml() ?>
<div id="subcatimported" style="display:none; float:right" ><img src="<?php echo Mage::getBaseUrl('media'); ?>mercadolibre/CheckIcon.png" title="Successfully Done" />
</div>
<div id="subcatnotimported" style="display:none; float:right" ><img src="<?php echo Mage::getBaseUrl('media'); ?>mercadolibre/incorrect.png" title="Try Again" /></div>
