<?php   
/*------------------------------------------------------------------------
 # Ves Blog Module 
 # ------------------------------------------------------------------------
 # author:    Ves.Com
 # copyright: Copyright (C) 2012 http://www.ves.com. All Rights Reserved.
 # @license: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 # Websites: http://www.ves.com
 # Technical Support:  http://www.ves.com/
-------------------------------------------------------------------------*/
	
		
	
	$leadingCols = 	(int)$this->getListConfig("list_leadingcols");
	$leadingItems = (int)$this->getListConfig("list_leadinglimit");	
	
	
	$secondItems = (int)$this->getListConfig("list_secondlimit");		
	$secondCols = (int)$this->getListConfig("list_secondcols");	
	$childheight = $this->getCategoryConfig("chidlrentheight");
	$childheight = (trim($childheight) == 'auto')?'auto':(int)$childheight."px";
	$cols = (int)$this->getCategoryConfig("chidlrentcols");

	$layout_mode = $this->getLayoutMode();
	
 ?>
<div class="blog-list blogs-second">
	<div class="blog-wrapper">
	
		<div class="page-title hidden">
			<h1><?php echo $this->getPageTitle(); ?></h1>
		</div>
		
		<?php  if( $this->getType() == 'category' && $category = $this->getCategory() ) : ?>	
		<?php if( $this->getCategoryConfig("show_childrent") && ($childrent = $this->getChildrent()) && count($childrent) ): ?>
			<div class="blog-childrent vesclear">
				<h3><?php echo $this->__("Childrent"); ?></h3>
				
				<div class="childrent-wrapper colswrapper cols<?php echo $cols;?>">
					<?php $i=0; foreach( $childrent as $sub ): ?>
						<?php $class=""; 
							if( $i%$cols==0 ){
								$class .="itemlast";
							}
						?>
						<div class="childrent-item itemcol <?php echo $class;?>" style="height:<?php echo $childheight;?>">
							<h2>
							<a href="<?php echo $sub->getCategoryLink();?>" title="<?php echo $category->getTitle();?>"><?php echo $sub->getTitle(); ?></a> 
							
							(<?php echo $this->countPosts( $sub->getId() ); ?>)</h2>
							
							<a href="<?php echo $sub->getCategoryLink(); ?>">
								<img src="<?php echo $sub->getImageURL('l');?>"/>
							</a>
							<div class="ves-description">
								<?php echo $sub->getDescription(); ?>
							</div>
							<div class="sub-viewblogs">
								<a href="<?php echo $sub->getCategoryLink();?>" title="<?php echo $category->getTitle();?>"><?php echo $this->__("View Posts"); ?></a>
							</div>
						</div>
					<?php $i++; endforeach; ?>
				</div>
			</div>
			<?php endif ; ?>
		<?php endif; ?>
		
		<?php if( ($posts = $this->getPosts()) && count($posts) ): ?>
			<div class="posts-list">
			<?php
			$i =0;$j=0;
			$_collectionSize = count($posts);
			$_columnCount = 1;
			foreach( $posts as $post ):
			$i++;
			?>

            <div class="row blogs-row _item<?php if($i==1): ?>first<?php elseif($i == $_collectionSize): ?> last<?php endif; ?>">
			  	<div class="col-lg-<?php echo $second_image_col; ?> col-md-<?php echo $second_image_col; ?> col-sm-<?php echo $second_image_col; ?> col-xs-12">
			  	<?php if( $post->getFile() ): ?>
			    	<?php
			    		$image_info = $this->getPostImage($post, $layout_mode);
			    		$image_file = isset($image_info['url'])?$image_info['url']:"";
			    		$image_width = isset($image_info['width'])?$image_info['width']:"0";
			    		$image_height = isset($image_info['height'])?$image_info['height']:"0";
			    		$image_attribute = "";
			    		if($image_width) {
			    			$image_attribute .= ' width="'.$image_width.'"';
			    		}
			    		if($image_height) {
			    			$image_attribute .= ' height="'.$image_height.'"';
			    		}
			    		if($image_file):
			    	?>
						<div class="blog-image">
							<?php if($this->getListConfig("list_showcreated")) { ?>
							<span class="created-date">
								<?php $_ct= new Zend_Date( $post->getCreated()); ?>
								<span class="day"><?php echo $_ct->toString('dd');?></span> <br/>
						        <span class="month"><?php echo $_ct->toString('MMM');?>  </span> 
						        <!-- <span class="year"><?php echo $_ct->toString('YYY');?></span> -->
							</span>	
							<?php } ?>

							<a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
								<img src="<?php echo $image_file;?>" <?php echo $image_attribute; ?> alt="<?php echo $post->getTitle();?>"/>
							</a>
						</div>
						<?php endif; ?>
				<?php endif; ?>
				</div>

				<div class="col-lg-<?php echo $second_content_col; ?> col-md-<?php echo $second_content_col; ?> col-sm-<?php echo $second_content_col; ?> col-xs-12">
					<div class="blog-meta-block">
								<h3 class="blog-title"><a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>"><?php echo $post->getTitle(); ?></a></h3>

								<div class="blog-meta">
									
									<?php if( $this->getType() !="category" && $this->getListConfig("list_category_title") ): ?>		
									<span class="blog-category">
										<!-- <span><?php echo $this->__("Pubslished In");?></span>  -->
										<a href="<?php echo $post->getCategoryLink();?>" title="<?php echo $post->getCatTitle();?>"> 
											<i class="fa fa-bookmark"></i> <?php echo $post->getCatTitle();?>
										</a> |
									</span>
									<?php endif; ?>

									<?php if($this->getListConfig("list_show_hits")) { ?>
									<span class="blog-hits"><span><?php echo $this->__("Read");?></span> <strong><?php echo $post->getHits(); ?></strong> <?php echo $this->__("Times"); ?></span>
									<?php } ?>

									<?php if($this->getListConfig("list_show_commentcouter")) { ?>
									<span class="blog-comment-count"> <i class="fa fa-comment"></i> <?php echo $this->getCountingComment($post->getId());?> <?php  echo $this->__("Comment");?></span>
									<?php } ?>
								</div>

								<div class="ves-description">
										<?php echo $post->getDescription(); ?>
										<p class="blog-readmore"><a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
											<?php echo $this->__("Read more > ");?>
										</a></p>
								</div>

								<div class="blog-bottom hidden">
									<?php if( $tags = $post->getTags() ) :$tags = explode( ",",$tags );	?>
									<div class="blog-tags">
										<span><?php echo $this->__("Tags :");?> </span>
										<?php foreach( $tags as $tag ): ?>
										<a href="<?php echo Mage::helper('ves_blog')->getTagUrl(trim($tag));?>" title="<?php echo $tag;?>"><span><?php echo $tag; ?><span></a>, 
										<?php endforeach; ?>
									</div>
									<?php endif; ?>
									
								</div>
					</div>
				</div>
            </div>
			<?php endforeach; ?>
		</div>
			
		<?php elseif( count($posts) <= 0 ): ?>
			<div class="ves-message">
				<?php echo $this->__( "We are updating data, please come back in near time!!!" ); ?>
			</div>
		<?php endif; ?>
		
	</div>
	<?php echo $this->getChildHtml('list.toolbar'); ?>
</div>
