<script type="text/javascript">
    function check(storeId) {
		var clientID = document.getElementById("mlitems_mltokenaccess_mltokenclientid").value;
		var clientSecret = document.getElementById('mlitems_mltokenaccess_mltokenclientsecret').value;
		new Ajax.Request('<?php echo $this->getAjaxCheckUrl().'clientID/'?>'+clientID+'/clientSecret/'+clientSecret+'/store/'+storeId, {
            method:     'get',
			data:     'test',
            onSuccess: function(transport){
			if (transport.responseText){
                if(transport.responseText == 1){
					document.getElementById('AppKeyNotFound').style.display = "none";
					document.getElementById('AppKeyFound').style.display = "block";
				}else if(transport.responseText == 0){
					document.getElementById('AppKeyFound').style.display = "none";
					document.getElementById('AppKeyNotFound').style.display = "block";
				}
            }
            }
        });
    }
</script>

<?php echo $this->getButtonHtml() ?>
<div id="AppKeyFound" style="display:none; float:right" ><img src="<?php echo Mage::getBaseUrl('media'); ?>mercadolibre/CheckIcon.png" title="Correct Credentials" />
</div>
<div id="AppKeyNotFound" style="display:none; float:right" ><img src="<?php echo Mage::getBaseUrl('media'); ?>mercadolibre/incorrect.png" title="Wrong Credentials" /></div>
