<?php 
	$modid=rand();
?>
<div class="ves-blog-archives block">
	 <div class="block-title">
        <strong>
            <span><?php echo $this->__('Blog Archives') ?></span>
        </strong>
    </div>
	<div class="block-content">
	<?php if( count($posts) ): ?>
		<ul id="blog-archives<?php echo $modid; ?>">
		<?php foreach( $posts as $year=>$post ): ?>
			<li class="level1 parent blog-archive">
				<a href="<?php echo Mage::helper("ves_blog")->getArchiveUrl($year);?>" title="<?php echo $year; ?>"><span><?php echo $year;?></span></a>
				<?php
					if(count($post)):
						?>
					<span class="head"><a href="javascript:void(0);" class="open_collapse"><i class="fa fa-plus-circle"></i></a></span>
					<ul class="list-level2 collapse">
					<?php foreach($post as $k=>$month): ?>
						<li class="level2"><a href="<?php echo Mage::helper("ves_blog")->getArchiveUrl($year."_".$month['month']);?>" title="<?php echo $month['month_name']; ?>"><span><?php echo $month['month_name'].' ('.$month['total'].')';?></span></a></li>
					<?php endforeach; ?>
					</ul>
					<?php
					endif;
				?>
			</li>
		<?php endforeach; ?>
		</ul>
		<script type="text/javascript">
					$jmenu(document).ready(function(){	
						// applying the settings
						var c = 0;
						$jmenu('#blog-archives<?php echo $modid; ?> a.open_collapse').on('click',function(e){
							e.preventDefault();
							var $this = jQuery(this);
							var $collapse = $this.closest('.blog-archive').find('.collapse');

							if($collapse.length > 0) {
								$collapse.collapse('toggle');
							} else {
								var $collapse = $this.closest('.blog-archive').find('.in');
								$collapse.collapse('toggle');
								$collapse.addClass("collapse");
							}

							if($this.data("clickEvent") == "open") {
								$this.data("clickEvent","close");
								$this.html('<i class="fa fa-plus-circle"></i>');
							} else {
								$this.data("clickEvent","open");
								$this.html('<i class="fa fa-minus-circle"></i>');
							}


						});
					});	
				</script>
	<?php endif; ?>
	</div>
</div>