<?php 
	$categories		= $this->getAllCategories() ;
	$catSuffix 		= $this->getCatSuffix();
	$urlKey			= $this->getUrlKey();
	$seller = Mage::registry("current_seller");
?>
	<div class="kbase-block kbase-main-category">
		<div class="kbase-block-content">
			<ul class="kbase-list level-0">
			<?php if(sizeof($categories) != 0){?>
			<?php foreach ($categories as $category):?>
				<?php
				$tmp = 1;
				$faqs = $this->getFaq($category->getData('category_id'));?>
				<?php if(sizeof($faqs)):?>
				<li>
					<h2 class="title"><span><?php echo $category->getData('title') ?></span></h2>
					
					<div class="content-faq-list">
						 <?php foreach ($faqs as $faq): ?>
						 <div class="content-faq">
							  <div class="accordion <?php if(!Mage::helper("advancedfaq")->getEnableAccordion()):?>accordion-open<?php endif; ?>" id="section<?php echo $faq->getId()?>"><span><?php echo $faq->getData('question') ?></span></div>
							  <div class="container">
						        <div class="content">
						           <div class="kbase-block-content">
												<div class="faq-answer">
												<?php echo $faq->getData('answer') ?>
												</div>	
											</div>
											<div class="clearer kbase-article-footer">
												<p class="article-date"><?php echo  Mage::getModel('core/date')->date('F j, Y',$faq->getData('created_time')); ?></p>
												<?php if($this->isEnableRating()):?>
													 <div id="rate_widget_<?php echo $faq->getId() ?>" class="rate_widget" rel="<?php echo $faq->getId() ?>">
												
													  </div>
												<?php endif;?>
									</div>
						        </div>
						   	  </div>
					   	  </div>
					   	  	<?php $tmp++ ; 
							if($tmp > Mage::helper("advancedfaq")->getArticlesPage()):?>
							<div class="readmore-faq">
								<a href="<?php echo  Mage::helper('sellerspage')->getUrl($seller,$urlKey."/".$category->getData('url_key').$catSuffix) ?>" class="readmore"><span><?php echo $this->__("Read More") ?></span></a>
							</div>
							<?php break; ?>
							<?php endif;?>
						 <?php endforeach;?>
					</div>
				</li>
				<?php endif;?>
			<?php endforeach;?>
			<?php }else{?>
					<li><p style="text-align:center;font-style:italic;"><?php echo $this->__("No Topic find yet!") ?></p></li>
			<?php }?>
			</ul>
		</div>
    </div>
    <script type="text/javascript">
    <?php if(Mage::helper("advancedfaq")->getEnableAccordion()): ?>
    	//$j = jQuery.noConflict();
    	$j(document).ready(function() {
	        //custom animation for open/close
	        $j.fn.slideFadeToggle = function(speed, easing, callback) {
	            return this.animate({opacity: 'toggle', height: 'toggle'}, speed, easing, callback);
	        };
	        $j('.accordion').accordion({
	            defaultOpen: 'section1',
	            cookieName: 'nav',
	            speed: '<?php echo Mage::helper("advancedfaq")->getSpeedAccordion() ?>',
	            bind : '<?php echo Mage::helper("advancedfaq")->getBindAccordion() ?>',
	            animateOpen: function (elem, opts) { //replace the standard slideUp with custom function
	                elem.next().stop(true, true).slideFadeToggle(opts.speed);
	            },
	            animateClose: function (elem, opts) { //replace the standard slideDown with custom function
	                elem.next().stop(true, true).slideFadeToggle(opts.speed);
	            }
	        });
		      });
    <?php endif; ?>

    <?php if($this->isEnableRating()):?>
	    $j.fn.raty.defaults.path = '<?php echo $this->getSkinUrl("images/otto_advancedfaq") ?>';
	    <?php foreach ($categories as $category):
	    $faqs = $this->getFaq($category->getData('category_id'));
	    ?>
	    <?php foreach ($faqs as $faq):?>
	   		 <?php if($this->canShowRatingForm($faq->getId())){ ?>
	       		 $j('#rate_widget_<?php echo $faq->getId() ?>').raty({score: <?php echo $faq->getData('rating') ?>});<?php }else{ ?>$j('#rate_widget_<?php echo $faq->getId() ?>').raty({readOnly: true,score: <?php echo $faq->getData('rating') ?>});
		     <?php } ?>
	    <?php endforeach;?>
	    <?php endforeach;?>
	    		 $j('.rate_widget img').bind('click', function() {
	 	              var star = this;
	 	              var widget = $j(this).parent();
	 				  var rating = $j(star).attr('alt');
	 				  var widget_id = widget.attr('rel');
	 	              $j.ajax({
	 	      		      url: '<?php echo $this->getUrlRatingAjax() ?>',
	 	      		      type: 'POST',
	 	      		      dataType: 'html',
	 	      		      data: "rating="+rating+"&id="+widget_id,
	 	      		      success : function(transport){
	 	  	      		    	//  $j(widget).find('.star_' + rating).prevAll().andSelf().addClass('ratings_vote');
	 	      		    		 $j('#rate_widget_'+widget_id).raty({readOnly: true, score: rating});
	 	      		       },
	 	      		   });
	 	          });
	<?php endif;?>
	</script>