<?php $_quote = $this->getQuote() ?>
<script type="text/javascript">
var SAVE_PROPOSAL_URL = '<?php echo $this->getSaveProposalUrl();?>';
var SAVE_ALL_PROPOSAL_URL = '<?php echo $this->getSaveAllProposalUrl();?>';
var UPDATE_DEFAULT_PROPOSAL_URL = '<?php echo $this->getSaveDefaultProposalUrl();?>';
var REMOVE_PROPOSAL_URL = '<?php echo $this->getRemoveProposalUrl();?>';
var REMOVE_QUOTE_ITEM_URL = '<?php echo $this->getRemoveQuoteItemUrl();?>';
var SEND_QUOTE_MESSAGE_URL = '<?php echo $this->getSendQuoteMessageUrl();?>';
var quotation = new Quotation(<?php echo $this->getDataJSON()?>);
var QUOTE_READONLY = <?php echo $this->canEditItems()?'true':'false';?>;
</script>

<?php echo $this->getChildHtml('search')?>
<?php if($this->canEditItems()):?>
<div style="float: right">
    <button id="show-search-product-btn" onclick="quotation.showSearchProductGrid();" class="scalable add" type="button"><span><span><span><?php echo $this->__('Add Products')?></span></span></span></button>
</div>
<?php endif;?>
<div style="clear:both;"></div>

<div class="grid np" id="vendorsquote-items">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables quote-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Comment with product') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th class="proposal"><span class="nobr"><?php echo $this->helper('sales')->__('Price Proposal') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Margin (GP)') ?></span></th>
                <th></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php if(sizeof($_items)):?>
        <?php $i=0;foreach ($_items as $_item):?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php $i ++;?>
            </tbody>
        <?php endforeach; ?>
        <?php else:?>
            <tbody>
                <tr><td colspan="7" class="no-item"><?php echo $this->__('No records found.')?></td></tr>
            </tbody>
        <?php endif;?>
    </table>
  </div>
</div>
