<?php $banner = $this->getBanner();?>
<?php if(!$banner):?>
	<?php echo $this->__("<!--Banner Not Found! -->")?>
<?php else:?>
	<?php if(!$this->getItems()) :?>
		<?php echo $this->__('Item not fould!');?>
	<?php else:?>
	<?php $random = rand(1111,9999)?>
		<script language="javascript" type="text/javascript" src="<?php echo $this->getSkinUrl('ves_bannermanager/js/jquery.js')?>"></script>
		<script language="javascript" type="text/javascript" src="<?php echo $this->getSkinUrl('ves_bannermanager/js/jquery.easing.js')?>"></script>
		<script language="javascript" type="text/javascript" src="<?php echo $this->getSkinUrl('ves_bannermanager/js/script.js')?>"></script>
		<script type="text/javascript">
		$ves_banner_<?php echo $random?> = jQuery.noConflict();
		$ves_banner_<?php echo $random?>(document).ready( function(){	
								
				$obj_<?php echo $random?> = $ves_banner_<?php echo $random?>('#lofslidecontent45_<?php echo $random?>').lofJSidernews( { 
														interval : <?php echo $banner->getDelay()?>,
													 	easing			: '<?php echo $banner->getEasing()?>',
														duration		: 1500,
														auto		 	: true,
														//maxItemDisplay  : 4,
														//navPosition     : 'horizontal', // horizontal
														//navigatorHeight : 32,
														//navigatorWidth  : 80,
														mainWidth		:<?php echo $banner->getWidth()?>
														} );
			});
		</script>
		
		<?php $now = Mage::getModel('core/date')->date('Y-m-d');?>
		<div id="lofslidecontent45_<?php echo $random?>" class="lof-slidecontent" style="width: <?php echo $banner->getWidth()?>px; height: <?php echo $banner->getHeight()?>px;">
			<div style="display: none;" class="preload"><div>&nbsp;</div></div>
			 <!-- MAIN CONTENT --> 
			  <div class="lof-main-outer" style="width:<?php echo ($banner->getWidth()-295)?>px;float:left;">
			  	<ul class="lof-main-wapper">
			  		<?php foreach($this->getItems() as $item):?>
			  		<?php if( ($item->getFromDate() && ($item->getFromDate() > $now)) || ($item->getToDate() && ($item->getToDate() < $now))) continue;?>
			  		<li>
			  			<?php if($item->getCustomHtml()):?>
			        		<div style="position:relative;width:<?php echo $banner->getWidth()-295?>px; height: <?php echo $banner->getHeight()?>px;color:#000;"><?php echo $item->getCustomHtml()?></div>
			        	<?php else:?>
			        		<img src="<?php echo Mage::helper('bannermanager/image')->init($item->getFilename())->resize($banner->getWidth(),$banner->getHeight())?>" title="<?php echo $item->getTitle()?>" alt="<?php echo $item->getTitle()?>" />
			        		<?php if($banner->getDisplayDescription()):?>            
			                 <div class="lof-main-item-desc">
								<h2><?php echo $item->getTitle()?></h2>
				                <p><?php echo $item->getDescription()?>
				                	<a class="readmore" href="<?php echo $this->getItemUrl($item)?>">Read more</a>
				                </p>
			             	</div>
			             	<?php endif;?>
			             <?php endif;?>
			        </li>
			        <?php endforeach;?>
			      </ul>  	
			  </div>
			  <!-- END MAIN CONTENT --> 
			    <!-- NAVIGATOR -->
			      <div class="lof-navigator-outer lof-navigator-outer-2">
			            <ul class="lof-navigator">
			            	<?php foreach($this->getItems() as $item):?>
			  				<?php if( ($item->getFromDate() && ($item->getFromDate() > $now)) || ($item->getToDate() && ($item->getToDate() < $now))) continue;?>
			               	<li>
				               	<div>
				                	<img src="<?php echo Mage::helper('bannermanager/image')->init($item->getFileThumbnail())?>" />
				                	<h3><?php echo $item->getTitle()?></h3>
				                  	<?php echo $item->getShortDescription();?>
				                </div>
                			</li>
			               	<?php endforeach;?>       		
			            </ul>
			      </div>
		 </div>
	 <?php endif;?>
<?php endif;?>