<?php $_product = $this->getProduct();?>
<h3 class="product-name"><?php echo $_product->getName()?></h3>
<form method="post" action="<?php echo $this->getSaveProductUrl()?>" id="selectandsell_product_edit_form">
<div class="vendor-save-product-btn">
<button class="button" type="button" onclick="cancelSeletAndSell()"><span><span><?php echo $this->__('Cancel')?></span></span></button>
<button class="button" type="submit"><span><span><?php echo $this->__('Save')?></span></span></button>
</div>
<ul>
	<li><label><?php echo $this->__('SKU')?><span class="required">*</span></label><input type="text" class="input-text required-entry" name="vendor_product[vendor_sku]" id="sku"/></li>
	<li><label><?php echo $this->__('Price')?><span class="required">*</span></label><input type="text" class="input-text required-entry validate-number" name="vendor_product[price]" value="<?php echo ($_product->getPrice()*1)?>"/></li>
	<li>
		<label><?php echo $this->__('Tax Class')?><span class="required">*</span></label>
		<select class=" required-entry required-entry select" name="vendor_product[tax_class_id]" id="tax_class_id">
			<?php foreach(Mage::getModel('tax/class_source_product')->getAllOptions(true) as $option):?>
			<option value="<?php echo $option['value']?>"><?php echo $option['label']?></option>
			<?php endforeach;;?>
		</select>
	</li>
</ul>
<input type="hidden" name="product_id" value="<?php echo $_product->getId()?>" />
</form>
<script type="text/javascript">
var productForm = new VarienForm('selectandsell_product_edit_form');
</script>