
<link href="<?php echo $this->getSkinUrl('flexslider/css/shCore.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->getSkinUrl('flexslider/css/shThemeDefault.css') ?>" rel="stylesheet" type="text/css" />
<!-- Demo CSS -->
<!-- <link rel="stylesheet" href="<?php //echo $this->getSkinUrl('flexslider/css/demo.css') ?>" type="text/css" media="screen" /> -->
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('flexslider/flexslider.css') ?>" type="text/css" media="screen" />

<!-- Modernizr -->
<script src="<?php echo $this->getSkinUrl('flexslider/js/modernizr.js') ?>"></script>

<?php $banner = $this->getBanner(); ?>
<?php if(!$banner) echo $this->__('Banner Not Found!'); ?>

<div id="home-slider" role="main">
      <section class="slider">
        <div id="slider" class="flexslider">
          <ul class="slides">
			<?php foreach($this->getItems() as $items): ?>
				<li><img src="<?php echo Mage::helper('bannermanager/image')->init($items->getFilename())->resize($banner->getWidth(),$banner->getHeight()) ?>" title="<?php echo $items->getTitle()?>" alt="" /><span><?php echo $items->getDescription()?></span></li>
			<?php endforeach; ?>
          </ul>
        </div>
		
		<div id="carousel" class="flexslider">
          <ul class="slides">
			<?php foreach($this->getItems() as $items): ?>
				<li><img src="<?php echo Mage::helper('bannermanager/image')->init($items->getFilename())->resize($banner->getWidth(),$banner->getHeight()) ?>" title="<?php echo $items->getTitle()?>" alt="" /><span><?php echo $items->getDescription()?></span></li>
			<?php endforeach; ?>
          </ul>
        </div>
      </section>
      
</div>

  
  <!-- FlexSlider -->
  <script defer src="<?php echo $this->getSkinUrl('flexslider/jquery.flexslider.js') ?>"></script>
  
  <!-- Syntax Highlighter -->
  <script type="text/javascript" src="<?php echo $this->getSkinUrl('flexslider/js/shCore.js') ?>"></script>
  <script type="text/javascript" src="<?php echo $this->getSkinUrl('flexslider/js/shBrushXml.js') ?>"></script>
  <script type="text/javascript" src="<?php echo $this->getSkinUrl('flexslider/js/shBrushJScript.js') ?>"></script>
  
  <!-- Optional FlexSlider Additions -->
  <script src="<?php echo $this->getSkinUrl('flexslider/js/jquery.easing.js') ?>"></script>
  <script src="<?php echo $this->getSkinUrl('flexslider/js/jquery.mousewheel.js') ?>"></script>
  <script defer src="<?php echo $this->getSkinUrl('flexslider/js/demo.js') ?>"></script>
  
  <script type="text/javascript">
	$flex = jQuery.noConflict();
    $flex(function(){
      SyntaxHighlighter.all();
    });
    $flex(window).load(function(){
      $flex('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel",
        
      });
	  
	  
	  $flex('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 210,
        itemMargin: 5,
        asNavFor: '#slider'
      });
	  
	  $flex(".flexslider .slides img").css({
			
			'width':'<?php echo $banner->getWidth(); ?>',
			'height':'<?php echo $banner->getHeight(); ?>',

	  });
    });
  </script>
 