<?php $banner = $this->getBanner();?>
<?php if(!$banner):?>
	<?php echo $this->__("Banner Not Found!")?>
<?php else:?>
	<?php if(!$this->getItems()) :?>
		<?php echo $this->__('Item not fould!');?>
	<?php else:?>
	<?php $random = rand(1111,9999)?>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('ves_bannermanager/js/jquery.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('ves_bannermanager/js/jquery.nivo.slider.pack.js')?>"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('ves_bannermanager/css/nivo-slider.css')?>" />
		<script type="text/javascript">
			$ves_banner_<?php echo $random?> = jQuery.noConflict();
		</script>
		<div class="nivo_slider_container" style="width: <?php echo $banner->getWidth()?>px; height: <?php echo $banner->getHeight()?>px;">
			<div id="slider_<?php echo $random?>" class="nivoSlider">
				<?php foreach($this->getItems() as $item):?>
					<?php $now = Mage::getModel('core/date')->date('Y-m-d H:i:s');?>
			  		<?php if( ($item->getFromDate() && ($item->getFromDate() > $now)) || ($item->getToDate() && ($item->getToDate() < $now))) continue;?>
					<?php if($item->getUrl()):?>
						<a href="<?php echo $this->getItemUrl($item)?>"><img src="<?php echo Mage::helper('bannermanager/image')->init($item->getFilename())->resize($banner->getWidth(),$banner->getHeight())?>" alt="" title="<?php echo $item->getDescription()?"#description_".$item->getId():$item->getTitle();?>" /></a>
					<?php else:?>
						<img src="<?php echo Mage::helper('bannermanager/image')->init($item->getFilename())->resize($banner->getWidth(),$banner->getHeight())?>" alt="" title="<?php echo $item->getDescription()?"#description_".$item->getId():$item->getTitle();?>" />
					<?php endif;?>
				<?php endforeach;?>
            </div>
           <?php foreach($this->getItems() as $item):?>
			  	<?php if( ($item->getFromDate() && ($item->getFromDate() > $now)) || ($item->getToDate() && ($item->getToDate() < $now))) continue;?>
           		<?php if($item->getDescription()):?>
           		<div id=description_<?php echo $item->getId()?>" class="nivo-html-caption">
	                <?php echo $item->getDescription();?>
	            </div>
           		<?php endif;?>
           <?php endforeach;?>
        </div>
	    <script type="text/javascript">
	    $ves_banner_<?php echo $random?>(window).load( function(){
	    	$ves_banner_<?php echo $random?>('#slider_<?php echo $random?>').nivoSlider({
	    		effect:'<?php echo $banner->getEasing()?>', /*Specify sets like: 'fold,fade,sliceDown'*/
	            slices:15, /*For slice animations*/
	            boxCols: 8, /*For box animations*/
	            boxRows: 4, /*For box animations*/
	            animSpeed:500, /*Slide transition speed*/
	            pauseTime:<?php echo $banner->getDelay()?>, /*How long each slide will show*/
	            startSlide:0, 	/*Set starting Slide (0 index)*/
	            directionNav:true, /*Next &amp; Prev navigation*/
	            directionNavHide:true, // Only show on hover
	            controlNav:true, // 1,2,3... navigation
	            controlNavThumbs:false, // Use thumbnails for Control Nav
	            controlNavThumbsFromRel:false, // Use image rel for thumbs
	            controlNavThumbsSearch: '.jpg', // Replace this with...
	            controlNavThumbsReplace: '_thumb.jpg', // ...this in thumb Image src
	            keyboardNav:true, // Use left &amp; right arrows
	            pauseOnHover:true, // Stop animation while hovering
	            manualAdvance:false, // Force manual transitions
	            captionOpacity:0.8, // Universal caption opacity
	            prevText: 'Prev', // Prev directionNav text
	            nextText: 'Next', // Next directionNav text
	            beforeChange: function(){}, // Triggers before a slide transition
	            afterChange: function(){}, // Triggers after a slide transition
	            slideshowEnd: function(){}, // Triggers after all slides have been shown
	            lastSlide: function(){}, // Triggers when last slide is shown
	            afterLoad: function(){} // Triggers when slider has loaded
	    	});
	    });
	    </script>
	 <?php endif;?>
<?php endif;?>