<?php $relatedVendorProducts = $this->getVendorRelatedProducts();?>
<div class="pricecomparison-container">
	<h4><?php echo $this->__('Vendors are selling this product')?></h4>
	<div class="pricecomarison-btn-container">
		<a href="javascript: void(0);" onclick="<?php if(Mage::getSingleton('vendors/session')->isLoggedIn()){if(!$this->isShowSelectProduct()){echo "Comparison.alertBox()"; }else{echo "pcShowMenu()"; }}else{ echo "alert('".$this->__('Please login to your vendor account to use this function.')."')";}  ?>"><?php echo $this->__('Sell your product here')?></a>
		<ul class="pc-menu" id="pricecomparison-menu" style="display: none;">
			<li><a target="_blank" href="<?php echo $this->getUrl('vendors/catalog_product/new',array('pricecomparison'=>$this->getProduct()->getId()));?>"><?php echo $this->__('Add new product')?></a></li>
            <li><a href="javascript:void(0)" onclick="Comparison.showDialogProduct('<?php echo $this->__("Select Product") ?>')"><?php echo $this->__('Select an exist product');?></a></li>
		</ul>
	</div>
	<div id="pricecomparison-table">
		<table cellpadding="0" cellspacing="0" class="pricecomparison-table">
	        <thead>
	            <tr>
	                <?php foreach($this->getColumns() as $column):?>
	                    <th class="<?php echo $column['name']?>"><?php echo $column['title']?></th>
	                <?php endforeach;?>
	            </tr>
	        </thead>
	        <tbody>
	                <?php if($relatedVendorProducts->count()):?>
	                    <?php foreach ($relatedVendorProducts as $product):?>
	                    <?php $vendor = Mage::getModel('vendors/vendor')->load($product->getVendorId());?>
	                    <tr>
	                        <?php foreach($this->getColumns() as $column):?>
	                            <?php echo $this->getColumnHtml($column['block'],$vendor,$product)?>
	                        <?php endforeach;?>
	                    </tr>
	                    <?php endforeach;?>
	            <?php else:?>
	                <tr>
	                    <td colspan="100"><p><?php echo $this->__('There is no vendor sell this product.')?></p></td>
	                </tr>
	            <?php endif;?>
	        </tbody>
	    </table>
    </div>
    <div id="ves-pricecomarison-selectproduct" style="display: none">
    	<?php echo $this->getChildHtml("vendors.product.pricecomparison.list") ?>
    </div>
    <input type="hidden"  id="ves_comparison_current_product" value="<?php echo $this->getProduct()->getId() ?>" />
    <div id="ves_pricecomparison_loading" class="ves_pricecomparison-loading-box" style="display: none;">
        <img src="<?php echo $this->getSkinUrl('ves_vendorspricecomparison/images/loading10.gif')?>" /><br />
        <span><?php echo $this->__("Loading....") ?></span>
    </div>
    <div id="ves_pricecomparison_overlay" class="ves_pricecomparison-overlay" style="display: none;"></div>

	<script type="text/javascript">

		decorateTable('pricecomparison-table');

        var DELETE_ITEM_PRODUCT_VENDOR = "<?php echo $this->getUrl('pricecomparison/process/deleteitem') ?>";
        var SHOW_LIST_PRODUCT_VENDOR = "<?php echo $this->getUrl('pricecomparison/process/showList') ?>";
        var SEARCH_LIST_PRODUCT_VENDOR = "<?php echo $this->getUrl('pricecomparison/process/search') ?>";
        var CHOOSE_PRODUCT_COMPARISON = "<?php echo $this->getUrl('pricecomparison/process/chooseitem') ?>";

		var pcMenuTimer;
		function pcShowMenu(){
			$('pricecomparison-menu').show();
			pcMenuTimer = setTimeout(function(){$('pricecomparison-menu').hide();},2000);
		}
		$('pricecomparison-menu').observe('mouseover',function(){
			clearTimeout(pcMenuTimer);
		});
		$('pricecomparison-menu').observe('mouseout',function(){
			pcMenuTimer = setTimeout(function(){$('pricecomparison-menu').hide();},2000);
		});

        var comparisonloadingBox = new ComparisonLoadingBox('ves_pricecomparison_loading','ves_pricecomparison_overlay');
      //  var productloadingBox = new ComparisonLoadingBox('ves_pricecomparison_loading_product','ves_pricecomparison_overlay_product');
	</script>
</div>