<?php
$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('top_filter'));
$reportCode = $this->getReportCode();
$id_box = $this->getIdBox();
if(empty($requestData)){
    $requestData = array();
    $requestData['report_radio_select'] = $reportCode;
    $isFound = false;
    $reportTypes = Mage::helper('inventorydashboard/constant')->getReportTypes();
    foreach ($reportTypes as $type => $value) {
        foreach ($value['report_code'] as $code => $value2) {
            if (strcmp($code, $reportCode) == 0) {
                $requestData['select_time'] = $value2['default_time_range'];
                $isFound = true;
                break;
            }
        }
        if ($isFound == true) {
            break;
        }
    }
    $requestData['attribute_select'] = 'payment_method';
}
$dataCollection = Mage::helper('inventoryreports/order')->getOrderReportCollection($requestData);
if (is_array($dataCollection)) {
    $collection = $dataCollection['collection'];
} else {
    $collection = $dataCollection;
}
?>
            <!-- report by supplier pie -->
<?php
    $pieData = Mage::helper('inventorydashboard')->getChartPieData($collection, $requestData);
    $series = $pieData['series'];
?>
<div class="chart-parent-div">
        <script type="text/javascript">
            $(function () {
                $_('#<?php echo $id_box?>').highcharts({
                chart: {
                    type: 'pie',
                    options3d: {
                        enabled: false,
                        alpha: 50
                    }
                },
                title: {
                    text: '<?php echo $this->__('Sales Report By Payment Method') ?>',
                },
                plotOptions: {
                    pie: {
                        depth: 30
                    }
                },
                series: [{
                    data: [
                        <?php echo $series;?>
                    ]
                }]
                });
            });
        </script>
    <div id="<?php echo $id_box?>" class="chart-child-div" ></div>
</div>