<?php
$moduleId = rand().time();
$cols =  (int)$this->getConfig( "columns" );
$cols = !empty($cols)?$cols:3;
$span = 12/$cols;
$itemsperpage = (int)$this->getConfig( "max_items" );
$itemsperpage = !empty($itemsperpage)?$itemsperpage:3;

$auto_play = $this->getConfig( "auto_play" );
if ($auto_play) {
	$auto_play = 'true';
}
$auto_play = 'false';
$interval  = $this->getConfig( "interval" );
if ($interval) {
	$interval = 'true';
}
$interval = 'false';


$show_image = $this->getConfig( "latest_show_image", "module_setting", 1);
$image_mode = $this->getConfig( 'latest_image_size');
$sizes = Mage::helper("ves_blog")->getImageSizeModes();
$key = "small_imagesize";
$size = "s";
foreach( $sizes as $k => $v ){
	if($v == $image_mode) {
		$key = $k;
		$size = $v;
		break;
	}
}

$c = $this->getGeneralConfig($key, "");
$tmp = explode( "x", $c );

$thumb_width = $thumb_height = "";
if( count($tmp) > 0 && (int)$tmp[0] ){
	$thumb_width = (int)$tmp[0];
	$thumb_height = (int)$tmp[1];
}

?>
<div class="block productcarousel venus-latest-block" id="module<?php echo $moduleId; ?>">
	<?php if( $this->getConfig("latestmod_title") ) : ?>
		<div class="block-title">
			<strong> <span><?php echo $this->getConfig( "latestmod_title" ); ?> </span> </strong>
		</div>	
	<?php endif; ?>
	
	<div class="block-content">
		<div class="box-vesblog carousel slide" id="vesblogcarousel<?php echo $moduleId;?>">
			<?php if( count($posts) > $itemsperpage) { ?>
			<?php if( $this->getConfig("enable_blognavmodule") ){ ?>
			<div class="carousel-controls">
				<a class="carousel-control left fa fa-angle-left" href="#vesblogcarousel<?php echo $moduleId;?>" data-slide="prev"></a>
				<a class="carousel-control right fa fa-angle-right" href="#vesblogcarousel<?php echo $moduleId;?>" data-slide="next"></a>
			</div>
			<?php } ?>
			<?php } ?>

			<div class="carousel-inner no-margin">
				<?php if( $this->getConfig("latestmod_desc") ) :?>
					<div class="block-description">
						<p><?php echo $this->getConfig("latestmod_desc"); ?></p>
					</div>
				<?php endif; ?>

				<?php $i = 0;?>

				<?php foreach( $posts as $post ): $i++?>

					<?php if($i == 1 || ($i-1) % $itemsperpage == 0) { ?>
					<div class="item row clearfix <?php if(($i-1)==0) {?>active<?php } ?>">
						<?php } ?>
						<div class="col-lg-<?php echo $span;?> col-sm-<?php echo $span;?> col-xs-12 <?php if(($i-1) % $cols == 0){echo "first";}  if($i%$cols == 0){echo "last";} ?>"    >
							<div class="post-block">
								<?php
								$image = "";
								if($thumb_width && $thumb_height) {
									$image = Mage::helper('ves_blog')->resizeImage($post->getFile(), "custom-".$size, $thumb_width, $thumb_height);
								} else {
									$image = $post->getImageURL( "s" );
								}
								if($image && $show_image):
								?>

								<div class="post-image">
									<a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
									<img src="<?php echo $image;?>" class="post-image" alt="<?php echo $post->getTitle();?>"/>
									</a>
								</div>

								<?php endif; ?>
								<h4><a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>"><?php echo $post->getTitle(); ?></a></h4>
								
								<div class="latest-description">
								<?php 
									if (strlen($post->getDescription()) > 100) :
										echo substr($post->getDescription(),0, 70).'...';
									else : 
										echo $post->getDescription();
									endif;
								?>
								</div>

								<?php if( $this->getConfig("latest_show_commentcouter") || $this->getConfig("latest_showcreated") || $this->getConfig("latest_show_hits")) :?>
									<div class="blog-meta">

										<?php if($this->getConfig("latest_showcreated")) { ?>
										<div class="blog-updated">
											<span><?php echo $this->__("Last Update");?></span>
											<?php echo $post->getUpdated(); ?>
										</div>
										<?php } ?>

										<?php if($this->getConfig("latest_show_hits")) { ?>
										<div class="blog-hits"><span><?php echo $this->__("Read");?></span> <strong><?php echo $post->getHits(); ?></strong> <?php echo $this->__("Times"); ?></div>
										<?php } ?>

										<?php if($this->getConfig("latest_show_commentcouter")) { ?>
										<div class="blog-comment-count"><?php echo $this->getCountingComment($post->getId());?> <?php  echo $this->__("Comment");?></div>
										<?php } ?>

									</div>

								<?php endif; ?>
								<p class="blog-readmore">
									<a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
										<?php echo $this->__("Read more >");?>
									</a>
								</p>
						</div>		
					</div>
					<?php if( $i%$itemsperpage == 0 || $i==count($posts) ) { ?>
				</div>
				<?php } ?>
			<?php endforeach; ?>



		</div>
	</div>	
</div>
</div>
<script type="text/javascript">
	jQuery('#vesblogcarousel<?php echo $moduleId;?>').carousel({interval:<?php echo $interval ?>,auto:<?php echo $auto_play ?>,pause:'hover', cycle: true});
</script>