<?php $relatedVendorProducts = $this->getVendorRelatedProducts();?>
<thead>
<tr>
    <?php foreach($this->getColumns() as $column):?>
        <th class="<?php echo $column['name']?>"><?php echo $column['title']?></th>
    <?php endforeach;?>
</tr>
</thead>
<tbody>
<?php if($relatedVendorProducts->count()):?>
    <?php foreach ($relatedVendorProducts as $product):?>
        <?php $vendor = Mage::getModel('vendors/vendor')->load($product->getVendorId());?>
        <tr>
            <?php //var_dump($this->getColumns()) ?>
            <?php foreach($this->getColumns() as $column):?>
                <?php echo $this->getColumnHtml($column['block'],$vendor,$product)?>
            <?php endforeach;?>
        </tr>
    <?php endforeach;?>
<?php else:?>
    <tr>
        <td colspan="100"><p><?php echo $this->__('There is no vendor sell this product.')?></p></td>
    </tr>
<?php endif;?>
</tbody>