<?php
/**
 * 
 */
?>

<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php
    // Get Menu Title
    $configData = Mage::getStoreConfig('hybrid_mobile');
    // Footer CMS page links
    if (isset($configData['footer_settings']['footercms_links'])){
        $footercms_links = $configData['footer_settings']['footercms_links'];
        $footercms_links = explode(',', $footercms_links);
    } else {
        $footercms_links = array();
    }

    // Check Back To Top Link
    $backtotop_link = $configData['footer_settings']['backtotop_link'];
    // Check Desktop Site link
    $desktop_link = $configData['footer_settings']['desktop_link'];
?>

<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function($) {
        $('.top-link').click(function(){
            $('html, body').animate({scrollTop:0}, 'fast');
        });
    });
</script>

<div data-role="navbar">
    <ul class="footermenu">
        <?php foreach ($footercms_links as $footercms_link): ?>
            <?php $footercms_title = Mage::getModel('cms/page')->load($footercms_link, 'identifier')->getTitle(); ?>
            <li><a href="<?php echo $this->getUrl($footercms_link) ?>"><?php echo $this->__($footercms_title) ?></a></li>
        <?php endforeach; ?>
        <?php $_links = $this->getLinks(); ?>
        <?php foreach ($_links as $_link): ?>
            <?php if ($_link instanceof Mage_Core_Block_Abstract): ?>
                <?php echo $_link->toHtml() ?>
            <?php else: ?>
                <li<?php if ($_link->getIsFirst() || $_link->getIsLast()): ?> class="<?php if ($_link->getIsFirst()): ?>first<?php endif; ?><?php if ($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if($backtotop_link == 1): ?><li><a href="javascript:void(0);" class="top-link"><?php echo $this->__('Back to top') ?></a></li><?php endif; ?>
        <?php if($desktop_link == 1): ?><li><a class="switchtodesktop" href="<?php echo $this->getUrl('hybridmobile/index/toDesktop') ?>"><?php echo $this->__('View Desktop Version') ?></a></li><?php endif; ?>
    </ul>
</div>
