<?php $maps = $this->getMapCollection() ;
$i=0;
?>
<ul>
    <?php foreach($maps as $map):
        $position = explode("|", $map->getData("position"));
        ?>
        <li  onclick ="findMapAddressCustomer(<?php echo $position[0] ?>,<?php echo  $position[1] ?>,<?php echo $i ?>)" rel="<?php echo $i ?>" <?php if($i == sizeof($maps)-1) echo 'class="last"'?>>
            <div id="box-map-<?php echo $map->getId() ?>">
                <div>
                    <div style="float:left;width:50px">
                        <a class="map-colorbox-logo" href="<?php echo $this->getUrlImage($map->getId());?>"><img src="<?php echo $this->getUrlImage($map->getId());?>" width="50px" height="50px"></a>
                    </div>
                    <div style="float:right;width:170px">
                        <?php echo  $this->__("Title : ");?>
                        <?php echo $map->getData("title") ;?>
                        <br />
                        <?php echo $this->__("Address : ") ; ?>
                        <?php echo $map->getData("address") ;  ?>
                        <br />
                        <?php echo $this->__("Telephone : ") ?>
                        <?php echo $map->getData("telephone")  ?>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div style="clear:both"></div>
                <input type="hidden" name="vendor[logo_url]" id="logo_url_<?php echo $i ?>" value="<?php echo $this->getUrlImage($map->getId());?>"/>
            </div>
        </li>
        <?php
        $i++;
    endforeach;?>
</ul>
<script type="text/javascript">
    $j(".map-colorbox-logo").colorbox({rel:'map-colorbox-logo'});
</script>

