   <div class="product-block" itemtype="http://schema.org/Product">					
                    <div class="image">
						<?php 
							// Get the Special Price
							$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
							// Get the Special Price FROM date
							$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
							// Get the Special Price TO date
							$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
							// Get Current date
							$today =  time();
						 
							if ($specialprice) {
								if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
						?>
								<span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
						<?php  
								}
							}
						?>
						<div class="product-img imga">
							<a href="<?php echo $_product->getProductUrl() ?>"  itemprop="url" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img">
							<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							<?php if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) { ?>
									<span class="hover-image">
										<a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></a>
									</span>
							<?php } ?>
						</div>
                        <?php if( $categoryPzoom ) { ?>
                        <?php
                            $productId = $_product->getId();
                            $_product2 = Mage::getModel('catalog/product')->load($productId);
                        ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width);?>" class="colorbox product-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="icon-zoom-in"></span></a>
                        <?php } ?>

						

                    </div>
                    <div class="product-meta">
                        <div class="left"> 
                            <h3 class="product-name name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
        					
        					<?php if($_product->getRatingSummary()): ?>
                            <div class="rating">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            </div>
                            <?php endif; ?>
        					
        					<div class="price">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                            
                        </div> 
                        <div class="right">  
                            <?php if ($quickview) { ?>
                                <a class="a-quickview ves-colorbox" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>"><span class='fa fa-plus'></span><?php echo $this->__('Quick View'); ?></a>
                            <?php } ?>

                            <div class="action">
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><i class="fa fa-shopping-cart"> </i> <?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="add-to-links button-group">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <div class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></div>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <div class="compare"><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-retweet"></i></a></div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>

                    </div>        
                </div>
            </div>