<div class="faq-search">
<h2 class="title"><?php echo $this->__('Search FAQ ') ?></h2>
<form id="search_mini_form" action="<?php echo $this->getUrlSearch() ?>" method="get">
    <div class="form-search">
        <input id="search" type="text" name="q" value="<?php if($this->getKeyQuery() )echo $this->getKeyQuery() ?>" class="input-text" maxlength="<?php //echo $catalogSearchHelper->getMaxQueryLength();?>" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
    </div>
</form>
</div>