<?php
/**
 * 
 * Overrides template/catalog/product/list/upsell.phtml
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="page-title">
    <h1><?php echo $this->__('You may also like') ?></h1>
</div>

<!-- Grid View -->
<div class="row">
    <ul class="ui-grid-a category-products-grid upsell-products">
        <?php 
        $cookie = Mage::getModel("core/cookie");
        $iphone = $cookie->get("iphone");
        $bg_colors = array('s1','s2','s3','s4','s5');
        $_productCollection = $this->getItemCollection();
        $i=0; foreach ($_productCollection as $_product):
        $_productNameStripped = $this->stripTags($_product->getName(), null, true);?>

        <li class="small-6 columns  ui-block-<?php echo  $i%2==0?'a':'b'?> grid-block">
            <?php if($iphone == 'true'): ?>
                <a class="product-link s <?php echo $bg_colors[array_rand($bg_colors)]?>" href="<?php echo  $_product->getProductUrl() . '?ios_title=' . $_product->getName() . '&ios_action=hidemenu' ?>"> 
            <?php else: ?>
                <a class="product-link d <?php echo $bg_colors[array_rand($bg_colors)]?>" href="<?php echo  $_product->getProductUrl() ?>">
            <?php endif; ?>
                <img class="thumb" src="<?php echo  $this->helper('catalog/image')->init($_product, 'small_image')->resize(223,319); ?>" alt="" />
            </a> 
            <div class="info-sec small-12 columns">
                <h2 class="product-name"><?php echo ucwords(strtolower($_productNameStripped))?></h2>
                <div class="prices"><?php echo  $this->getPriceHtml($_product, true); ?></div>
            </div>
        </li>
        <?php $i++;endforeach; ?>
    </ul>
</div>
<?php endif ?>


