
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>

<!-- start: Meta -->
    <meta charset="utf-8">
    <title>Personal Logistic</title>
    <meta name="description" content=">Personal Logistic">
    <meta name="keyword" content=">Personal Logistic">
<!-- end: Meta -->
     
<?php //echo $this->getChildHtml('head') ?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>

<!-- start: Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- end: Mobile Specific -->

 <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('custom/css/layout/logistic.css');?>">




</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

<?php echo $this->getChildHtml('after_body_start') ?>

    <!-- Header Start Here -->
    <div class="page-header-fixed">
        <div class="container navcon">

        </div>
    </div>
    <!-- Header End Here -->

<div class="wrapper">
<?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">

       

       
        
    


       <!-- Content Area -->
        <div class="main-container col1-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">

                    <?php echo $this->getChildHtml('global_messages') ?>
                    
                    <?php echo $this->getChildHtml('content') ?>

                </div>
            </div>
        </div>
       <!-- End Content Area -->



        <!-- start: Footer -->
        <!-- <footer>
            <div class="container main-footer">
                <div class="row">
                    <p class="powered"><span style="text-align:center;width:100%;float:left;">&copy;VENDORPLACE ver. 1.0.0 by <a alt="Bluethink IT Consulting Pvt. Ltd" href="http://www.bluethink.in" target="_blank" style="color: #fff;">www.bluethink.in</a></span> </p>
                </div>
            </div>
        </footer> -->
        <!-- End: Footer -->

        <!-- start: JavaScript-->
            <script src="<?php echo $this->getSkinUrl('vendorjs/menu.js'); ?>"></script>
        <!-- end: JavaScript-->

    </div>
</div>
</body>
</html>


