<?php
/**
 * @author Robogento <support@robogento.com>
 * @package Robogento
 * @subpackage SEO Rich
 * @url http://robogento.com
 *
 * This code is protected by copyright and you are not allowed to share it, alter it and sell as your own.
 * @copyright  Copyright (c) 2012 Robogento
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td>
                <h3>SEO Rich (Microdata): Check &amp; Install Updates</h3>
            </td>
            <td class="form-buttons">
                <?php echo $this->getReturnToCfgButtonHtml(); ?>    
            </td>
            <td class="form-buttons" style="width:63px">
                <?php echo $this->getRerunButtonHtml(); ?>    
            </td>
         </tr>
    </tbody></table>
</div>
<style type="text/css">
    span.qs_status_icon { background-position: center left; background-repeat: no-repeat; height: 20px; width: 16px; display: block; float: left; padding-right: 4px; }
    span.qs_success { background-image: url("<?php echo $this->getAdminImagesUrl();?>success_msg_icon.gif"); }
    span.qs_error { background-image: url("<?php echo $this->getAdminImagesUrl();?>error_msg_icon.gif"); }
    span.qs_advice { background-image: url("<?php echo $this->getAdminImagesUrl();?>note_msg_icon.gif"); }
    span.qs_neutral { display: none; }
    #robo_qs #qs_loader {
        height: 16px;
        width: 16px;
        padding-right: 14px;
        float: left;
    }
    #robo_qs #qs_msgs {
        height: 20px;
        line-height: 20px;
        width: 400px;
        float: left;
    }
    #robo_qs #qs_msgs strong {
        font-size: 14px;
    }
    #robo_qs {
        width: 720px;
        height: 500px;
        overflow: hidden;
    }
</style>
<div id="robo_qs">
    <div id="qs_loader"><img src="<?php echo $this->getAdminImagesUrl();?>ajax-loader.gif" /></div>
    <div id="qs_msgs"></div>
    <br style="clear: both" />
</div>
<script type="text/javascript">
    function qs_ajax(step) {
        new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/seorich_checkforupdates/ajax"); ?>',
        {
            method:'get',
            parameters: {step: step},
            onSuccess: function(transport){
                var response = transport.responseText.evalJSON();

                var hint_link = '';
                // If there is an error, show the hint link
                if(response['stepData']['status'] == "error" && response['stepData']['show_resolve_link'] == true) {
                    hint_link = '&nbsp;&nbsp;[<a href="http://support.robogento.com/updates/router/?ext=seorich&step='+encodeURIComponent(response['stepData']['uniqueId'])+'" target="_blank" title="How to resolve this?">How to resolve this?</a>]';
                }

                var break_space = "";
                if(response['stepData']['msg'].search('<strong>') != -1) {
                    break_space = "<br />";
                }
                $("qs_msgs").update( break_space + '<span class="qs_status_icon qs_'+response['stepData']['status']+'"></span>' + response['stepData']['msg'] + hint_link + '<br style="clear:left" />' + $("qs_msgs").innerHTML );


                if(response['endQueue'] != 1) {
                    qs_ajax(response['nextStep']);
                } else {
                    $("qs_loader").hide();
                }
            },
            onFailure: function() {
                alert('Error connecting to AJAX trigger')
            },
            timeout : 20000
        });
    }
    qs_ajax(0);
</script>