<html>
    <head>    
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/css.css" rel="stylesheet">
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/dark.css" rel="stylesheet">
        <link href="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/blue.css" rel="stylesheet">    
        </script><script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js.js"></script>
        <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/js_003.js"></script>        
        
        <!-- charts -->
        <!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>-->
        <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/charts/highcharts.js"></script>
        <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/charts/highcharts-3d.js"></script>
        <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/dashboard/lib/charts/modules/exporting.js"></script>
        <script src="<?php echo $this->getJsUrl() ?>magestore/adminhtml/inventory/reports/lib/charts/modules/no-data-to-display.js"></script>
    </head>
</html>
