
<div class="block block-faq">
    <div class="block-title">
        <strong><span><?php echo $this->__('FAQs Search ') ?></span></strong>
    </div>
    <form id="pollForm" action="<?php echo $this->getUrlSearch() ?>" method="get" >
        <div class="block-content">
            <ul id="poll-answers">
            	<li>
   					<input id="search" type="text" name="q" value="<?php if($this->getKeyQuery() )echo $this->getKeyQuery() ?>" class="input-text" maxlength="<?php //echo $catalogSearchHelper->getMaxQueryLength();?>" />
   				</li>
   				<li>
       				 <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
       			</li>	
            </ul>
         
        </div>
    </form>
</div>