<?php 
	$storeId = '';
	if($this->getData('storeId')){
		$storeId = $this->getData('storeId');
	}
?>
<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('items')->__('Category Mapping') ?></h3></td>
      <td class="a-right"><?php  echo $this->getButtonsHtml() ?></td>
    </tr>
  </table>
  </div>
  <p class="switcher">
    <label for="store_switcher">Choose Mercado Libre Root Category:</label>
    <select onchange="return meliCategoryStore(this);" id="meli_category_switcher" name="meli_category_switcher">
      <?php
$data['root_id'] = '';
$data = $this->getData();
foreach($data['meliCategoriesRoot'] as $key => $value ){
	echo '<option value="'.$key.'"';
	if($key == $data['root_id']){  $selected = 'selected'; } else { $selected = '';};
	echo $selected .'>&nbsp;&nbsp;'.$value.'&nbsp;&nbsp;</option>';
}
?>
    </select>
		<?php 
		if(count($data['meliCategoriesRoot']) == 1 || count($data['meliCategoriesRoot']) == 0){
			echo "&nbsp;&nbsp;<a href='".$this->getUrl('adminhtml/system_config/edit/section/mlitems')."'>Click here</a>&nbsp;&nbsp;To Choose MercadoLibre Root Category";
		}
	
	?>
<form  id="edit_form" action="<?php echo $this->getUrl('*/*/post');?>" method="post" >
<div style="text-align:right;">
	<input name="button" type="button" value="Save Mapping" onclick="edit_form.submit()" class="form-button scalable save" />
</div>
  <div> <?php echo $this->getGridHtml() ?> </div>
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
</form>
<script type="text/javascript">
    function meliCategoryStore(obj) {
		var storeId = '<?php echo $storeId; ?>';
		var storePram = '';
		if(storeId){
			var storePram = storeId ? 'store/' + storeId + '/' : '';
		}
        var categoryParam = obj.value ? 'root_id/' + obj.value + '/' : '';
        setLocation('<?php echo $this->getUrl('*/*/*');?>' + storePram + categoryParam);
        }
</script>
