<?php 
$pro_sku = $this->getRequest()->getParam('sku');

    $quesModel = Mage::getModel('quesanswer/quesanswer')->getCollection()->addFieldToFilter('sku',array('eq'=>$pro_sku))->addFieldToFilter('status',array('eq'=> 1));
    $quescount = count($quesModel->getData());

?>
 <div class="comp comp-question-ans" style="clear: both;">
        <h2 class="section-head fnt-19">Questions &amp; Answers</h2>      
</div>
<ul class="clearfix qna-question-wrapper" id="example2">
<?php 

foreach ($quesModel as $quesans) {
    $ques = $quesans['question'];
    $ans = $quesans['answer'];

?>
   <li class="qna-question clearfix " style="padding:0px 0px 0px 0px;">
         <div class="qBlock">
            <span class="qna-ques-head">
               <span class="ques-icon">Q</span>
               <div class="qright-info"><a href=""><span class="ques"><?php echo __($ques); ?></span></a></div>
            </span>
         </div>
         <!-- For Question-Answer pair -->
         <div class="dotted-line"></div>
            <div class="response-text"><span class="ques-icon">A</span>
                <div class="right-info"><span class="ans"><?php echo __($ans); ?></span>
                </div> 
            </div>
      </li>
      <?php } ?>
 </ul>

 <div id="example2-pagination">
      <a id="example2-previous" href="#">&laquo; Previous</a> 
      <a id="example2-next" href="#">Next &raquo;</a> 
  </div>


<link rel="stylesheet" href="<?php //echo $this->getSkinUrl('custom/css/style.css')?>"> 


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('custom/js/jquery.paginate.js')?>"></script>
<script type="text/javascript">
jQuery(document).ready(function()    {
  jQuery('#example2').paginate({itemsPerPage: 2});
  jQuery.getJSON('data.json', function(data) {
    var items = [];
    jQuery.each(data.items, function(i, item) {
      items.push('<li>' + item + '</li>');
    });
  });
});
</script>