<div class="dashboard-inventory">
    <div class="content-header">
        <table cellspacing="0">
            <tbody><tr>
                    <td><h3 class="head-dashboard"><?php echo $this->__('Dashboard'); ?></h3></td>
                </tr>
            </tbody></table>
    </div>

    <!-- dashboard tabs -->
    <?php
    $check = Mage::helper('inventoryplus')->isDataInstalled();
    ?>
    <?php if ($check == 1) : ?>
        <?php echo $this->getChildHtml('warehouse_shipment') ?> 

        <?php echo $this->getChildHtml('adjuststock') ?>   

        <?php echo $this->getChildHtml('lowstock') ?>   

        <?php echo $this->getChildHtml('dropship') ?>   
    <?php endif ?>
</div>