<?php
/**
 * @file
 *   Adminhtml help template for kreXX
 *   kreXX: Krumo eXXtended
 *
 *   This is a debugging tool, which displays structured information
 *   about any PHP object. It is a nice replacement for print_r() or var_dump()
 *   which are used by a lot of PHP developers.
 *
 *   kreXX is a fork of Krumo, which was originally written by:
 *   Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author brainworXX GmbH <info@brainworxx.de>
 *
 * @license http://opensource.org/licenses/LGPL-2.1
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2016 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
use Brainworxx\Krexx\Framework\Config;

krexx::editSettings();
?>
<h1>Edit local browser settings</h1>
<?php if (!Config::isEnabled(null)) { ?>
    Normally, we would display the menu for the local browser settings here.
    <br/>
    The output of kreXX was <b>disabled</b>, so it will not be displayed.
<?php } else { ?>
    <?php if (Config::getConfigValue('output', 'destination') == 'file') { ?>
        Normally, we would display the menu for the local browser settings here.
        <br/>
        The output of kreXX is switched to <b>file</b>, so it will not be displayed.

    <?php } else { ?>
        Here you can edit the local browser settings. They are stored in a cookie, and only affect your current browser. Unlike the configuration file, not all settings can be edited here by default. This can be changed in the
        <i>Edit FE configuration</i> menu. Local browser settings overwrite configuration file settings.
        <br/><br/>
        <b>Please note, that these settings only affect your current browser!</b>
    <?php } ?>
<?php } ?>
