<?php
/**
 * Template for displaying lowest product price from associated products in different places (products grid, product view page etc)
 */
?>
<?php
$_product = $this->getProduct();
$_store = $_product->getStore();
$_id = $_product->getId(); 
$_cpspHelper = $this->helper('configurableproductssimpleprices');
$lodedProduct = Mage::getModel('catalog/product')->load($_product->getId()); 
$_configurableSimple = $_cpspHelper->isEnable($lodedProduct);
$_controllerName = Mage::app()->getRequest()->getControllerName(); 
$_listControllers = array('category','product','result','advanced','index','cart','product_compare'); 
if($lodedProduct->getTypeId() != 'configurable' || !$_configurableSimple || ($_configurableSimple && !in_array($_controllerName, $_listControllers))){ 
	echo $this->setTemplate('catalog/product/price.phtml')->toHtml();
	return;
}

$_coreHelper = $this->helper('core');
$_taxHelper = $this->helper('tax');

$_cpspHelper->setUpStaticData($lodedProduct);
$class = '';?>

	<?php 
		list($spID, $_minimalPriceValue) = $_cpspHelper->getMinimalProductPrice($_id);
		
		if(is_array($spID)) $spID = array_shift($spID);
		if($spID != null && $spID != 0) $_sProduct = Mage::getModel('catalog/product')->load($spID);

		$_minimalPriceValue = $_store->roundPrice($_store->convertPrice($_minimalPriceValue));
        //$_minimalPriceValue = Mage::helper('core')->currency($_minimalPriceValue,false,false);
		
		if ($_sProduct && $_minimalPriceValue) {
			$_exclTax = $_taxHelper->getPrice($_sProduct, $_minimalPriceValue);
			$_inclTax = $_taxHelper->getPrice($_sProduct, $_minimalPriceValue, true);

			/* -------------- changelog 11.12.15 --------------- */
			/*if($_sProduct->getFinalPrice() < $_minimalPriceValue) {
				$_exclTax = $_taxHelper->getPrice($_sProduct, $_sProduct->getFinalPrice());
				$_inclTax = $_taxHelper->getPrice($_sProduct, $_sProduct->getFinalPrice(), true);
			}*/
			/* -------------- changelog 11.12.15 --------------- */
			
			$price = $_minimalPriceValue;
		} 
	?>
	<?php if ($price): ?>
        <div class="price-box"<?php echo $class;?>>
            <p<?php if ($_minimalPriceValue): ?> class="minimal-price"<?php endif ?>>
                <?php if ($_minimalPriceValue): ?>
                    <span class="price-label"><?php echo $this->__('Price From:') ?></span>
                <?php endif ?>
                <?php if ($_taxHelper->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
                        <span class="price"
                              id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_exclTax, false) ?>
                        </span>
                    </span>
                    <span class="price-including-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
                        <span class="price"
                              id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_inclTax, false) ?>
                        </span>
                    </span>
                <?php else: ?>
                    <?php
                    $_showPrice = $_inclTax; 
                    if (!$_taxHelper->displayPriceIncludingTax()) {
                        $_showPrice = $_exclTax;  
                    }
                    ?>
                    <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                    <?php echo $_coreHelper->formatPrice($_showPrice, false) ?>
                </span>
                <?php endif; ?>
            </p>
        </div>
    <?php endif; ?>
