.ves-tabs-chatlive .ves-livechat-box-button,.ves-tabs-chatlive .top-bar{background:#<?php echo $this->getColor("vendors/vendorslivechat/theme_color"); ?>}

.ves-tabs-chatlive .ves-livechat-box-button h1 , .ves-tabs-chatlive .top-bar h1{color:#<?php echo $this->getColor("vendors/vendorslivechat/text_color"); ?>!important}
.ves-livechat-box-create .content-box .button-set button span{
    background:#<?php echo $this->getColor("vendors/vendorslivechat/theme_color"); ?>;
    color:#<?php echo $this->getColor("vendors/vendorslivechat/text_color"); ?>;
}

.ves-livechat-container .livechat-tabs .tab a{background:#<?php echo $this->getColor("vendors/vendorslivechat/theme_color"); ?>}
.ves-livechat-container .livechat-tabs .chat-content .box-content-reply button{background:#<?php echo $this->getColor("vendors/vendorslivechat/theme_color"); ?>}
.ves-livechat-container .livechat-tabs .tab a{color:#<?php echo $this->getColor("vendors/vendorslivechat/text_color"); ?>!important}
.ves-livechat-container .livechat-tabs .chat-content .box-content-reply button span{
    color:#<?php echo $this->getColor("vendors/vendorslivechat/text_color"); ?>;
}