<div class="grid np" id="vendorsquote-items">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables quote-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Comment with product') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th class="proposal"><span class="nobr"><?php echo $this->helper('sales')->__('Price Proposal') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Margin (GP)') ?></span></th>
                <th></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php if(sizeof($_items)):?>
        <?php $i=0;foreach ($_items as $_item):?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php $i ++;?>
            </tbody>
        <?php endforeach; ?>
        <?php else:?>
            <tbody>
                <tr><td colspan="7" class="no-item"><?php echo $this->__('No records found.')?></td></tr>
            </tbody>
        <?php endif;?>
    </table>
  </div>
</div>
