<div>
   <h3> <?php echo __('Personal Logistic Orders'); ?> </h3>
</div>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('custom/css/custommish.css')?>" media="all"/>
<?php  
      $id = $this->getRequest()->getParam('id'); 
      $plUserModel = Mage::getModel('personallogistic/personallogistic')->load($id);
      $pluserModeldata = Mage::getModel('personallogistic/personallogisticuserorder')->getCollection()
      ->addFieldToFilter('pl_user_id',array('eq'=>$id));
       $pluserprice        = $plUserModel->getTotalestimateprice();

?>

    <div class="selectedCategories">
      <input type="text" id="myInputs" onkeyup="myFunction()" placeholder="Search by Order Id" title="Type in a name">
          <table  id="myTable" class="display" cellspacing="0">
              <thead>
                  <tr>
                      <th style="padding: 5px;"><?php echo __('Order Increment Id'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Customer Name'); ?></th>
              <th style="padding: 5px;"><?php echo __("Customer's telephone number"); ?></th>
                    <th style="padding: 5px;"><?php echo __('Order Delivery Address'); ?></th>
                    <th style="padding: 5px;"><?php echo __('Seller WarehouseAddress'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Total Order Amount'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Product Name'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Product Quantity'); ?></th>
                      <th style="padding: 5px;"><?php echo __('SKU'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Volumetric Weight'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Dispatch Cost'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Order Status'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Status'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Comment'); ?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Amount'); ?></th>
                      <th style="padding: 5px; border-right: none;"><?php echo __('Action'); ?></th>
                  </tr>
              </thead>

               <tfoot>
                  <tr>
                      <th style="padding: 5px;"><?php echo __('Order Id'); ?></th>
                     
                  </tr>
              </tfoot>
              <tbody>

              <?php 
                  foreach($pluserModeldata as $data)
                  {
                    $orderid          = $data->getOrderId();
                    $salesOrder       = Mage::getModel('sales/order')->load($orderid);
                    $currencysymbol   = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                    $incrementId      = $salesOrder->getIncrementId();
                    $customerFullName = $salesOrder->getCustomerFirstname()." ".$salesOrder->getCustomerLastname();
                    $grandtotal       = $salesOrder->getGrandTotal();
                    $billto           = $salesOrder->getBillingAddress()->format('html'); 
                    $shipto           = $salesOrder->getShippingAddress()->format('html'); 
                    $telephone        = $salesOrder->getShippingAddress()->getTelephone();
                    $weight           = $salesOrder->getWeight();
                    $Order = Mage::getModel('sales/order')->loadByIncrementId($incrementId);
                    $orderItems = $Order->getItemsCollection();


                    $vendor_id        = $salesOrder->getVendorId();
                    $vendorcollection=Mage::getModel('inventoryplus/warehouse')->load($vendor_id,'vendor_id');

                      $telephone1=$vendorcollection['telephone'];                 
                       $countryid=$vendorcollection['country_id'];
                      $stateid=$vendorcollection['state_id'];

                       $region1 = Mage::getModel('directory/region')->load($stateid);
                      $state_name = $region1->getName();
                     
                        $country = Mage::getModel('directory/country')->loadByCode($countryid);
                         $countryname= $country->getName();
                
              ?>
                    <tr>
                        <td style="padding: 5px;"><?php echo __($incrementId); ?></td>
                        <td style="padding: 5px;"><?php echo __($customerFullName); ?></td>
                        <td style="padding: 5px;"><?php echo __($telephone); ?></td>
                        <td style="padding: 5px;"><?php echo __($billto); ?></td>
                        <td style="padding: 5px;"><?php echo __($vendorcollection['street']."<br>".$vendorcollection['city'].","."<br>".$state_name.",".$vendorcollection['postcode']."<br>".$countryname."<br>T: ".$telephone1); ?></td>
                        <td style="padding: 5px;"><?php echo __(number_format($grandtotal, 2, '.', '')." ".$currencysymbol); ?></td>
                        <td style="padding: 5px;">
                            <?php
                                 foreach ($orderItems as $productdata) {
                                      echo __($productdata->getName())."<br>";
                                  }
                            ?>
                        </td>
                        <td style="padding: 5px;">
                            <?php
                                 foreach ($orderItems as $productdata) {
                                      echo __(number_format($productdata->getQtyOrdered(), 2, '.', ''))."<br>";
                                  }
                            ?>
                        </td>
                        <td style="padding: 5px;">
                            <?php
                                 foreach ($orderItems as $productdata) {
                                      echo __($productdata->getSku())."<br>";
                                  }
                            ?>
                        </td style="padding: 5px;">
                        <td style="padding: 5px;"><?php echo __(number_format($weight, 2, '.', '')); ?></td>
                        <td style="padding: 5px;"><?php echo __($pluserprice." ".$currencysymbol); ?></td>
                        <td style="padding: 5px;"><?php 
                         if($data['order_status'] == 0){
                              echo __('Not Delivered');
                            }else{
                              echo __('Delivered');
                            } ?></td>

                        <td style="padding: 5px;"><?php  
                         if($data['payment_status'] == 0){
                              echo __('Unpaid');
                            }else{
                              echo __('Paid');
                            }  ?></td>

                            <td style="padding: 5px;"><?php echo __($data['payment_comment']); ?></td>
                            <td style="padding: 5px;"><?php echo __($data['payment_amount'])." ".$currencysymbol; ?></td>


                                              <td style="padding: 5px; width: 1%;border-right: none;">
                         <?php
                            if($data['payment_status'] == 1){
                                echo 'Complete';
                            }elseif($data['order_status'] == 1){?>
                                  <a class= "js-open-modal btn btn-small" href="#" data-modal-id="popup1-<?php echo $data['id']; ?>"><?php echo __('Pay'); ?></a>
 <div id="popup1-<?php echo  $data['id']; ?>" class="modal-box">
          <header> <a href="#" class="js-modal-close close">×</a>
            <h3><?php echo __('Payment For Order #');?><?php echo $incrementId; ?></h3>
          </header>
          <div class="modal-body">

            <span><?php echo __('20% amount will be deducted from Dispatch Price of Personal logistic user.');?></span><br>
            <span><?php echo __('Dispatch Cost')?> - <?php echo $pluserprice." ".$currencySymbol; ?></span><br>
            <span><?php echo __('Admin Amount - ').$totalcostMishAdmin = ((20/100)* $pluserprice)." ".$currencySymbol; ?></span><br>
            <span><?php echo __('Personal Logistic User Amount - ').$cost = ($pluserprice -  $totalcostMishAdmin)." ".$currencySymbol ?></span><br>

            <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/paypluserCost'); ?>" method="post" enctype="multipart/form-data">
               <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                  <span><?php echo __('Comment'); ?> - <textarea name="orderpaymentcomment"></textarea></span>
               <input type="hidden" name="rowid" value="<?php echo $data['id']; ?>" />
                <input type="hidden" name="dispatch_amount" value="<?php echo $pluserprice; ?>" />
               <button class= "confirmationpayment">Submit</button>
            </form>

          </div>

</div>

<script>
    var ok = jQuery.noConflict();
    ok(function(){

    var appendthis =  ("<div class='modal-overlay js-modal-close'></div>");

    ok('a[data-modal-id]').click(function(e) {
    e.preventDefault();
    ok("body").append(appendthis);
    ok(".modal-overlay").fadeTo(500, 0.7);
  
    var modalBox = ok(this).attr('data-modal-id');
    ok('#'+modalBox).fadeIn(ok(this).data());
    });  


    ok(".js-modal-close, .modal-overlay").click(function() {
    ok(".modal-box, .modal-overlay").fadeOut(500, function() {
    ok(".modal-overlay").remove();
    });

    });

    ok(window).resize(function() {
    ok(".modal-box").css({
    top: (ok(window).height() - ok(".modal-box").outerHeight()) / 2,
    left: (ok(window).width() - ok(".modal-box").outerWidth()) / 2
    });
    });

    ok(window).resize();

    });
</script>

                                
                           <?php  }else{
                              echo "Order is not delivered yet";
                            } ?>
                      </td>
                  </tr>
                           <?php } ?>
              </tbody>


        </table>
  </div>


<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script> 
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script>jQuery.noConflict();</script>
<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInputs");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>
