<?php
/**
 * Request For Quote template
 *
 * @var $this VES_VendorsQuote_Model_Quote
 */
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?php echo $_priceDisplay; ?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Request for Quote') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <?php foreach($this->getQuotes() as $quote):?>
        <?php if(!$quote->getItemsCount()) continue;?>
        
        <h3><?php echo $quote->getVendor()->getTitle(); ?></h3>
        <form action="<?php echo $this->getUrl('vquote/index/updatePost') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <table id="shopping-cart-table" class="cart-table data-table">
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <col width="1" />
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
                <col width="1" />
                <?php endif; ?>
        
            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th><span class="nobr"><?php echo $this->__('Product') ?></span></th>
        
                        <th>&nbsp;</th>
                        
                        <th><?php echo $this->__('Remarks')?></th>
                        <th class="a-center cart-price-head"">
                            <span class="nobr"><?php echo $this->__('Price') ?></span>
                        </th>
        
                        <th class="a-center">
                            <?php echo $this->__('Qty') ?>
                        </th>
        
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="50" class="a-right cart-footer-actions">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button2 btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                            <?php endif; ?>
        
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach($quote->getAllItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </form>
        <div class="cart-totals-wrapper">
            <div class="cart-totals">
                <div class="client-data box">
                    <h2><?php echo $this->__('Remarks')?></h2>
                    <?php echo $this->__('Do you have a general remark with this Quote Request?')?><br>
                    <textarea class="input-text" rows="5" cols="10" id="customer:client_request" name="customer[client_request]"></textarea>
                </div>
            </div>
        </div>
        <div style="clear:both;display: block; width: 100%; height: 20px;"></div>
    <?php endforeach;?>
</div>
