<?php
/**
 * Overrides template/catalog/product/list.phtml
 * Product list template
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php
// Check if enabling filter
$configData = Mage::getStoreConfig('hybrid_mobile');
$listfilter = $configData['catalog_settings']['listfilter'];
// Check if showing rating stars
$ratingstars = $configData['catalog_settings']['ratingstars'];

$cookie = Mage::getModel("core/cookie");
$iphone = $cookie->get("iphone");
$bg_colors = array('s1','s2','s3','s4','s5');
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
if(!$_productCollection->getSize()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.');?></p>
<?php else: ?>

<!-- Grid View -->
<div class="row">
    <ul class="small-12 columns category-products-grid no-padding">
        <?php foreach ($_productCollection as $_product): ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="small-6 columns product grid-block">
            <div class="grid-block-image">
                <?php if($iphone == 'true'): ?>
                    <a class="product-link <?php echo $bg_colors[array_rand($bg_colors)]?>" href="<?php echo  $_product->getProductUrl() . "?ios_title=" . $_product->getName() . '&ios_action=hidemenu' ?>"> 
                <?php else : ?>   
                    <a class="a-center product-link <?php echo $bg_colors[array_rand($bg_colors)]?>" href="<?php echo  $_product->getProductUrl() ?>">
                <?php endif; ?>
                        <img class="thumb" src="<?php echo  $this->helper('catalog/image')->init($_product, 'small_image')->resize(600); ?>" alt="<?php echo $_product->getName()?>" />
                    </a>
             </div> 

            <!-- Price Information -->
            <div class="info-sec small-12 columns">
                <?php $name = $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                <h2 class="product-name"><a href="<?php echo  $_product->getProductUrl() . "?ios_title=" . $_product->getName() . '&ios_action=hidemenu' ?>"><?php echo ucwords(strtolower($name))?></a></h2>
                <div class="prices"><?php echo $this->getPriceHtml($_product, true); ?></div>
                <?php if($ratingstars == 1): ?>
                    <?php if($_product->getRatingSummary()): ?>    
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?> 
                <?php endif; ?>  
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<div class="toolbar-wrapper bottom"><?php echo $this->getToolbarHtml(); ?></div>
<?php endif; ?>

