<?php

?>
<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
    <div class="product-review-box">
        <table cellspacing="0" id="product-review-table">
        	<?php if($this->isAdminMode()):?>
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th><span class="nobr"><?php echo Mage::helper('rating')->__('1 star') ?></span></th>
                    <th><span class="nobr"><?php echo Mage::helper('rating')->__('2 stars') ?></span></th>
                    <th><span class="nobr"><?php echo Mage::helper('rating')->__('3 stars') ?></span></th>
                    <th><span class="nobr"><?php echo Mage::helper('rating')->__('4 stars') ?></span></th>
                    <th><span class="nobr"><?php echo Mage::helper('rating')->__('5 stars') ?></span></th>
                </tr>
            </thead>
            <?php endif;?>
        <?php $_oddIterator = 1; ?>
            <tbody>
            <?php foreach ($this->getRating() as $_rating): ?>
                <tr class="odd<?php if($_oddIterator == $this->getRating()->getSize()): $_oddIterator = 0; ?> last<?php endif; ?>">
                    <td class="label"><?php echo $this->escapeHtml($_rating->getTitle()) ?></td>
                <?php $_iterator = 1; ?>
                <?php $_vote = $this->getVote($_rating->getId())?>
                <!-- admin mode -->
                <?php if($this->isAdminMode()):?>
	                <?php while($_iterator<=5): ?>
	                    <td<?php if($_iterator == 5): ?> class="last"<?php endif; ?>><input type="radio" class="vendor_review_radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getTitle()) ?>_<?php echo $_iterator ?>" value="<?php echo $_iterator?>" <?php if($_iterator == $_vote['rate_value']): ?>checked="checked"<?php endif; ?> /></td>
	                <?php $_iterator++ ?>
	                <?php endwhile; ?>
	                <!-- end#adminmode -->
                <?php else:?>
                	<td>
                		<div class="rating-box">
                        	<div class="rating" style="width:<?php echo $_vote['rate_percents'] ?>%;"></div>
                        </div>
                	</td>
                <?php endif?>
                </tr>
            <?php $_oddIterator ++; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
    </div>
<script type="text/javascript">
//<![CDATA[
    
    /*disable rating radio*/
    <?php if(!Mage::registry('useAdminMode')):?>       
	$$(".vendor_review_radio").each(function(item){item.disabled = true;});
	<?php endif; ?>
    Validation.addAllThese(
    [
           ['validate-rating', '<?php echo Mage::helper('rating')->__('Please select one of each ratings above') ?>', function(v) {
                var trs = $('product-review-table').getElementsBySelector('tr');
                var inputs;
                var error = 1;

                for( var j=0; j < trs.length; j++ ) {
                    var tr = trs[j];
                    if( j > 0 ) {
                        inputs = tr.getElementsBySelector('input');

                        for( i in inputs ) {
                            if( inputs[i].checked == true ) {
                                error = 0;
                            }
                        }

                        if( error == 1 ) {
                            //console.log(tr)
                            return false;
                        } else {
                            error = 1;
                        }
                    }
                }
                return true;
            }]
    ]
    );
//]]>
</script>
<?php else: ?>
    <?php echo Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif; ?>
