  <div class="homepageheading">
     <h2><?php echo __("Home Page Configurations"); ?></h2>
  </div>

<div id="homepage-tabs"  class="bannertopTabing">

 <div>
      <ul>
        <li><a href="#tab-1"><?php echo __('Homepage Banner Slider'); ?></a></li>
        <li><a href="#tab-2"><?php echo __('Homepage Category Product Slider'); ?></a></li>
        <li><a href="#tab-3"><?php echo __('Homepage Category with Brand'); ?></a></li>
        <div class="clr"></div>
      </ul>
</div>
<!-- Banner Slider section start here -->

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->getSkinUrl('ves_vendors/js/jquery.pagination-with-hash-change-2.js')?>"></script> 
  <script>jQuery.noConflict();</script>
<div id="tab-1">


<h3><?php echo __('Banner Slider : '); ?></h3>

  <div class="bannerslider">
     <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/saveBanerimages') ?>" method="POST" enctype="multipart/form-data">
         <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
          <label>Select image:</label>
          <input type="file" value="" name="fileToUpload" id="fileToUpload">

          <label>Image Tab Label:</label>
          <input type="text" name="imagelabel">

          <label>Title:</label>
          <input type="text" name="title">

          <label>Banner url:</label>
          <input type="text" name="url" >
          <button type="submit" class="savebutton" ><?php echo __('Save'); ?></button><br><br>
      </form>
  </div>


<?php 
  $btSLiderModel = Mage::getModel('btslider/btslider')->getCollection();

?>

<div class="bannertable">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    
             <table border="0" cellpadding="0" cellspacing="0">
      <thead>
        <tr class="toprow">
            <td><?php echo __('Id'); ?></td>
          <td><?php echo __('Image'); ?></td>
          <td><?php echo __('Tab Label'); ?></td>
          <td><?php echo __('Image Title'); ?></td>
          <td><?php echo __('Url'); ?></td>
          <td><?php echo __('Action'); ?></td>
        </tr>
      </thead>
      <tbody>
      <?php 
foreach ($btSLiderModel as $imagedata) { 
  $id = $imagedata['btslider_id'];
  $image = $imagedata['images'];
  $url = $imagedata['url'];
  $imagelabel = $imagedata['imagelabel'];
  $title = $imagedata['title'];
  $imagethumbnail = $imagepath.$image;
?>
<input type="hidden" name="id" value="<?php echo $id; ?>">
        <tr>
              <td><?php echo $id;?></td>
            <td> <img height="100px" width="100px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/".$image; ?>"></td>
            <td><?php echo $imagelabel;?></td>
            <td><?php echo $title; ?></td>
            <td><?php echo $url; ?></td>
            <td><a href="<?php echo Mage::helper("adminhtml")->getUrl('*/*/deletesliderimage') ?>?id=<?php echo $id;?>"><?php echo __('Delete'); ?></a></td>
        </tr>
  <?php } ?>
      </tbody>
    </table>
   
  </div>
</div>


<!-- Banner Slider section end here -->

<!-- Homepage Category Slider section start here -->
  <div id="tab-2">
    
      <div>
         <h3><?php echo __("Category Product Slider : "); ?></h3>
     </div>

     <div class="bannerslider">


       <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/saveCategorysliderdata') ?>" method="POST" enctype="multipart/form-data">
         <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

          <label>Category id:</label>
          <input type="text" name="categoryid">

          <label>Product Sku:</label>
          <input type="text" name="productsku">
          <small><?php echo __('you can enter more than one sku with "," seperated.'); ?></small>

          <button type="submit" class="savebutton" ><?php echo __('Save'); ?></button><br><br>
      </form>
     </div>
     <?php
        $btproductSLiderModel = Mage::getModel('btslider/btproductslider')->getCollection();
     /*   echo "<pre>++";
        print_r($btproductSLiderModel->getData());*/
        
      ?>
     <div class="bannertable">
             <table border="0" cellpadding="0" cellspacing="0">
      <thead>
        <tr class="toprow">
            <td><?php echo __('Id'); ?></td>
          <td><?php echo __('Category Id'); ?></td>
          <td><?php echo __('Product Sku'); ?></td>
          <td><?php echo __('Action'); ?></td>
        </tr>
      </thead>
      <tbody>
      <?php 
            foreach ($btproductSLiderModel as $productsliderdata) { 
              $id = $productsliderdata['bt_productslider_id'];
              $categoryid = $productsliderdata['categoryid'];
              $productsku = $productsliderdata['product_sku'];
            ?>
<input type="hidden" name="id" value="<?php echo $id; ?>">
        <tr>
            <td><?php echo $id;?></td>
            <td><?php echo $categoryid;?></td>
            <td><?php echo $productsku ?></td>
            <td><a  href="<?php echo Mage::helper("adminhtml")->getUrl('*/*/deleteproductslider') ?>?id=<?php echo $id;?>"><?php echo __('Delete'); ?></a></td>
        </tr>
  <?php } ?>
      </tbody>
    </table>
   
     </div>
  </div>
<!-- Homepage Category Slider section start here -->


<!-- Homepage Category with brand start here -->
<div id="tab-3">
<div>
    <h3><?php echo __('Category and Brands : '); ?></h3>
</div>

      <div class="bannerslider">
      <div>
          <h4><u><?php echo __('Category and Brand name section'); ?></u>:</h4>
      </div>
       <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/saveCategorybranddata') ?>" method="POST" enctype="multipart/form-data">
         <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

          <label>Select featured image:</label>
          <input type="file" value="" name="featuredimage" id="featuredimage">

          <label>Category id:</label>
          <input type="text" name="catid" id="catid">

          <label>Sub Category Id:</label><span style="color: red;">*</span>
          <input type="text" name="subcatid " id="subcatid" required="required">
        <!--   <input type="button" onclick="validate();" value="Validate" id="validate" /> -->
    
        <a href="javascript:void(0)" onclick="validate();">Validate</a> <span id="result" style="font-weight: bold;"></span>
       
            <img id="loading-image" src='https://cdn-us-east.velaro.com/Content/Images/loading.gif' style="display: none;height: 10px; width: 10px;"  />
        
     
        <br>
          <small><?php echo __('you can enter more than one id name with "," seperated.'); ?></small><br>
            <br>
          <label>Image(1):</label>
          <input type="file" value="" name="image1" id="image1">
          <br>
          <label>Image(2):</label>
          <input type="file" value="" name="image2" id="image2">
          <br>

          <button type="submit" class="savebutton" id="savebtn" ><?php echo __('Save'); ?></button><br><br>
      </form>
     </div>


     <script>
          document.getElementById('savebtn').disabled= true;
          document.getElementById('savebtn').style.background='#000000';
         
    </script>

    <script>


    function validate(){
      var formkey = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
       var subcatvalue = document.getElementById("subcatid").value;
       var catvalue = document.getElementById("catid").value;
      // alert(formkey);
      jQuery('#loading-image').show();
          jQuery.ajax(
                    {
              type: "POST",
              url: '<?php echo Mage::helper("adminhtml")->getUrl('*/*/validateSubCatdata') ?>',
              data: {subcatvalue: subcatvalue, form_key: formkey, catvalue: catvalue},
              success: function(result)
            {
              jQuery('#loading-image').hide();
              if(result == 1 && result!= 0){
                document.getElementById('savebtn').disabled= false;
                document.getElementById('savebtn').style.background='#eb5f34';
                jQuery("#result").html('Correct id(s)');
          
              }else{
                 document.getElementById('savebtn').disabled= true;
                 document.getElementById('savebtn').style.background='#000000';
                jQuery("#result").html('Please check sub category Id(s).');
              }
              
            }
                });
    }

       
     </script>
     <?php
        $btcatbrandModel = Mage::getModel('btslider/btcatbrand')->getCollection();
       /* echo "<pre>++";
        print_r($btcatbrandModel->getData());*/
        
      ?>
     <div class="bannertable">
             <table border="0" cellpadding="0" cellspacing="0">
      <thead>
        <tr class="toprow">
          <td><?php echo __('Id'); ?></td>
          <td><?php echo __('Category Id'); ?></td>
          <td><?php echo __('Sub Category Id'); ?></td>
          <td><?php echo __('Featured Image'); ?></td>
          <td><?php echo __('More Images'); ?></td>
          <td><?php echo __('Action'); ?></td>
        </tr>
      </thead>
      <tbody>
      <?php 
            foreach ($btcatbrandModel as $catbrand) { 
              $id = $catbrand['catbrand_id'];
              $catid = $catbrand['catid'];
              $brand = $catbrand['brand_name'];
              $featuredImage = $catbrand['featured_image'];
              $Image1 = $catbrand['imageone'];
              $Image2 = $catbrand['imagetwo'];
            ?>
<input type="hidden" name="id" value="<?php echo $id; ?>">
        <tr>
            <td><?php echo $id;?></td>
            <td><?php echo $catid;?></td>
            <td><?php echo $brand ?></td>
            <td><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$featuredImage; ?>" height="100px" width="100px"></td>
            <td>
                <div><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$Image1; ?>" height="50px" width="100px"></div><br>
                <div><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?><?php echo "slider/brandfeatureimage/".$Image2; ?>" height="50px" width="100px"></div>
            </td>
            <td><a  href="<?php echo Mage::helper("adminhtml")->getUrl('*/*/deletecatbrand') ?>?id=<?php echo $id;?>"><?php echo __('Delete'); ?></a></td>
        </tr>
  <?php } ?>
      </tbody>
    </table>
   
     </div>
</div>

<!-- Homepage Category with brand end here -->


</div>

<script>
  var j = jQuery.noConflict();
    j( function() {
      j( "#homepage-tabs" ).tabs();
    } );
</script>

<style type="text/css">
  .bannertopTabing ul li {float: left;
    margin-right: 10px;
    background: #329f91;
    padding: 8px;}
  .bannertopTabing ul li a  {    display: block;
    text-decoration: none;
    color: #fff;
    text-transform: uppercase;}
    .clr {clear: both;}
    .ui-state-active {
    background: #eb5f34 !important;
}
.homepageheading {padding: 10px 0;}
.bannerslider {background: #ddd; padding: 15px 10px; padding-bottom: 0; font-size: 15px; margin-bottom: 10px; border-radius: 4px;}
.bannerslider input {padding: 7px 0;}
.bannerslider .savebutton {background: #eb5f34;
    padding: 7px 20px;
    border: none;
    font-size: 15px;
    font-weight: normal;
    text-transform: uppercase; border-radius: 3px;}
   .bannertable table  {    width: 100%;
    border: solid 1px #ccc;
    margin: 0 10px 32px 0;
    float: left;
    border-bottom: none;}
.bannertable table  tr td {padding: 8px; border:solid 1px #ddd;}
    .bannertable table  tr.toprow {font-weight: bold; background: none;}
  
  .bannertable table tr:nth-child(even) {background: #fff}
.bannertable table tr:nth-child(odd) {background: #ccc}
</style>