<?php
/**
 * @file
 *   Adminhtml help template for kreXX
 *   kreXX: Krumo eXXtended
 *
 *   This is a debugging tool, which displays structured information
 *   about any PHP object. It is a nice replacement for print_r() or var_dump()
 *   which are used by a lot of PHP developers.
 *
 *   kreXX is a fork of Krumo, which was originally written by:
 *   Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author brainworXX GmbH <info@brainworxx.de>
 *
 * @license http://opensource.org/licenses/LGPL-2.1
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2016 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

$linkToConfig = Mage::helper("adminhtml")->getUrl("/krexx/config");
$linkToCookieEdit = Mage::helper("adminhtml")->getUrl("/krexx/feconfig");

?>
<h1>kreXX Quick Docu</h1>
<div class="entry-edit">

  <div class="section-config">
    <div class="entry-edit-head collapseable">
      <a onclick="Fieldset.toggleCollapse('usage'); return false;" href="#" id="usage-head" class="">
        Usage
       </a>
    </div>
    <fieldset id="usage" class="config collapseable" style="display: none;">
      <h3>Usage</h3>
      <div class="comment">
        kreXX will be called in the PHP source code:
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx($myObject);</code></pre></div>

        Most of the time you will use this method. kreXX will analyse the $object and give you detailed information about it:
        <ul>
          <li style="padding-left: 5px;list-style: disc; margin-left: 20px;">Public attributes of the object</li>
          <li style="padding-left: 5px;list-style: disc; margin-left: 20px;">Protected attributes of the object (can be toggled)</li>
          <li style="padding-left: 5px;list-style: disc; margin-left: 20px;">Private attributes of the object (can be toggled)</li>
          <li style="padding-left: 5px;list-style: disc; margin-left: 20px;">Content of the traversable part of the object (can be toggled)</li>
          <li style="padding-left: 5px;list-style: disc; margin-left: 20px;">Result of all configured debugging callbacks (can be configured)</li>
        </ul>
        In case the variable is not an object, it will simply display its content.

        <br /><br />
        Define a "moment" during a benchmark test. The $string should be something meaningful, like "Model invoice db call":
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx::timerMoment($string);</code></pre></div>
        <br />
        End the benchmark test and displays the result:
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx::timerEnd();</code></pre></div>
        <br />
        Outputs backtrace with sourcecode. When kreXX finds objects inside the backtrace, it will analyse them:
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx::backtrace();</code>	</pre></div>
        <br />
        Register the fatal error handler in the system:
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx::registerFatal();</code></pre></div>
        <br />
        Unregister the fatal error handler in the system:
        <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>krexx::unregisterFatal();</code></pre></div>
      </div>
    </fieldset>
    <script type="text/javascript">//&lt;![CDATA[Fieldset.applyCollapse('usage');//]]&gt;</script>
  </div>



  <div class="section-config">
    <div class="entry-edit-head collapseable">
      <a onclick="Fieldset.toggleCollapse('configuration'); return false;" href="#" id="configuration-head" class="">
        Configuration
      </a>
     </div>
    <fieldset id="configuration" class="config collapseable" style="display: none;">
      <h3>Configuration</h3>
      kreXX is already preconfigured, you don't have to cofigure it. But there are always moments when you want to change it. There are 3 levels of configuration:<br /><br />
      <h4>1.) Factory settings</h4>
      The factory settings are hardcoded fallback settings.<br /><br />
      <h4>2.) Configuration file Krexx.ini</h4>
      The configuration file settings are stored in the file Krexx.ini. kreXX shows in it's output footer where it is searching for this file. In Magento this is normally:
      <div style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;"><pre><code>app/code/community/Brainworxx/Includekrexx/Block/krexx/Krexx.ini</code></pre></div>
      You can edit these settings <a href="<?php echo $linkToConfig ?>">here.</a><br />
      Configuration file settings overwrite factory settings.<br /><br />
      <h4>3.) Local browser settings</h4>
      You can edit the local browser settings on the fly in the footer of the kreXX output. They are stored in a cookie, and only affect your current browser. Unlike the configuration file, not all settings can be edited there.<br />
      Local browser settings overwrite configuration file settings.<br />
      You can edit these settings <a href="<?php echo $linkToCookieEdit ?>">here.</a><br />
      <b>Please note, that these are only local settings, only affecting your current browser.</b>
    </fieldset>
    <script type="text/javascript">//&lt;![CDATA[Fieldset.applyCollapse('configuration');//]]&gt;</script>
  </div>





  <div class="section-config">
    <div class="entry-edit-head collapseable">
      <a onclick="Fieldset.toggleCollapse('on_the_web'); return false;" href="#" id="on_the_web-head" class="">
         kreXX on the web
      </a>
    </div>
    <fieldset id="on_the_web" class="config collapseable" style="display: none;">
      <h3>kreXX on the WeBB</h3>
      <a target="_blank" href="https://docs.typo3.org/typo3cms/extensions/includekrexx/">Documentation</a><br />
      <a target="_blank" href="https://github.com/brainworxx/kreXX/issues">Bug reports for kreXX</a><br />
      <a target="_blank" href="https://github.com/brainworxx/kreXX-Magento-1-Extension/issues">Bug reports for the Magento kreXX extension</a><br />
      <a target="_blank" href="http://typo3.org/extensions/repository/view/includekrexx">TYPO3 kreXX</a><br />
      <a target="_blank" href="https://www.magentocommerce.com/magento-connect/krexx-debugger.html">Magento kreXX</a>
    </fieldset>
    <script type="text/javascript">//&lt;![CDATA[Fieldset.applyCollapse('on_the_web');//]]&gt;</script>
  </div>
</div>


