<?php
/**
 * Open Biz Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file OPEN-BIZ-LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mageconsult.net/terms-and-conditions
 *
 * @category   Magecon
 * @package    Magecon_AdvancedStockBar
 * @version    1.0.0
 * @copyright  Copyright (c) 2012 Open Biz Ltd (http://www.mageconsult.net)
 * @license    http://mageconsult.net/terms-and-conditions
 */
?>
<?php
$assocProducts = $this->getAssocProducts();
$assocProductsStock = array();
foreach ($assocProducts as $_product) {
    $stockBarInfo = $this->getStockBarInfo($_product);
    $assocProductsStock[$_product->getId()] = array(
        "height" => $stockBarInfo["bar_height"],
        "disabled" => (int) $_product->getDisableStockBar(),
        "bar_value" => $stockBarInfo["bar_value"],
        "bar_color" => $stockBarInfo["bar_color"],
        "comment" => $stockBarInfo["stock_comment"]
    );
    
    echo '<style>.magecon-product-color' . $_product->getId() . ' progress::-webkit-progress-value { background: ' . $stockBarInfo["bar_color"] . '; }</style>';
    echo '<style>.magecon-product-color' . $_product->getId() . ' progress::-moz-progress-bar { background: ' . $stockBarInfo["bar_color"] . '; }</style>';
}
?>

<style>
	.html5-progress-bar progress::-webkit-progress-value {
		border-radius: 9px;
	}
	
	.html5-progress-bar progress::-moz-progress-bar {
		border-radius: 9px;
	}
</style>
<script type="text/javascript">
    //<![CDATA[
    Product.Config.prototype.getIdOfSelectedProduct = function() {
        var productsArray = <?php echo json_encode($assocProductsStock); ?>;
        var existingProducts = new Object();
        for (var i = this.settings.length - 1; i >= 0; i--) {
            var selected = this.settings[i].options[this.settings[i].selectedIndex];
            if (selected.config) {
                for (var iproducts = 0; iproducts < selected.config.products.length; iproducts++) {
                    var usedAsKey = selected.config.products[iproducts] + "";
                    if (existingProducts[usedAsKey] == undefined) {
                        existingProducts[usedAsKey] = 1;
                    } else {
                        existingProducts[usedAsKey] = existingProducts[usedAsKey] + 1;
                    }
                }
            }
        }
        
        for (var keyValue in existingProducts) {
            for (var keyValueInner in existingProducts) {
                if (Number(existingProducts[keyValueInner]) < Number(existingProducts[keyValue])) {
                    delete existingProducts[keyValueInner];
                }
            }
        }
        var sizeOfExistingProducts = 0;
        var currentSimpleProductId = "";
        for (var keyValue in existingProducts) {
            currentSimpleProductId = keyValue;
            sizeOfExistingProducts = sizeOfExistingProducts + 1
        }

        var progressBar = document.getElementById('progressbar');
        var progressBarDiv = document.getElementById('magecon-html5-progress-bar');
        
        if (sizeOfExistingProducts == 1 && !productsArray[currentSimpleProductId]['disabled']) {
            if (progressBarDiv != null) {
            	progressBarDiv.style.display = 'block'; // to show
            }
            
            var product = productsArray[currentSimpleProductId];
            var mageconBarCurrentValue = product['bar_value'];
            var mageconBarColor = product['bar_color'];
            var mageconBarHeight = product['height'];

            progressBar.setAttribute('style', 'height: ' + mageconBarHeight + 'px;');
            progressBarDiv.setAttribute('class', 'html5-progress-bar magecon-product-color' + currentSimpleProductId);
                
            var comment = document.getElementById('availability');
            if (comment != null) {
                comment.innerHTML = product['comment'];
            }
            
            if (typeof mageconBarCurrentValue != 'undefined') {
            	var mageconBarValue = 0;
        		var mageconBarМаx = document.getElementById("progressbar").getAttribute('max');
        		var mageconBarTime = (1000 / mageconBarМаx) * 2;
        		
        		var mageconBarLoading = function() {
        			mageconBarValue += 1;
        			document.getElementById("progressbar").setAttribute('value', mageconBarValue);
        			
        			if (mageconBarValue == mageconBarCurrentValue) {
        				clearInterval(mageconBarAnimate);                    
        			}
        		};
        		
        		var mageconBarAnimate = setInterval(function() {
        			mageconBarLoading();
        		}, mageconBarTime);
            }
        } else {
            if (progressBar != null) {
            	progressBarDiv.style.display = 'none'; // to hide
            }
            var comment = document.getElementById('availability');
            if (comment != null) {
                comment.innerHTML = '';
            }
        }
    }
    //]]>
</script>
<?php foreach ($this->getAttributes() as $id): ?>
    <script type="text/javascript">
        //<![CDATA[
        Event.observe(window, 'load', function() {
            Event.observe('attribute<?php echo $id ?>', 'change', spConfig.getIdOfSelectedProduct.bind(spConfig));
        });
        //]]>
    </script>
<?php endforeach; ?>
<?php if ($this->getConfig('enable_bar')): ?>
    <p id="availability"></p>
    <div id="magecon-html5-progress-bar" class="html5-progress-bar" style="display: none;">
		<div class="progress-bar-wrapper">
			<progress id="progressbar" value="0" max="100"></progress>
		</div>
	</div>
<?php endif; ?>