<?php
$_collection = $this->getAsyncCollection();
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 style="width: 100%">
                <?php echo Mage::helper('asynccache')->__('Asynchronous Cache Management') ?> (<?php echo $_collection->getSize() ?>)
                <small style="color: #999; font-size: 0.8em;">
                    Saved <?php echo $this->getSavedTime() ?> of your time
                </small>
                <small style="color: #999; font-size: 0.8em; float: right;">
                    Status: <?php echo $this->getStatus() ?>
                </small>
                <small style="color: #999; font-size: 0.8em; float: right; margin-right: 20px;">
                    Last execution time: <?php echo $this->getLastExecutionTime() ?>
                </small>
            </h3></td>
            <?php if (count($_collection) > 0): ?>
                <td class="form-buttons"><button onclick="setLocation('<?php echo $this->getUrl('*/asyncCache/process')?>')" type="button" class="scalable delete"><span><?php echo Mage::helper('asynccache')->__('Force process queue') ?></span></button></td>
            <?php endif ?>
        </tr>
    </table>
</div>

<?php if (count($_collection) > 0): ?>
    <div class="grid">
        <table class="data" cellspacing="0">
            <thead>
                <tr class="headings">
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('asynccache')->__('Created At') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('asynccache')->__('Match Mode') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('asynccache')->__('Tags') ?></span></th>
                </tr>
            </thead>
            <tbody>
            <?php $i = 0;?>
            <?php foreach ($_collection as $_item): ?>
                <tr <?php echo ($i++ % 2) ? '' : 'class="even"'; ?>>
                    <td><?php echo $_item->getCreatedAt() ?></td>
                    <td><?php echo $_item->getMode() ?></td>
                    <td class="a-left"><?php echo implode('<br>', $_item->getTagArray()) ?></td>
                </tr>
            <?php endforeach ?>
            <?php if ($_collection->count() < $_collection->getSize()): ?>
                <tr>
                    <td>...</td>
                    <td>...</td>
                    <td class="a-left">...</td>
                </tr>
            <?php endif ?>
            </tbody>
        </table>
    </div>

<?php else: ?>
    <?php echo Mage::helper('asynccache')->__('No pending queue entries available.') ?>
<?php endif; ?>