
<?php
    $_helper    = $this->helper('vendorscategory');
    $_category  = $this->getCurrentCategory();
?>
<div class="page-title category-title">
    <h1><?php echo $_category->getName() ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_category->getDescription() ?>
    </div>
<?php endif; ?>
<?php echo $this->getChildHtml('top_content');?>
<?php if($this->canShowProducts()):?>
	<?php echo $this->getProductListHtml() ?>
<?php endif;?>
<?php echo $this->getChildHtml('bottom_content');?>

