
<?php 

      $vendorID = Mage::app()->getRequest()->getParam('id');
?>
<div>
    <div style="text-align: center;"">
          <h3 ><?php echo __('Manage Commission');?><?php echo __(" (Vendor Id- ".$vendorID).")";?></h3>
    </div>

    <div>
       <?php
           $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
           $vendorCommissionModel = Mage::getModel('commision/vendorcommision')->getCollection()
           ->addFieldToFilter('vendor_id',array('eq' => $vendorID));
        ?>
    </div>
    <div class="selectedCategories">
        <table id="example" class="display" cellspacing="0" width="100%">
            <thead>
                  <tr>
                      <th style="padding: 5px;"><?php echo __('Invoice Increment Id');?></th>
                      <th style="padding: 5px;"><?php echo __('Order Id');?></th>
                      <th style="padding: 5px;"><?php echo __('Price');?></th>
                      <th style="padding: 5px;"><?php echo __('Product Name');?></th>
                      <th style="padding: 5px;"><?php echo __('CategoryName');?></th>
                      <th style="padding: 5px;"><?php echo __('Product Quantity');?></th>
                      <th style="padding: 5px;"><?php echo __('Amount (Price X Item Ordered Quantity)');?></th>
                      <th style="padding: 5px;"><?php echo __('Commission Amount (%)');?></th>
                      <th style="padding: 5px;"><?php echo __('Calculated Paid Amount');?></th>
                      <th style="padding: 5px;"><?php echo __('Status');?></th>
                      <th style="padding: 5px;"><?php echo __('Payment Date and Time');?></th>
                      <th style="padding: 5px;"><?php echo __('Comment');?></th>
                      <th style="padding: 5px;border-right: none;"><?php echo __('Action');?></th>
                 </tr>
            </thead>
             <tfoot>
                  <tr>
                      <th><?php echo __('Invoice Increment Id');?></th>
                      <th><?php echo __('Order Id');?></th>
                      <th><?php echo __('Price');?></th>
                      <th><?php echo __('Product Name');?></th>
                      <th><?php echo __('CategoryName');?></th>
                      <th><?php echo __('Product Quantity');?></th>
                      <th><?php echo __('Amount (Price X Item Ordered Quantity)');?></th>
                      <th><?php echo __('Commission Amount (%)');?></th>
                      <th><?php echo __('Calculated Paid Amount');?></th>
                      <th><?php echo __('Status');?></th>
                      <th><?php echo __('Payment Date and Time');?></th>
                      <th><?php echo __('Comment');?></th>
                      <th><?php echo __('Action');?></th>
                 </tr>
            </tfoot>
             <tbody>
                  <?php 
                        foreach ($vendorCommissionModel as $commissionData) {
                           $id                        = $commissionData['id'];
                           $invoiceincrementId        = $commissionData['invoice_increment_id'];
                           $invoiceincrementId        = $commissionData['invoice_increment_id'];
                           $orderId                   = $commissionData['order_increment_id'];
                           $productPrice              = $commissionData['product_amount'];
                           $productCategoryCommission = $commissionData['pro_categorycommision'];
                           $calculatedCommissionAmount= $commissionData['calculated_commission'];
                           $status                    = $commissionData['status'];
                           $paymentDateTime           = $commissionData['payment_datetime'];
                           $actualPrice               = $commissionData['product_actual_price'];
                           $QtyOrdered                = $commissionData['product_qty'];
                           $comment                   = $commissionData['comment'];
                           $productName               = $commissionData['product_name'];
                           $categoryName              = $commissionData['category_name'];
                       
                       
                  ?>
           
                  <tr>

                      <td style="padding: 5px;"><?php echo $invoiceincrementId; ?></td>
                      <td style="padding: 5px;"><?php echo $orderId; ?></td>
                      <td style="padding: 5px;"><?php echo $actualPrice."". $currencySymbol; ?></td>
                      <td style="padding: 5px;"><?php echo $productName ?></td>
                      <td style="padding: 5px;"><?php echo $categoryName; ?></td>
                      <td style="padding: 5px;"><?php echo $QtyOrdered; ?></td>
                      <td style="padding: 5px;"><?php echo $productPrice." ". $currencySymbol;; ?></td>
                      <td style="padding: 5px;"><?php echo $productCategoryCommission; ?></td>
                      <td style="padding: 5px;"><?php echo $calculatedCommissionAmount." ". $currencySymbol;; ?></td>
                      <td style="padding: 5px;">
                          <?php  
                              if($status==0){
                                echo "Unpaid";
                              }else{
                                echo "Paid";
                              }
                         
                           ?>
                         
                       </td>
                      <td style="padding: 5px;"><?php echo $paymentDateTime; ?></td>
                        <td style="padding: 5px;"><?php echo $comment; ?></td>
                      
                      <td style="padding: 5px; width: 1%;border-right: none;">
                         <?php
                            if($status == 1){
                                echo 'Complete';
                            }else{?>
                                  <a class= "js-open-modal btn btn-small" href="#" data-modal-id="popup1-<?php echo $id; ?>"><?php echo __('Pay'); ?></a>
<div id="popup1-<?php echo $id; ?>" class="modal-box">
  <header> <a href="#" class="js-modal-close close">×</a>
    <h3><?php echo __('Payment id');?> - <?php echo $id; ?></h3>
  </header>
  <div class="modal-body">

    <span><?php echo __('Product Actual Price')?> - <?php echo $actualPrice." ". $currencySymbol; ?></span><br>
    <span><?php echo __('Product Quantity')?> - <?php echo $QtyOrdered; ?></span><br>
    <span><?php echo __('Commission %')?> - <?php echo $productCategoryCommission; ?></span><br>
    <span><?php echo __('Calculated Amount')?> - <?php echo $calculatedCommissionAmount." ". $currencySymbol; ?></span><br>

    <form action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/payCommission'); ?>" method="post" enctype="multipart/form-data">
       <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
       <span><?php echo __('Comment'); ?> - <textarea name="paymentcomment"></textarea></span>
       <input type="hidden" name="id" value="<?php echo $id; ?>" />
                 <button class= "confirmation">Send</button>
    </form>

  </div>
  <footer> 
<!--   <a href="#" class="btn btn-small js-modal-close">Close</a>
   </footer> -->
</div>

<script>
var ok = jQuery.noConflict();
ok(function(){

var appendthis =  ("<div class='modal-overlay js-modal-close'></div>");

  ok('a[data-modal-id]').click(function(e) {
    e.preventDefault();
    ok("body").append(appendthis);
    ok(".modal-overlay").fadeTo(500, 0.7);
    //$(".js-modalbox").fadeIn(500);
    var modalBox = ok(this).attr('data-modal-id');
    ok('#'+modalBox).fadeIn(ok(this).data());
  });  
  
  
ok(".js-modal-close, .modal-overlay").click(function() {
    ok(".modal-box, .modal-overlay").fadeOut(500, function() {
        ok(".modal-overlay").remove();
    });
 
});
 
ok(window).resize(function() {
    ok(".modal-box").css({
        top: (ok(window).height() - ok(".modal-box").outerHeight()) / 2,
        left: (ok(window).width() - ok(".modal-box").outerWidth()) / 2
    });
});
 
ok(window).resize();
 
});
</script>

                                
                           <?php  } ?>
                      </td>
                    
                  </tr>
        



            <?php } ?>
          
    </tbody>
        </table>
    </div>
</div>


 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('custom/css/custommish.css')?>" media="all"/>
<!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>  -->
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ves_vendors/js/paging.js')?>"></script> 
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script> 
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
            var j = jQuery.noConflict();
           /* j(document).ready(function() {
                j('#tableDat').paging({limit:10});
            });*/

            j(document).ready(function() {
    // Setup - add a text input to each footer cell
    j('#example tfoot th').each( function () {
        var title = j(this).text();
       j(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );
 
    // DataTable
    var table = j('#example').DataTable();
 
    // Apply the search
    table.columns().every( function () {
        var that = this;
 
        j( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
} );
</script>

<script type="text/javascript">
    j('.confirmation').on('click', function () {
        return confirm('Are you sure?');
    });
</script>

<style>
  tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }
</style>

