
<div>
    <div style="text-align: center;">
     <h3>Selected Categories:</h3>
    </div>

    <?php 
  

    ?>
      <?php 
    
        $vendorIDses = Mage::app()->getRequest()->getParam('id');
        $modeladditional = Mage::getModel('vendors/additional')->load($vendorIDses,'vendor_id');
     // $modeladditional = Mage::getModel('vendors/additional')->load(8,'vendor_id');
        $selected_categories = $modeladditional->getCategories();
        $categories = explode(',',$selected_categories);
      //  $vendor_info = Mage::getModel('vendors/vendor')->load(8,'vendor_id');
        $vendor_info = Mage::getModel('vendors/vendor')->load($vendorIDses,'vendor_id');

        $groupid = Mage::getModel('vendors/source_group')->getOptionArray();
        $groupname= $groupid[$vendor_info->getGroupId()];
        $vendorname= $vendor_info->getFirstname().' '.$vendor_info->getLastname();
        $commission_model = Mage::getModel('vendorscommission/rule')->getCollection(); ?>
        <?php $_helper = Mage::helper('catalog/category') ?>
        <?php $categoryId = 2;?>
        <?php $category = Mage::getModel('catalog/category')->load($categoryId); ?>
        <?php $_categories = $category->getChildrenCategories(); ?>
     


    <div class="selectedCategories">
      <table style="border: solid 1px #000;" >
          <thead>
            <!-- <th style="padding: 5px;">Vendor Name</th> -->
            <th style="padding: 5px;">Vendor Id</th>
            <th  style="padding: 5px;">Selected Categories</th>
            <th style="padding: 5px;">(%) Commission</th>
            <th  style="padding: 5px;">Group Id</th>
            <th style="padding: 5px; border-right: none;">Registration Date</th>
           <!--  <th>No. of Sku loaded</th> -->
          </thead>
          <tbody>
            <tr>
               <!--  <td style="padding: 5px; width: 1%"><?php // echo $vendorname; ?></td> -->
            
                <td style="padding: 5px; width: 1%"><?php echo $vendor_info->getVendorId(); ?></td>
            
                <td style="padding: 5px; width: 1%">
                <?php 
                  foreach ($categories as $cat) {
                      $categoryModel = Mage::getModel('catalog/category')->load($cat);
                      echo $catName=$categoryModel->getName()."<br>";
                      $selected_cat_id[] = $categoryModel->getEntityId();
                   }
                ?>
                </td>

              
            
                <td style="padding: 5px; width: 1%"><?php //echo $vendor_info->getVendorId(); ?>
               <?php 
                foreach ($categories as $cat) {
                      $catCommission = Mage::getModel('catalog/category')->load($cat)->getData('set_commission');
                         
                            // $catCommission = Mage::getModel('catalog/category')->load($_category->getId())->getData('set_commission');
                                if($catCommission != ''){
                                  echo $catCommission."%";
                                  echo "<br>"; 
                                }
                            }
                 /* foreach ($commission_model as $comm) {
                      $assigncat = $comm['vendor_group_ids'];
                      $arr_group = explode(',',$assigncat);

                      if($vendor_info->getGroupId()==$arr_group[0]){
                            echo $comm['commission_amount']."<br>";  
                      }
                     }  */ 
                 
                     ?>
                </td>
                <td style="padding: 5px; width: 1%"><?php echo  $groupname; ?></td>
            
                <td style="padding: 5px; width: 1%; border-right: none;">
                <?php 
                  echo   $date = date('d-m-Y',strtotime($vendor_info->getCreatedAt()));
                ?>
                  
                </td>
              
            </tr>
          </tbody>

      </table>
      </div>
</div>

<style type="text/css">
  .addNewCategory ul {padding-top: 20px; clear: both; overflow: hidden;}
  .addNewCategory ul li {float: left; padding:0 10px 10px 0; width: 240px; }
  .selectedCategories tr td {border: solid 1px #000; border-bottom: none; border-left: none;  }
   .selectedCategories tr th {border: solid 1px #000; border-bottom: none; border-left: none;  border-top:none;  }

</style>