<?php
$collection = $this->getTagCollection();
?>
<div class="kb-tag-cloud">
    <h1><?php echo $this->__("Tags") ?></h1>
    <?php if ($collection->count()):?>
    <?php foreach($collection as $tag):?>
        <a href="<?php echo $tag->getUrl()?>" style="font-size:<?php echo $tag->getRatio()*70+75 ?>%;"><?php echo $tag->getName() ?></a>
    <?php endforeach?>
    <?php endif;?>
    <a href="<?php echo Mage::helper('kb/tag')->getListUrl() ?>">All Tags</a>
</div>
