<?php
$collection = $this->getTagCollection();
?>
<div class="kb-tag-list">
    <h1><?php echo $this->__("Tags") ?></h1>
    <?php if ($collection->count()):?>
    <?php foreach($collection as $tag):?>
        <a href="<?php echo $tag->getUrl()?>" style="font-size:<?php echo $tag->getRatio()*70+75 ?>%;"><?php echo $tag->getName() ?></a>
    <?php endforeach?>
    <?php else: ?>
        <p><?php echo $this->__("The are no Tags") ?></p>
    <?php endif ?>
</div>