
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="kbase-main-header page-title">
	<h1><?php echo $this->getHomeTitle()?></h1>
</div>
<div class="kbase-main search">
<div class="kbase-block-title">
	<?php echo $this->getBlockHtml("kbase_search") ;?>
	<div class="new-faq">
		<a class="bt_submit" href="<?php echo $this->getUrlNew() ?>">
			<span><?php echo $this->__('Submit a question') ?></span>
		</a>
	</div>
</div>
</div>
<div class="kbase-main kbase">
	<?php echo $this->sortBlockHtml() ?>
</div>
