<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_View_Tab_Info */ ?>
<?php $_quote = $this->getQuote() ?>
<div>
    <div class="box-left">
        <!-- General Request Information -->
        <!-- Customer Information -->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Customer Information')?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
    
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Customer Name')?></label></td>
                                <td class="value"><strong><?php echo $_quote->getCustomerName();?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Email')?></label></td>
                                <td class="value"><a href="mailto:<?php echo $_quote->getEmail();?>"><strong><?php echo $_quote->getEmail();?></strong></a></td>
                            </tr>
                            <?php if($this->showField('account_detail_telephone')):?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Telephone')?></label></td>
                                <td class="value"><strong><?php echo $_quote->getTelephone();?></strong></td>
                            </tr>
                            <?php endif;?>
                            <?php if($this->showField('account_detail_company')):?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Company')?></label></td>
                                <td class="value"><strong><?php echo $_quote->getCompany();?></strong></td>
                            </tr>
                            <?php endif;?>
                            
                            <?php if($this->showField('account_detail_taxvat')):?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('VAT/Tax Id')?></label></td>
                                <td class="value"><strong><?php echo $_quote->getTaxvat();?></strong></td>
                            </tr>
                            <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Quotation Management')?></h4>
            </div>
            <input type="hidden" name="quote[id]" value="<?php echo $this->getQuote()->getId()?>" />
            <div class="fieldset quote-info">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Last Update')?></label></td>
                                <td class="value"><strong><?php echo $this->formatDate($_quote->getUpdatedAt(),'long')?></strong></td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__('Quote Request Status')?></label>
                                </td>
                                <td class="value">
                                    <span id="quote_status">
                                        <select name="quote[status]" style="width: auto;"<?php if($this->isReadonly()):?> disabled="disabled"<?php endif;?>>
                                            <?php foreach($this->getAllQuoteStatus() as $key=>$option):?>
                                            <option value="<?php echo $key?>"<?php if($_quote->getStatus() == $key):?> selected="selected"<?php endif;?>><?php echo $option?></option>
                                            <?php endforeach;?>
                                        </select>
                                    </span>
                                </td>
                            </tr>
    
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__('Expiry Date')?></label>
                                </td>
                                <td>
                                    <div style="margin-top:3px;">
                                        <input class="input-text" type="text" value="<?php echo date('m/d/Y',strtotime($_quote->getExpiryDate()))?>" id="expiry" name="quote[expiry_date]">
                                        <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" style="position:relative; top: 1px;" id="expiry_btn">    
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Reminder Date')?></label></td>
                                <td>
                                    <div style="margin-top:3px;">
                                        <input class="input-text" type="text" value="<?php echo date('m/d/Y',strtotime($_quote->getReminderDate()));?>" id="reminder" name="quote[reminder_date]">
                                        <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif');?>" style="position:relative; top: 1px;" id="reminder_btn">
                                    </div>
                                </td>
                            </tr>    
                            <tr>
                                <td class="label"><label><?php echo $this->__('Customer Comment')?></label></td>
                                <td><div class="customer-coment"><?php echo $this->formatComment($_quote->getClientComment());?></div></td>
                            </tr>
    
                            <tr>
                                <td class="label">
                                    <label><?php echo $this->__('Note')?></label>
                                </td>
                                <td style="padding:10px 0px;">
                                    <textarea rows="4" id="internal_comment" name="quote[internal_comment]" style="width:94%;"><?php echo $_quote->getInternalComment();?></textarea>
                                    <p class="note"><span><?php echo $this->__('Not visible for customers')?></span></p>
                                </td>
                            </tr>
    
                        </tbody>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            //&lt;![CDATA[
            Calendar.setup({
                inputField: "expiry",
                ifFormat: "%m/%d/%Y",
                showTime: false,
                button: "expiry_btn",
                align: "Bl",
                singleClick: true
            });
            Calendar.setup({
                inputField: "reminder",
                ifFormat: "%m/%d/%Y",
                showTime: false,
                button: "reminder_btn",
                align: "Bl",
                singleClick: true
            });
        </script>
    </div>
    <div class="box-right">
        <!-- Message History -->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo $this->__('Message History')?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <textarea id="message_comment" style="height:80px; width:97%;" name="message[comment]"></textarea>
                    <div class="f-left">
                        <input type="checkbox" value="1" id="message_notify" name="message[is_customer_notified]"><label for="message_notify" class="normal"> <?php echo $this->__('Notify Customer by Email')?></label><br>
                    </div>
                    
                    <div class="f-right">
                        <button style="" onclick="submitQuoteMessage(<?php echo $_quote->getId()?>,'message_comment','quote-message-list',$('message_notify').checked)" class="scalable save" type="button" title="<?php echo $this->__('Submit Comment')?>"><span><span><span><?php echo $this->__('Send')?></span></span></span></button>
                    </div>
                    <div class="clear"></div>
                    
                    <?php echo $this->getChildHtml('quote_messages')?>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <?php echo $this->getChildHtml('quote_items');?>
</div>

