<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
    <td class="product-cart-image">
        <a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image">
            <img src="<?php echo $this->getProductThumbnail()->resize(80); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
        </a>
    </td>

    <td class="quote-item-product">
        <h2 class="product-name">
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
        </h2>
        <div class="product-cart-sku">
            <span class="label"><?php echo $this->__('SKU'); ?>:</span> <?php echo $this->escapeHtml($_item->getSku()); ?>
        </div>

        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
    </td>
    <td class="quote-item-comment">
        <?php echo $this->getComment();?>
    </td>
    <td class="product-cart-price">
        <span class="cart-price">
        <?php echo $this->helper('checkout')->formatPrice($this->getOriginalPrice()) ?>
        </span>
    </td>
    
    <td class="a-center" data-rwd-label="<?php echo $this->__('Qty'); ?>">
    <?php foreach($_item->getProposals() as $_proposal):?>
        <div class="proposal-cotnainer"><?php echo $_proposal->getQty()?></div>
    <?php endforeach;?>
    </td>
    <?php $_quote = $this->getQuote();?>
    <td class="a-left proposals">
        <?php foreach($_item->getProposals() as $_proposal):?>
            <div class="proposal-cotnainer">
                <?php if($_quote->getStatus()!=VES_VendorsQuote_Model_Quote::STATUS_PROCESSING):?>
                    <input type="radio" class="proposal-radio"<?php if($_quote->getStatus()!=VES_VendorsQuote_Model_Quote::STATUS_SENT):?> disabled="disabled"<?php endif;?> id="proposal-<?php echo $_proposal->getId()?>-radio" value="<?php echo $_proposal->getId()?>" data-item-id="<?php echo $_item->getId()?>" name="item[<?php echo $_item->getId()?>][default_proposal]" <?php if($_item->getDefaultProposal()==$_proposal->getId()):?> checked="checked"<?php endif;?>>
                <?php endif;?>
                <span><?php echo $_quote->getStatus()==VES_VendorsQuote_Model_Quote::STATUS_PROCESSING?$this->__('in process... '):$this->helper('checkout')->formatPrice($_proposal->getPrice())?></span>
            </div>
        <?php endforeach;?>
    </td>

</tr>


