<?php
$_rootCategory = $this->getCategory();
$_collection   = $this->getCategoryCollection();
?>
<div class="kb-category-view">
    <h1><?php echo $_rootCategory->getName() ?></h1>

    <?php if ($_collection->count()): ?>
        <?php foreach($_collection as $_category): ?>
        <div class="kb-category-view-subcategory">
            <?php $_articles = $this->getArticleCollection($_category); ?>
            <div class="category-name">
                <a href="<?php echo $_category->getUrl()?>"><?php echo $_category->getName() ?> <span class="num">(<?php echo $this->getArticlesNumber($_category) ?>)</span> <span class="more">»</span></a>
            </div>
            <div class="articles">
                <?php foreach($_articles as $_article):?>
                    <div class="article">
                        <a href="<?php echo $_article->getUrl()?>"><?php echo $_article->getName() ?></a>
                    </div>
                <?php endforeach?>
            </div>
        </div>
        <?php endforeach?>
    <?php else: ?>
        <?php echo $this->getChildHtml('kb.article.list') ?>
    <?php endif ?>
</div>