<?php
$testimonials = isset($testimonials)?$testimonials:null;
$auto_play_mode = $this->getConfig("autoplay");
$interval = $this->getConfig("interval");
$auto_play = $auto_play_mode?"true":"false";
$cols = $this->getConfig("autoplay");
$rows = $this->getConfig("autoplay");
$cols = (int)$this->getConfig("columns");
$cols = !empty($cols)?$cols:1;
$span = 12/$cols;
$itemsperpage = (int)$this->getConfig("max_items_page");
$itemsperpage = !empty($itemsperpage)?$itemsperpage:1;

$id = rand(1,10)+rand();
?>
<?php if( count($testimonials) ) { ?>
<div class="vestestimonialcarousel block owlproductcarousel">
	<?php if($this->getConfig('title')){?>
	<div class="block-title">
		<h2><?php echo $this->getConfig('title')?></h2>
	</div>
	<?php }?>
	<div class="block-content">
		<div id="vestestimonialowl<?php echo $id;?>" class="owl-carousel carousel slide vestestimonial">
				<?php
				$pages = array_chunk( $testimonials, $itemsperpage);
				?>
				<?php foreach ($pages as $k=>$tmptestimonials) {  ?>
				<div class="item <?php if($k == 0){echo "first";}  if($k == (count($pages) - 1)){echo "last";} ?>">
					<?php foreach( $tmptestimonials as $i => $testimonial ) {  $i=$i+1;?>
					<?php if( $cols == 1 || $i%$cols == 1 ) { ?>
						<?php } ?>
							<div class="testimonial-item">
								<div class="post-image">
									<img src="<?php echo $testimonial['thumb']; ?>" alt="<?php echo strip_tags($testimonial['profile']); ?>"/>
								</div>
								<?php if(  $testimonial['description'] ) { ?>
								<div class="latest-description"><?php echo $testimonial['description']; ?></div>
								<?php } ?>
								<?php if(  $testimonial['profile'] ) { ?>
									<div class="profile">
										<div><?php echo $testimonial['profile']; ?></div>
									</div>
								<?php } ?>
								<div class="testimonial-social pull-left text-right">
									<?php if ($testimonial['facebook']) { ?>
									<a href="https://www.facebook.com/<?php echo $testimonial['facebook']; ?>" class="carousel-control"><i class="fa fa-facebook">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['twiter']) { ?>
									<a href="https://www.twiter.com/<?php echo $testimonial['twiter']; ?>" class="carousel-control"><i class="fa fa-twitter">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['google']) { ?>
									<a href="https://plus.google.com/<?php echo $testimonial['google']; ?>" class="carousel-control"><i class="fa fa-google-plus">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['youtube']) { ?>
									<a href="https://youtube.com/user/<?php echo $testimonial['youtube']; ?>" class="carousel-control"><i class="fa fa-youtube">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['pinterest']) { ?>
									<a href="https://pinterest.com/<?php echo $testimonial['pinterest']; ?>" class="carousel-control"><i class="fa fa-pinterest">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['vimeo']) { ?>
									<a href="https://vimeo.com/<?php echo $testimonial['vimeo']; ?>" class="carousel-control"><i class="fa fa-vimeo">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['instagram']) { ?>
									<a href="https://instagram.com/<?php echo $testimonial['instagram']; ?>" class="carousel-control"><i class="fa fa-instagram">&nbsp;</i></a>
									<?php } ?>
									<?php if ($testimonial['linkedin']) { ?>
									<a href="https://linkedin.com/in/<?php echo $testimonial['linkedin']; ?>" class="carousel-control"><i class="fa fa-linkedin">&nbsp;</i></a>
									<?php } ?>
								</div>
								<?php if( $testimonial['video_link']) { ?>
								<p class="blog-readmore">
									<br>
									<a class="colorbox-t" href="<?php echo $testimonial['video_link'];?>"><?php echo Mage::helper("ves_testimonial")->__("Watch Video");?></a>
								</p>
								<?php } ?>
							</div>
						<?php if( $cols==1 || $i%$cols == 0 || $i==count($tmptestimonials) ) { ?>
					<?php } ?>

					<?php } ?>
				</div>
				<?php } ?>
		</div>
	</div>
</div>
<?php if( count($testimonials) > $itemsperpage ){ ?>
<script type="text/javascript">
jQuery(window).load(function() {
	var owl = jQuery('#vestestimonialowl<?php echo $id;?>');
        owl.owlCarousel({
            autoPlay: <?php echo $auto_play_mode?'true':'false';?>,
            slideSpeed: <?php echo $interval?(int)$interval:'500';?>,
            autoplayHoverPause: true,
            singleItem:true,
            lazyLoad:true,
            navigationText: ["<span class='md md-arrow-back'></span>","<span class='md md-arrow-forward'></span>"],
            slideBy: 1,
            loop: true,
            margin: 0,
            navigation: <?php echo (1 == $this->getConfig("show_navigator"))?'true':'false'; ?>,
            rtl: false,
            mouseDrag: true,
            touchDrag: true,
            autoWidth: false,
            responsive: true,
            items: <?php echo $cols?(int)$cols:1; ?>
        });
});
</script>
<?php } ?>
<script type="text/javascript"><!--
	jQuery(document).ready(function() {
		jQuery('.colorbox-t').colorbox({iframe:true, innerWidth:640, innerHeight:390});
	});
	//--></script> 
	<?php } ?>
