<!--Attachment-->
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-dropship-attachment"><?php echo Mage::helper('sales')->__('Attachment') ?></h4>
        <div class="tools"></div>
    </div>
    <fieldset>
        <div>
            <label for="fileToUpload">
                <?php echo $this->__('Please choose file to upload') ?>
            </label><br />
            <input type="file" name="fileToUpload[]" id="fileToUpload" <?php if ($this->getDropship()): ?>onchange="fileSelected();"<?php endif; ?> enctype="multipart/form-data"/>
            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_key"/>
            <?php if ($this->getDropship()): ?>
                <button onclick="uploadFile()" class="scalable task" type="button" id="Upload"><span><?php echo $this->__('Upload') ?></span></button>
            <?php endif; ?>
        </div>
        <div class="clear"></div>
        <div id="fileName">
        </div>
        <div id="fileSize">
        </div>
        <div id="fileType">
        </div>
        <div id="progressNumber">
        </div>
        <div class="file-list" style="margin-top: 10px">
            <?php
            if ($this->getDropship()) {
                $dropship = $this->getDropship();
                $physicalPathArr = explode(';', $dropship->getAttachmentPhysicalPath());
                foreach ($physicalPathArr as $physicalPath) {
                    if (!Mage::helper('inventoryplus')->isNullOrEmptyString($physicalPath)) {
                        $physicalPath = addslashes($physicalPath);
                        $physicalPath = str_replace(array("\"", "'"), array("&quot;", '&#039;'), $physicalPath);
                        ?>
                        <p>
                            <span><?php echo substr($physicalPath, strrpos($physicalPath, DS) + 1); ?></span>
                            <span><a
                                    onclick="deleteAttachment('<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/inp_inventorydropship/deleteattachment"); ?>', '<?php echo $physicalPath ?>', <?php echo $dropship->getId() ?>)">Delete</a></span>
                        </p>
                        <div class="clear"></div>
                        <?php
                    }
                }
            }
            ?>
        </div>
    </fieldset>
</div>
<?php if ($this->getDropship()): ?>
<script type="text/javascript">

    function fileSelected() {
        var file = document.getElementById('fileToUpload').files[0];
        if (file) {
            var fileSize = 0;
            if (file.size > 1024 * 1024)
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            else
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';

            document.getElementById('fileName').innerHTML = 'Name: ' + file.name;
            document.getElementById('fileSize').innerHTML = 'Size: ' + fileSize;
            document.getElementById('fileType').innerHTML = 'Type: ' + file.type;
        }
    }

    function uploadFile() {
        if(!$('fileToUpload') || !$('fileToUpload').value){
            alert('Please choose file to upload!');return false;
        }
        if($('loading-mask')){
            $('loading-mask').style.display = 'block';
        }
        var fd = new FormData();
        fd.append('fileToUpload', document.getElementById('fileToUpload').files[0]);
        fd.append('form_key', document.getElementById('form_key').value);
        fd.append('dropship_id', <?php echo $dropship->getId() ?>);
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange=function()
        {
            if (xhr.readyState==4 && xhr.status==200)
            {
                if(xhr.responseText != ''){
                    alert(xhr.responseText);
                    location.reload();
                }
            }
        }
        xhr.upload.addEventListener('progress', uploadProgress, false);
        xhr.addEventListener('load', uploadComplete, false);
        xhr.addEventListener('error', uploadFailed, false);
        xhr.addEventListener('abort', uploadCanceled, false);
        var url = '<?php echo $this->getUrl('adminhtml/inp_inventorydropship/uploadattachment'); ?>';
        xhr.open('POST', url);
        xhr.send(fd);
    }

    function uploadProgress(evt) {

    }

    function uploadComplete(evt) {
        if($('loading-mask')){
            $('loading-mask').style.display = 'none';
        }
    }

    function uploadFailed(evt) {
        if($('loading-mask')){
            $('loading-mask').style.display = 'none';
        }
    }

    function uploadCanceled(evt) {
        if($('loading-mask')){
            $('loading-mask').style.display = 'none';
        }
    }

    function deleteAttachment(url, filePath, dropshipId) {
        Element.show('loading-mask');
        var parameters = {file_path: filePath, dropship_id: dropshipId};
        var options = {
            method: 'post',
            parameters: parameters,
            onFailure: '',
            onComplete: function (transport) {
                if (transport.status == 200) {
                    Element.hide('loading-mask');
                }
            }
        };
        var request = new Ajax.Updater('dropship-attachment', url, options);
    }
</script>
<?php endif; ?>