<?php if($this->canSelectAndSell()):?>
<div class="vendor_product_selling_tool"><button class="button selling-button" onclick="vesSelectAndSell('<?php echo $this->getSelectAndSellUrl()?>',$(this))"><span><span><?php echo $this->__('Sell a Product like this')?></span></span></button></div>
<div id="vendor_product_adding_tool" style="display: none;">
	<div class="vendor_product_mask"></div>
	<div class="vendor_product_container" id="vendor_product_container">
		
	</div>
</div>
<script type="text/javascript">
	var vesSelectAndSellTranslation = <?php echo $this->getTransationJSON();?>;
</script>
<?php endif;?>