<div class="kb-s-form">
    <form action="<?php echo Mage::getUrl('kb/article/s')?>" method="GET" id="kb-s-form">
        <input name='s' id='s' placeholder="<?php echo __('What can we help you with?') ?>" class="input-text required-entry" value="<?php echo $this->getQuery() ?>">
        <button type="submit" title="Submit" class="button form-button"><span><span>Submit</span></span></button>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('kb-s-form', true);
    //]]>
    </script>
</div>