<?php $_product = $this->getProduct();?>
<?php $_vendor	= $this->getVendor();?>
<td>
	<ul>
		<li>
			<div class="rating-box">
				<div style="width:<?php echo $this->getRatingScore()?>%;" class="rating"></div>
			</div>
			<div><a target="_blank" href="<?php echo Mage::helper('vendorspage')->getUrl($this->getVendor(),'rating')?>"><?php echo $this->__('(%s Reviews)',$this->getReviewCount());?></a></div>
		</li>
	</ul>
</td>